### ISSUE TITLE
scroller

### ISSUE THREAD

**Issue by NoobTW** [rexrainbow/phaser3-rex-notes#1]
Does the scroller plugin work? I cannot run the example.

**Comment by rexrainbow** [comment]
I had not finished the spec of this plugin yet, sorry.

**Comment by NoobTW** [comment]
BTW, there is still some tweaks before running the examples, such as `npm i -g webpack, webpack-cli`. Maybe you can put them in install.bat.

And thanks for the awesome docs.

**Comment by rexrainbow** [comment]
Reopen this issue until I finished scroller plugin.

**Comment by rexrainbow** [comment]
[Scroller](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/scroller/index.html) is published. [Here](https://codepen.io/rexrainbow/pen/Kxzgre) is a live demo.

**Comment by Vi-jay** [comment]
> [Scroller](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/scroller/index.html) is published. [Here](https://codepen.io/rexrainbow/pen/Kxzgre) is a live demo.

Scroller don't work again ...

**Comment by rexrainbow** [comment]
That demo works fine on my pc and ipad5. What kind of issue in your testing?
