### ISSUE TITLE
Scene Plugin key in use: rexuiplugin

### ISSUE THREAD

**Issue by raphlee** [rexrainbow/phaser3-rex-notes#10]
If 2 scenes have ScenePlugin (created in preload function) to create some UI elements, then scene A call scene B, it's getting warning **Scene Plugin key in use: rexuiplugin**, and thrown an error: 
**Uncaught TypeError: Cannot read property 'add' of undefined.** 

This 'add' was used as: 'this.rexUI.add.' in scene B.

If I use another key, the UI won't work and stop.

**Comment by rexrainbow** [comment]
It is an issue of sequence of creating scene and installing scene plugin, I will report this issue to Rich
A workaround soution is installing scene plugin via Game configuration object, like [this](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/ui-label/two-scenes.js#L56-L62), which will loading scene plugin into plugin cache **before** creating any scene.

**Comment by rexrainbow** [comment]
Another workaround: 

UI plugin also attaches classes into `RexPlugins.UI`, you can create ui object via class name 
[`new RexPlugins.UI.Tabs(scene, config)`](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-tabs/#custom-class), 
[`new RexPlugins.UI.GridTable(scene, config)`](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-gridtable/#custom-class) 
directly.
[Here](https://codepen.io/rexrainbow/pen/qQGyYM) is a live demo.

**Comment by raphlee** [comment]
thx @rexrainbow , I'll try it.
