### ISSUE TITLE
How to set the depth of a dialog?

### ISSUE THREAD

**Issue by lumixraku** [rexrainbow/phaser3-rex-notes#100]
How to change the depth of a dialog?

It seems there is not way to set depth of a dialog.
Or It suggests  running rexUI in another parallel scene?

**Comment by lumixraku** [comment]
Sorry stupid question. 
I found Dialog extends Zone , and Zone extends GameObject.

**Comment by rexrainbow** [comment]
Two way to control depth:
- Placing ui components in another scene is a better solution. 
- Or set depth of each child game object individually.
