### ISSUE TITLE
Thank you for the Notes of Phaser3!

### ISSUE THREAD

**Issue by kenzan100** [rexrainbow/phaser3-rex-notes#101]
(Wanted to thank you, but don't know if this is the appropriate place.. )

I'm a backend engineer giving Phaser3 (or game dev in general) a try. I found [official API doc](https://photonstorm.github.io/phaser3-docs/Phaser.html) a bit intimidating, and the tutorials out in the web are somewhat mixed bag in terms of their quality.

Then I found your [Notes of Phaser3](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/group/), which to me at this time is filling the gap between various sample code and the official API doc perfectly.

just wanted to say thank you for your work! please keep it up!

**Comment by rexrainbow** [comment]
You are welcome. Have fun with phaser3 and my plugins!
