### ISSUE TITLE
VirtualJoystick does not work with zoom

### ISSUE THREAD

**Issue by koljakutschera** [rexrainbow/phaser3-rex-notes#102]
First, thank you very much for all the great docs! I think I use yours more than the original phaser ones 👍 

I found a small bug in your VirtualJoystick-Plugin:

If zoom is set to for example: this.cameras.main.zoom = 0.5 the VirtualJoystick-plugin does not interpret the touch position right.

**Comment by rexrainbow** [comment]
Thanks for this bug report. It has been fixed now, please download latest version of virtual joystick plugin from [here](https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/dist/rexvirtualjoystickplugin.min.js).
