### ISSUE TITLE
Dependency has vulnerability

### ISSUE THREAD

**Issue by DeeElGee** [rexrainbow/phaser3-rex-notes#103]
Hi,

papaparse has released an update to fix a security vulnerability. Could you update the version in package.json to 5.2.0 to fix this?

![Screenshot 2020-06-01 at 13 00 29](https://user-images.githubusercontent.com/359846/83412035-5c68e900-a411-11ea-828b-d04faeeb24a5.png)

**Comment by rexrainbow** [comment]
Thank you for this notification, I had upgraded papaparse.
