### ISSUE TITLE
Trouble with TextEdit keyboard input

### ISSUE THREAD

**Issue by cuianthony** [rexrainbow/phaser3-rex-notes#107]
Hello, I've been using your RexUI plugin for my game and it has been amazing. Just wanted to say thanks for all your hard work!

I'm currently running into an issue with my use of your TextEdit component.
The basic flow of my game is such: player starts in a Lobby scene and can navigate to a CreateGame scene, where they input the name of their game using TextEdit:
```
var nameText = new BBCodeText(this, reducedWidth/2, reducedHeight/2-80, 'my_legend', {
            color: 'yellow',
            fontSize: '35px',
            fixedWidth: 400,
            fixedHeight: 60,
            backgroundColor: '#333333',
            valign: 'center',
            halign: 'center'
})
this.add.existing(nameText);
var editNameText = new TextEdit(nameText);
```
From there the player moves to the main Game scene. In the Game scene, I add keys to the keyboard input and poll them in the update loop for camera scrolling
```
this.cameraKeys = this.input.keyboard.addKeys({
      up: 'w',
      down: 's',
      left: 'a',
      right: 'd',
      zoomIn: 'q',
      zoomOut: 'e'
});
```
```
if (this.cameraKeys["up"].isDown) {
      camera.scrollY -= this.cameraScrollSpeed;
} else if (this.cameraKeys["down"].isDown) {
      camera.scrollY += this.cameraScrollSpeed;
}

if (this.cameraKeys["left"].isDown) {
      camera.scrollX -= this.cameraScrollSpeed;
} else if (this.cameraKeys["right"].isDown) {
      camera.scrollX += this.cameraScrollSpeed;
}
```

The player can then choose to navigate back to the Lobby scene (and from there the CreateGame scene) to create another game. My issue is that, after shutting down the Game scene and starting the Lobby-->CreateGame, the EditText in CreateGame doesn't seem to receive the keyboard inputs of specifically the keys that I added in the Game scene. I'm having some trouble with fixing this. I've tried explicitly removing the keys before shutting down the Game scene, but it doesn't make a difference
```
private removeInputKeys() {
    this.input.keyboard.removeKey('w', true);
    this.input.keyboard.removeKey(this.cameraKeys['up'], true)
...
```
I've looked through the Phaser keyboard plugin docs and can't see anything else that might be interfering. From what I can tell your EditText is built on the DOM Textarea, but I'm also not sure how this may play into things.

Sorry for the long post, I hope the description is clear and maybe you can help me with fixing this. Thanks!

**Comment by rexrainbow** [comment]
Try to set `enableCapture` to false to prevent this issue, in [`addKeys` method](https://github.com/photonstorm/phaser/blob/master/src/input/keyboard/KeyboardPlugin.js#L410),  which works fine in my testing.

**Comment by cuianthony** [comment]
Works perfectly, thank you!
