### ISSUE TITLE
How to apply physics to a circle masked image?

### ISSUE THREAD

**Issue by AndysonDK** [rexrainbow/phaser3-rex-notes#108]
How do you apply physics to a circle masked image if it's possible?

https://rexrainbow.github.io/phaser3-rex-notes/docs/site/circlemaskimage/

**Comment by rexrainbow** [comment]
[Here](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/buildarcadeobject/) is a plugin/method to create arcade body, and inject arcade object methods.
