### ISSUE TITLE
rexUI.gridTable error.

### ISSUE THREAD

**Issue by iKest** [rexrainbow/phaser3-rex-notes#11]
Good day.
I get an error when i slide up the table cells  if the height of all cells is less than the height of the gridTable.
For example, if in your simplecode you specify the number of cells equal to 10

**Comment by rexrainbow** [comment]
Thank you for reporting this bug.
I had fixed this scrolling issue, please get the lastest version of rexUI plugins.
Now the slider bar will not be scollable if height of items is not larger then height of table.
