### ISSUE TITLE
OutlineEffectLayer plugin can't be imported

### ISSUE THREAD

**Issue by AndysonDK** [rexrainbow/phaser3-rex-notes#110]
Even though I've installed phaser3-rex-plugins locally using the following command:
`npm i phaser3-rex-plugins`

The following import statement results in an error:

`import OutlineEffectLayer from 'phaser3-rex-plugins/plugins/outlineeffectlayer.js';`

The plugin that I'm trying to use is this one:
https://rexrainbow.github.io/phaser3-rex-notes/docs/site/effectlayer-outline/#import-class

When I look at the git repository the files are there but not in the latest version of the npm package

**Comment by rexrainbow** [comment]
I had published current version of codebase to npm. Thanks for notification.

**Comment by AndysonDK** [comment]
Nice, it works now!
