### ISSUE TITLE
Cell margins for grid table?

### ISSUE THREAD

**Issue by cfortuner** [rexrainbow/phaser3-rex-notes#111]
Hey!

I was just wondering if there is anyway to apply margins to the cells in a container?

I see The option to add padding and I suppose I could just remove the cell backgrounds and use a custom icon or something but I think it would be cleaner if there was a way to set the cell margins.

Thanks!

**Comment by rexrainbow** [comment]
Grid table dose not have margin/padding for cell itself. Since you can design cell container, add a padding by shrinking background as your idea.

**Comment by cfortuner** [comment]
Makes sense! Just thought I would ask. Thanks for the quick reply :)
