### ISSUE TITLE
[UI Plugins] IsSceneObject return false for scene that extends extension of phaser.scene

### ISSUE THREAD

**Issue by as3mbus** [rexrainbow/phaser3-rex-notes#121]
hello first time submitting issue. and i'm still pretty new with phaser. 

i've traced an error when trying to make ScrollablePanel, and it doesn't seems to able to find the scene it need to refer to.

```
const SceneClass = Phaser.Scene;
var IsSceneObject = function (object) {
    return (object instanceof SceneClass);
}
export default IsSceneObject;
```

if im trying to parse a scene made from extending class below

```
import Phaser from 'phaser';

export default class BaseSceneController extends Phaser.Scene
{    
    constructor(superobj) {
        super(superobj);
        
    }

    init (data){

    }   
}
```

it'll return false if scene script extends BaseSceneController. 

and i manage to fix it by removing const, and directly refer Phaser.Scene. 

it might also be a problem on my way of trying to create my own extension of phaser.scene class. so i'd love if you could give me some insight for this as well :)

**Comment by rexrainbow** [comment]
[Here](https://codepen.io/rexrainbow/pen/WNwWRWy) is a testing of using `IsSceneObjec` method with custom scene extends from Phaser.Scene.
```
Phaser.Scene -> Base0 -> Base1 -> Demo
```
Which works fine.

**Comment by as3mbus** [comment]
as weird as it is , when i tried the same thing through different file it works just fine.

have you tried to call it from createScrollable ?
![image](https://user-images.githubusercontent.com/16043293/94426433-c1fa9580-01b7-11eb-813d-5c663fc6c4f8.png)

it encounter problem when it tried to access the scene from getSceneObject

or is there any possibility that my webpack configuration causing some problem.

here are some modification that i've done to produce log aboves

```
class DragSpeed {
    constructor(gameObject, config) {
        this.gameObject = gameObject;
        this.scene = GetSceneObject(gameObject);

        console.log("gameobject.scene : " + gameObject.scene);
        console.log("isSceneObject : " + IsSceneObject(gameObject.scene));
        console.log(gameObject.scene && IsSceneObject(gameObject.scene));
        console.log("getSceneObject : " + GetSceneObject(gameObject));
        // Event emitter
        this.setEventEmitter(GetValue(config, 'eventEmitter', undefined));

        this._enable = undefined;
        gameObject.setInteractive(GetValue(config, "inputConfig", undefined));
        this.resetFromJSON(config);
        this.boot();
    }
```

**Comment by rexrainbow** [comment]
I change previous [testing](https://codepen.io/rexrainbow/pen/WNwWRWy) for scrollable panel (line 5,6,7), and it still works fine.

**Comment by as3mbus** [comment]
now i'm really confused 🤔 

i'll try around using more primitive testing. 

thank you for responding 🙇
