### ISSUE TITLE
If the inputed text is empty, the text object gets deleted

### ISSUE THREAD

**Issue by Fisherswamp** [rexrainbow/phaser3-rex-notes#123]
There is an annoying bug I am experiencing where if all of the text in a textedit object is deleted by the user, or the text value is empty at any time, it deletes the bbcodetextobject. This is quite annoying 

Here is the example codepen for textedit. See what happens when you delete all of the characters
https://codepen.io/rexrainbow/pen/GaxqLZ

**Comment by rexrainbow** [comment]
I had fixed bug in that [demo](https://codepen.io/rexrainbow/pen/GaxqLZ), by adding `fixedHeight` and `valign` property, to prevent 0 size issue.
(When content of text is an empty string, size of text object will be `fixedWidth` x 0, no background is drawn)

**Comment by Fisherswamp** [comment]
Thanks!
