### ISSUE TITLE
Private sprite animations?

### ISSUE THREAD

**Issue by juanitogan** [rexrainbow/phaser3-rex-notes#124]
https://rexrainbow.github.io/phaser3-rex-notes/docs/site/sprite/#create-animation
Animation
Create animation
Global animation for all sprites

`scene.anims.create(config)`

Private animation for this sprite

`sprite.anims.create(config);`

----

Regarding the last line above, I can't tell that private animations are supported.  The create() function does not exist under sprite.anims.  That, or I'm terribly lost.

**Comment by rexrainbow** [comment]
That new feature will be added in next [phaser3 release (3.50)](https://github.com/photonstorm/phaser/releases/tag/v3.50.0-beta.7).
Sorry I did not separate the document of current release (3.24) and next release (3.50).

**Comment by juanitogan** [comment]
Ah hah... so I _was_ lost... just not terribly.  This is excellent news.  Thank you.  This will reduce wiring up animations on some of my sprites significantly.  Since I'm just now ramping up this project, I might switch to the 3.5 beta to take advantage of this.
