### ISSUE TITLE
UI Dialog dialog.getElement('description') returns null

### ISSUE THREAD

**Issue by tiangco** [rexrainbow/phaser3-rex-notes#125]
After creating a dialog object with content and description, accessing the description using the getElement returns a null. 

(Note: accessing the content this way works. could it be a typo?)

after creating a dialog with both content and description...

(portion of the config)
```
         ...
          content: self.add.text(0, 0, "Do you want to build a snow man?", {
            fontSize: "24px",
          }),
          description: self.add.text(0, 0, "here is the description", {fontSize: "24px"}),
         ...
```

```
     let content = dialog.getElement("content");  // returns the proper object
     let description = dialog.getElement("description");  // returns null

```

ref: https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-dialog/

**Comment by rexrainbow** [comment]
Reference of *description* element was missed. [Added back](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/templates/ui/dialog/Dialog.js#L216) at latest commit. (NPM package has not updated yet)
