### ISSUE TITLE
rexTagText not showing in Phaser 3.50.0-beta.9

### ISSUE THREAD

**Issue by darrylpizarro** [rexrainbow/phaser3-rex-notes#126]
I had this working in previous versions of Phaser, but now when I use this.add.rexTagText, the text no longer shows up.

this.infoTop.text = this.add.rexTagText(0, 36, 'test', {
      fontSize: '14px',
      fontFamily: 'Verdana, "Times New Roman", Tahoma, serif',
      stroke: '#000000',
      strokeThickness: 3,
      color: '#ffffff',
      align: 'center',
      tags: this.tags,
      wordWrap: { width: 200, useAdvancedWrap: false },

    }).setOrigin(0.5, 0.5).setSize(200, 60).setShadow(0, 2, 'rgba(0,0,0,0.5)', 6, true, true);

**Comment by rexrainbow** [comment]
Thanks for reporting this issue. It has been fixed in [v3.50-camera-shader](https://github.com/rexrainbow/phaser3-rex-notes/tree/v3.50-camera-shader) branch.

**Comment by darrylpizarro** [comment]
I can confirm that this is now working as it was previously. Thank you so much, you have done such an amazing job on everything!
