### ISSUE TITLE
waitEvent clear method

### ISSUE THREAD

**Issue by iKest** [rexrainbow/phaser3-rex-notes#13]
Please add for this class method of forced cleanup(with/no completion signal) . This is useful when one of the actions may fail and never emit complete signal. Thx.

**Comment by rexrainbow** [comment]
```javascript
var callback = waitevents.waitCallback();
```

This `callback` is a function object, invoked when waiting event finished. You can invoke it (i.e. `callback()`) manually when you want to remove/cleanup it.
