### ISSUE TITLE
Phaser 3.5 beta 10 issue

### ISSUE THREAD

**Issue by darrylpizarro** [rexrainbow/phaser3-rex-notes#131]
It looks like the latest Phaser beta might have broken the tag text plugin:
"Cannot read property 'alpha' of undefined at TagText.TextWebGLRenderer"

**Comment by rexrainbow** [comment]
**Master-branch** dose not support 3.50-betaX. Try [3.50-branch](https://github.com/rexrainbow/phaser3-rex-notes/tree/v3.50-camera-shader) for phaser 3.50-betaX.
BTW, My shader effect plugins do not work for 3.50-beta10 yet.

**Comment by darrylpizarro** [comment]
I am using that branch (updated) and still have the issue sadly

**Comment by rexrainbow** [comment]
I had exported plugins in [dist folder](https://github.com/rexrainbow/phaser3-rex-notes/tree/v3.50-camera-shader/dist)  again, hope it can help you.
[Testing](https://github.com/rexrainbow/phaser3-rex-notes/blob/v3.50-camera-shader/examples/tagtext/tagtext.js) using source code by webpack works well already.

**Comment by rexrainbow** [comment]
3.50 stable version is out. I also merger my 3.50 branch to master.
