### ISSUE TITLE
Cannot change position on menu items

### ISSUE THREAD

**Issue by d3sandoval** [rexrainbow/phaser3-rex-notes#137]
Thanks so much for this awesome library! It really removes a lot of the boilerplate required to get graphics drawn on the screen in Phaser.

I'm running into a problem where I'm trying to draw a radial menu on the screen and i am unable to position the elements once I've instantiated the menu.
![image](https://user-images.githubusercontent.com/7872348/101998811-648cc580-3c8b-11eb-8b33-15ddd3247211.png)

Here's a code sandbox reproducing the issue: https://codepen.io/d3sandoval/pen/OJRWbvG

Expected behavior:
I am able to set the x position of each button/menu item 

Actual behavior:
trying to setX, setY, setPosition, etc. doesn't seem to affect the items. Only rotation is working.

**Comment by rexrainbow** [comment]
It is design intent. Menu/button game objects are extends from [Sizer](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-sizer/), which layout children game objects in horizontal or vertical way. i.e. The position will be controlled by rexUI.

See [argument of creating menu](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-menu/#add-menu-object)
```
orientation : Main orientation of the menu, default is 1 (top to bottom)

    'left-to-right', 'horizontal','h', 'x', or 0 : Arrange buttons from left ot right.
    'top-to-bottom', 'vertical','v', 'y', or 1 : Arrange buttons from top to bottom.
```

**Comment by d3sandoval** [comment]
I see. Thanks for the explanation! It sounds like I should wrap my label elements with a different layout mechanism to get them into the places they need to be. Appreciate the guidance here :) helped a lot!

**Comment by rexrainbow** [comment]
The core mechanism of rexUI is to set position and size of children in `layout()` method. rexUI dose not have circular layout (yet). It can't support your requirement.
