### ISSUE TITLE
rexuiplugin problem with setPipeline() after update to Phaser 3.50.0 'Subaru'

### ISSUE THREAD

**Issue by CreativeSparkStudios** [rexrainbow/phaser3-rex-notes#139]
Phaser 3.5 was just released today, and when I updated to it in a current project, I got an error: 

```
Uncaught TypeError: t.setPipeline is not a function
    at d.q [as renderWebGL] (<anonymous>:1:11483)  
```
    
Searching for setPipeline() in my project files, I only found it used in rexuiplugin.min.js, so probably the plugin could be updated to use PipelineManager.set() instead of WebGLRenderer.setPipeline() as specified in the Phaser 3.5 'Subaru' release notes: https://phaser.io/download/stable

**Comment by rexrainbow** [comment]
All my shader effect plugins are all changed to post-fx pipeline, and tested pass. The usage also changed. Please see the *Apply effect* section (for example, [grayscale](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/shader-grayscale/#apply-effect)

**Comment by CreativeSparkStudios** [comment]
Okay, I can confirm that the error doesn't appear with Phaser 3.5 and the latest rexuiplugin.min.js file.
