### ISSUE TITLE
grid buttons - no of elements in a row

### ISSUE THREAD

**Issue by sthakral** [rexrainbow/phaser3-rex-notes#142]
Hi,

In the grid buttons - if we increase the no of buttons per row, we don't see all elements.
For example, in your demo
https://codepen.io/rexrainbow/pen/MWaExGE
if we have buttons array as 6*2 instead of 3*4, we only see 4 buttons.
What controls the no of elements per row?

**Comment by rexrainbow** [comment]
Number of items in a row/column is set from the dimension of `buttons` array in line 40, which can not be changed after created.
To append/remove item dynamically, try fixwidthsizer, see this [demo](https://codepen.io/rexrainbow/pen/XWWBvWG)

**Comment by sthakral** [comment]
Please check again. If I wanted a single row of 12 buttons, I'd describe the buttons array as 1*12 array. But in that case I only get a single button, not the expected 12.
Change line 40 to buttons: [
                [btns['7'], btns['8'], btns['9'],
                btns['4'], btns['5'], btns['6'],
                btns['1'], btns['2'], btns['3'],
                btns['<'], btns['0'], btns['.']]
            ],

**Comment by rexrainbow** [comment]
Thanks for reporting this bug. It has been fixed, please download latest version of rexUI (or upgrade npm package)
