### ISSUE TITLE
demo link is using a different plugin for effectlayer outline

### ISSUE THREAD

**Issue by tiangco** [rexrainbow/phaser3-rex-notes#143]
in https://rexrainbow.github.io/phaser3-rex-notes/docs/site/effectlayer-outline/
the demo link results in a 404

**Comment by rexrainbow** [comment]
EffectLayout plugin is *abandon*, please replace it by [rexOutlinePipeline](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/shader-outline/). 
Here is a [demo](https://codepen.io/rexrainbow/pen/dyGNrqa)
- Pointer-over/pointer-out any game object.

**Comment by tiangco** [comment]
thank you. (I really feel flattered that you answer my questions)
Q: can a game object have 2 rexOutlinePipeline outline effects at one time? I kind of looked at the documentation and it does not seem that I could do that. (and for some reason, the old plug-in seems to have stopped working when I updated to the new phaser and plugins)

**Comment by rexrainbow** [comment]
Yes, rexOutlinePipeline can apply to multiple game objects, with different configuration values.

Because that the new post-fx pipeline introduced in 3.50 can apply to/remove from each game object individually, my outline-effect-layer is not necessary anymore. Moreover, outlinePipeline dose not have camera zoom-in issue.

**Comment by tiangco** [comment]
Sorry, I was not too clear. what I meant was, can a single object have more than one outline effect applied to it. (with different thickness (and depth) to show). This was possible with the previous version - but it seems to me, that the OutlinePipeline may not have this ability.

**Comment by rexrainbow** [comment]
Got it. This case can't be supported in current post-fx pipeline case. 
I can try to fix outline-effect-layer, but I still prefer using post-fx pipeline version. How about creating another outline post-fx pipeline, which can support 2 (or more thickness/color) draw in order?

**Comment by tiangco** [comment]
Thank you. If you can get the outline post-fx pipeline to handle 2 or more thickness/outline - that works for me too. of course fixing the old way will also mean that I won't have to make any changes on my part. but if your plan is to deprecate this, then i think allowing the new version to have 2 or more outlines is better in the long run.

**Comment by rexrainbow** [comment]
My post-fx pipeline plugins have been improved, now outline post-fx pipeline can be cascaded many times. See [this demo](https://codepen.io/rexrainbow/pen/dyGNrqa).
Please get latest minify file of outline post-fx pipeline plugin.

**Comment by tiangco** [comment]
This is great! Now, one can do a rainbow outline!
Can we also add transparency to the color?... this way we can fade it and even have like an outline "explosion" effect :)

 
 

Sent: Friday, December 25, 2020 at 3:48 AM

**Comment by tiangco** [comment]
i'm using npm with
 "phaser3-rex-plugins": "^1.1.35". does this version have this new feature?

**Comment by rexrainbow** [comment]
Yes, the latest 1.1.35 has this new feature.

**Comment by rexrainbow** [comment]
> Can we also add transparency to the color?

No idea how to implement this feature, sorry.

**Comment by tiangco** [comment]
> 
> 
> Yes, the latest 1.1.35 has this new feature.

hi. not sure what I'm doing wrong, but the double outline does not seem to take. I only get the most recent outline. Please confirm that the version 1.1.35 has it. or is there something that i should do?

**Comment by rexrainbow** [comment]
I publish 1.1.36 for latest code again. Hope it can solve this issue.

**Comment by tiangco** [comment]
thank you! 1.1.36 works!
