### ISSUE TITLE
TagText  "Cannot Read Propert 'alpha' of undefined" [1.1.36]

### ISSUE THREAD

**Issue by as3mbus** [rexrainbow/phaser3-rex-notes#147]
hello i found an issue with later version of the plugin. 

the tag text won't render properly and produce an error as stated in the title

![image](https://user-images.githubusercontent.com/16043293/104412887-d82e3500-559f-11eb-8d27-9741f0fe26d6.png)

i am previously using 1.1.31 and it worked fine. but when im starting on a new project i can't seems to use the old code since updated version [1.1.36]. i also tried to downgrade the plugin and it works fine.

is there any change that i need to make for this version changes ?

**Comment by rexrainbow** [comment]
package >= 1.1.32 is worked for phaser3.50.

**Comment by as3mbus** [comment]
ah i see, so i would need to upgrade my phaser to later version in order to use it.

sorry if i missed it. but where can i find a change log / release note for these changes ?

**Comment by rexrainbow** [comment]
I did not publish change log at repo, only on [my discord channel](https://discord.gg/pZcYpjFbVs)..
