### ISSUE TITLE
Invalid Plugin: rexUI when loading rexuiplugin.min.js

### ISSUE THREAD

**Issue by Esrat21** [rexrainbow/phaser3-rex-notes#148]
i was using the plugin in the following code and it was working fine but suddenly stopped working.
```javascript
this.load.scenePlugin({
            key: 'rexuiplugin',
            url: 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/plugins/dist/rexuiplugin.min.js',
            sceneKey: 'rexUI'
        });
```
So I downloaded the rexuiplugin.min.js and tried the following code and didn't work.
```javascript
this.load.scenePlugin({
            key: 'rexuiplugin',
            url: './assets/js/rexuiplugin.min.js',
            sceneKey: 'rexUI'
        });
```
 I've been trying many ways to load the plugin but no one works for me.
 
 
![image](https://user-images.githubusercontent.com/61031102/104479696-7f13d080-55a2-11eb-8495-e64232c308af.png)

**Comment by rexrainbow** [comment]
Please upgrade phaser to 3.50 or higher version.

**Comment by Esrat21** [comment]
Now it works fine, thx!
