### ISSUE TITLE
Documentation for ForEachTileXY

### ISSUE THREAD

**Issue by ciabaros** [rexrainbow/phaser3-rex-notes#15]
In the following documentation page:
[https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board/#tile-position-world-position](url)

The part about board.forEachTileXY has incorrect definition; it suggests that "order" should somehow be part of the callback, when it really should follow the "scope" as the 3rd argument of forEachTileXY, rather than the third argument of the callback.

board.forEachTileXY(function(tileXY, board, order) {
    // var tileX = tileXY.x;
    // var tileY = tileXY.y;
}, scopr);

SHOULD BE:

board.forEachTileXY(function( tileXY, board ) {
    // var tileX = tileXY.x;
    // var tileY = tileXY.y;
}, scope, **order** );

**Comment by ciabaros** [comment]
Here's another small code-copying-hair-pulling-out typo on a different section of the same page (the "X" iteration has a > instead of a <):
[https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board/#for-each-tile](url)

for (var tileY = 0; tileY < board.height; tileY++) {
    for (var tileX = 0; tileX > board.width; tileX++) {
        // ...
    }
}

SHOULD BE:

for (var tileY = 0; tileY < board.height; tileY++) {
    for (var tileX = 0; tileX **<** board.width; tileX++) {
        // ...
    }
}

**Comment by rexrainbow** [comment]
Thank for this issue, all fixed.
