### ISSUE TITLE
inherited gridButtons displayList is null

### ISSUE THREAD

**Issue by tylerroost** [rexrainbow/phaser3-rex-notes#150]
I am trying to create an object that inherits from gridButtons where the buttons themselves are objects inheriting from Label. Nothing displays on screen and on further inspection it seems like displayList is null for both the inherited gridButtons object and the inherited Label objects.
I am also getting the error TypeError: Cannot read property 'addToRenderList' of undefined.
Though I believe this is because the displayLists are null. I could be wrong though.

I am adding both objects to the scene in the constructors.

Any help or questions that could lead me in the right direction would be greatly appreciated.

**Comment by rexrainbow** [comment]
Have you added `scene.add.existing(this);` , to add GameObject to display list of scene?
[Reference](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-gridbuttons/#custom-class)

**Comment by tylerroost** [comment]
yes this is what I mean by I am adding both objects to the scene in the constructors

**Comment by rexrainbow** [comment]
`addToRenderList` is a new method introducted in phaser3.52.0. Try to upgrade your phaser3 version to 3.52.0.
( But phaser3.52.0 has some other bugs BTW )

**Comment by tylerroost** [comment]
I will make an attempt thank you.
