### ISSUE TITLE
Button plugin not firing click events if it contains Sprites

### ISSUE THREAD

**Issue by stevium** [rexrainbow/phaser3-rex-notes#151]
Since phaser `3.52.0`,  the `ButtonPlugin` is not working with sprites.

For example:
```ts
scene.rexUI.add
  .buttons({ 
    buttons: [
      scene.rexUI.add.label({
        background: scene.add.sprite()
      })
    ]
  })
  .on('button.click', () => {  
    ...this does not execute  
  });
```

Other objects (i.e. `roundRectangle`) work fine.

I did some debugging and found out that the change on `Sprite.js` from [this commit](https://github.com/photonstorm/phaser/commit/59e89fa78847663a51d8518ece620207506fd85f) might be the cause. 

If I revert these 2 lines, it works fine:

```ts
this.on(GameObjectEvents.ADDED_TO_SCENE, this.addedToScene, this);
this.on(GameObjectEvents.REMOVED_FROM_SCENE, this.removedFromScene, this);
```

**Comment by stevium** [comment]
Sorry my bad. Ignore my comments related to `Sprite`. 

After doing some more checks it looks like `setInteractive()` is breaking it, when called on any `GameObject` not just `Sprite` when it is part of `Label` as shown above on `background` example.

**Comment by rexrainbow** [comment]
See issue #149

**Comment by stevium** [comment]
I've applied the changes from the PR, and can confirm it now works as expected.
