### ISSUE TITLE
VirtualJoystick touch event at edge/outside window causes JS error

### ISSUE THREAD

**Issue by kris-sum** [rexrainbow/phaser3-rex-notes#156]
When using the virtual joystick, if your thumb/cursor moves to the edge of the phaser game window then a console error is produced : **Uncaught TypeError: pointer.camera is undefined**

TouchCursor.js

    onKeyDown(pointer) {
        if (this.pointer !== pointer) {
            return;
        }

        // Vector of world position
        this.setVector(
            (this.gameObject.x + pointer.camera.scrollX), <--- here

You can see this happen on the demo site at https://codepen.io/rexrainbow/pen/oyqvQY - start with your touch event inside the joystick and then move to the edge of the phaser game window.

---
PS, thank you so much for your notes and plugins!

**Comment by rexrainbow** [comment]
I did not see any error message in console in chrome or firefox browser in win10. 
Could you list your testing environment more detail?

**Comment by kris-sum** [comment]
Ok that's weird, I can't reproduce it on my machine anymore ... must have been a weird browser bug. Will retry it on my dev machine later and will close if the problem's gone away

**Comment by kris-sum** [comment]
Aha! It only does it if you use a touch device, not a mouse cursor. 

Happens on Firefox and Edge, haven't got chrome installed on this tablet.

Firefox reports

    Uncaught TypeError: t.camera is undefined
    value https://cdpn.io/rexrainbow/fullpage/oyqvQY line 1 > injectedScript:1
    emit https://cdn.jsdelivr.net/npm/phaser@3.52.0/dist/phaser.min.js:1
    processMoveEvents https://cdn.jsdelivr.net/npm/phaser@3.52.0/dist/phaser.min.js:1
    update https://cdn.jsdelivr.net/npm/phaser@3.52.0/dist/phaser.min.js:1

Edge reports

    Uncaught TypeError: Cannot read property 'scrollX' of undefined
    at o.value (<anonymous>:1:8667)
    at initialize.o.emit (phaser.min.js:1)
    at initialize.processMoveEvents (phaser.min.js:1)

**Comment by rexrainbow** [comment]
I add a condition to check if camera is valid or not, please test your case with this latest version of virtual-joystick plugin.

**Comment by rexrainbow** [comment]
The trigger logic of 'pointermove' event seem not the same between mouse input and touch input.

See my reported [issue](https://github.com/photonstorm/phaser/issues/5592)

**Comment by kris-sum** [comment]
That seems to have fixed it, thanks! Please bump the npm package :)

**Comment by rexrainbow** [comment]
New npm package (1.1.40) upgraded.
