### ISSUE TITLE
Missing `CurcularProgress.js` file

### ISSUE THREAD

**Issue by hktr92** [rexrainbow/phaser3-rex-notes#161]
Hello.
I wanted to implement a dialog using rexUI, typescript and nodejs. when compiling with webpack, i have the following error in console:

>Module build failed: Module not found:
"./node_modules/phaser3-rex-plugins/templates/ui/ui-components.js" contains a reference to the file "./circularprogresscanvas/CircularProgress.js".
This file can not be found, please check it for typos or update it if the file got moved.

After opening up the `ui-components.js` file in editor, it seems that `./circularprogresscanvas/CircularProgress.js` file is missing, the directory only containing `CurcularProgressCanvas.js` and `Factory.js`.

I didn't find any references to it except for export part, so it might be a hanging / unused import? as per this commit 8b3119bf268243a1ef06a6d471904a03e3e94ae6

Using:
- Phaser ^3.54
- phaser3-rex-plugins ^1.1.43

**Comment by rexrainbow** [comment]
Thanks for reporting this bug, I had upgraded npm package to *1.1.44* to fix it.
