### ISSUE TITLE
How to use with typescript?

### ISSUE THREAD

**Issue by x-wk** [rexrainbow/phaser3-rex-notes#163]
How to use with typescript , is there a type definition?

**Comment by rexrainbow** [comment]
No ts definition file provided for my phaser3 plugins, sorry.

**Comment by khasanovbi** [comment]
You can use https://github.com/khasanovbi/phaser3-rex-plugins-types. There are already quite a few types described.

**Comment by rexrainbow** [comment]
Typescript declaration files of rexUI released in npm package 1.1.54
[Document](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-overview/#using-typescript-declaration-file), [example](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/ui-wrap-expand-text/speech-bubble-background-ts.ts).

**Comment by x-wk** [comment]
> Typescript declaration files of rexUI released in npm package 1.1.54
> [Document](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-overview/#using-typescript-declaration-file), [example](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/ui-wrap-expand-text/speech-bubble-background-ts.ts).

Thank you for your nice work

**Comment by wzurborg** [comment]
There are now some `*.d.ts` files but a lot are still missing or have the wrong file extension `*.js`.

E.g. I cannot import `MoveTo` like:
``` typescript
import MoveTo from 'phaser3-rex-plugins/plugins/moveto';
```

When I rename the file `phaser3-rex-plugins/plugins/moveto.js` to `moveto.d.ts`, then the import works.

**Comment by rexrainbow** [comment]
@wzurborg 
Typescript declaration files still work in progress, now only rexUI rexBoard, virtual-joystick, and post-fx pipelines are finished.

**Comment by rexrainbow** [comment]
Most of d.ts files are added, in npm package 1.1.58.

**Comment by wzurborg** [comment]
Great, thank you!
