### ISSUE TITLE
How can I call textplayer's nextpage in my function?

### ISSUE THREAD

**Issue by hsnks100** [rexrainbow/phaser3-rex-notes#168]
refer: https://rexrainbow.github.io/phaser3-rex-notes/docs/site/textplayer/

on enter key press:
When textplayer is typing, I want to complete page complete.
When textplayer's page is complete, I want to jump next page. 

Thus I try to process scene input, 
```
text.playPromise(content);
this.input.enabled = true; 
this.input.keyboard.on('keydown', (eventName, event) => {
        // something...
});
```

But I don't know calling textplayer's next page. 

In advance, thank you.

**Comment by rexrainbow** [comment]
Will try to add method for these requests later. Thanks for advice.

**Comment by rexrainbow** [comment]
Here is a [test case](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/textplayer/show-page.js), [live demo](https://codepen.io/rexrainbow/pen/XWMMpjE) of 

- [Show current page under ENTER key](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/textplayer/show-page.js#L104-L106) : Method `text.showPage()`
- [Start typing next page under ENTER key](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/textplayer/show-page.js#L91): Config `nextPageInput: 'ENTER'`

**Comment by hsnks100** [comment]
Now can't I solve this problem? I try to review your plugin source, but I can't find way. 

Any tricky way is okay, so let me know.

**Comment by rexrainbow** [comment]
This [test case](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/textplayer/show-page.js), shows how to
- [Show page](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/textplayer/show-page.js#L105) after enter key down,
- [Typing page](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/textplayer/show-page.js#L91) after enter key down

But there still has bug in `showPage()` method, I will fix it later.

**Comment by rexrainbow** [comment]
Bug fixed in `showPage()` method. See this [live demo](https://codepen.io/rexrainbow/pen/XWMMpjE).

**Comment by rexrainbow** [comment]
Feature shown in this [demo](https://codepen.io/rexrainbow/pen/XWMMpjE), see line 103~113.

**Comment by rexrainbow** [comment]
Will close this fixed issue.
