### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by iKest** [rexrainbow/phaser3-rex-notes#17]
Good day!
With rollup i get warn:
Circular dependency: node_modules\phaser3-rex-plugins\templates\ui\menu\Menu.js -> node_modules\phaser3-rex-plugins\templates\ui\menu\ExpandSubMenu.js -> node_modules\phaser3-rex-plugins\templates\ui\menu\Menu.js

**Comment by rexrainbow** [comment]
Thanks, I had removed this circular dependency, please get the latest commit.
