### ISSUE TITLE
Fix to rexuiplugin.min.js broke dialog background

### ISSUE THREAD

**Issue by itumel** [rexrainbow/phaser3-rex-notes#171]
Hello,

I noticed that 3 hours ago a fix was made to rexuiplugin.min.js. And now this is what the dialog looks like:

![image](https://user-images.githubusercontent.com/6449281/119721255-3d0d6c00-be6b-11eb-83de-116b3ffe5d55.png)

It no longer has the background.

**Comment by Maz-POTAT** [comment]
This makes rex-ui and also phaser3 off.
it needs quick fix

**Comment by rexrainbow** [comment]
In 3.55.1, phaser3 try to fix [an issue of filling arc](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md#bug-fixes), but still has [bug](https://github.com/photonstorm/phaser/issues/5720.

Please downgrade phaser3 to 3.54, with my npm package 1.1.47, which also has previous version of minify files.

**Comment by rexrainbow** [comment]
Commits yesterday has been reversed, which can work well with phaser3.54.0.

**Comment by itumel** [comment]
The dialog is back to normal therefore I'll close the issue.

**Comment by rexrainbow** [comment]
The bug of round-rectangle will be still there, if using phaser >3.55.0.
I will open this issue again until it is fixed with latest phaser3 engine.

**Comment by rexrainbow** [comment]
Export plugins and upgrade npm package for phaser3.55.2.
