### ISSUE TITLE
Dialog Background Broken rehappening

### ISSUE THREAD

**Issue by Maz-POTAT** [rexrainbow/phaser3-rex-notes#173]
Please make fix this issue
I am using lots of rexui dialogs
And it make my app poor..
Please fix it asap...
I am using Phaser3.54.0

**Comment by rexrainbow** [comment]
Please upgrade phaser3 to 3.55.2, with the latest minify file of rexUI or from npm package 1.1.49.
[dialog demo](https://codepen.io/rexrainbow/pen/oQjMWE).
