### ISSUE TITLE
Scrollable Panel Issue occurred after I upgrade phaser.js from 3.54.0 to 3.55.2

### ISSUE THREAD

**Issue by Maz-POTAT** [rexrainbow/phaser3-rex-notes#174]
"Cannot read property 'removeKey' of null" error occur after stop scene that include Scrollable Panel
When I remove Scrollable Panel the error not occur.
![image](https://user-images.githubusercontent.com/84121020/119972588-0f373d00-bfbb-11eb-9bfa-d2c1751bfbb3.png)
![image](https://user-images.githubusercontent.com/84121020/119972647-20804980-bfbb-11eb-9ad6-5b81991483f0.png)
![image](https://user-images.githubusercontent.com/84121020/119972678-2b3ade80-bfbb-11eb-889a-4984069668bd.png)
![image](https://user-images.githubusercontent.com/84121020/119972747-41e13580-bfbb-11eb-852b-5bdbad79d780.png)

**Comment by rexrainbow** [comment]
Thanks for this bug reporting.
This bug has been fixed, please uses latest minify file of rexUI. Npm package will upgraded tomorrow.
