### ISSUE TITLE
iOS Safari and anchor plugin don't work

### ISSUE THREAD

**Issue by marcusx2** [rexrainbow/phaser3-rex-notes#176]
On iOS Safari, the anchor plugin doesn't work properly. Things that you anchor to the right gets shifted way to the left for some reason. It works pefectly on Android chrome and on desktop though. I tested without your plugin, using Phaser.Scale.FIT and setPosition to anchor, and it worked on all browsers, Safari included. The problem is, I want to use Phaser.Scale.HEIGHT_CONTROLS_WIDTH, not Phaser.Scale.FIT. And anchoring without your plugin only works if I use Phaser.Scale.FIT

This is probably not even your plugin's fault, but some extra configuration/workaround is necessary to work on Safari. 

Love the plugin by the way, thanks! Pitty that I can't use it because of Safari.

**Comment by marcusx2** [comment]
I've been investigating further, and what happens is that the right: 100% is not at the end of the device, like it should be.

**Comment by rexrainbow** [comment]
Anchor plugin on ipad Safari works fine in my [test](https://codepen.io/rexrainbow/pen/oVxWVB).
*Phaser.Scale.FIT* does not have to use anchor, world size is equal to window size at all time.
Other modes, like *Phaser.Scale.ENVELOP*, the world size might not equal to window size, thus ui need anchor to set position related on window size.

**Comment by marcusx2** [comment]
I discovered the issue. To work on Safari, you need to set initial-scale=1 on the metatag
`<meta name="viewport" content="width=device-width, initial-scale=1">`
otherwise you will have problems.

Now I have another problem: the bottom bar on Safari hides part of my game UI. [This bar](https://cdn.osxdaily.com/wp-content/uploads/2014/08/show-navigation-bar-safari-ios.png) . This seems to be a problem a lot of people have. Do you know how can I work around this with your plugin or phaser in general? The game needs to take into account this annoying bar,

**Comment by rexrainbow** [comment]
I know that bar, but could not see it in my test normally. 
Sorry I can't help you in this case, you might post this issue on [phaser forum](https://phaser.discourse.group/), or discord channel.

**Comment by marcusx2** [comment]
Not an issue with this plugin. This plugin should be incorporated in phaser by the way. It's essential and saved my skin

**Comment by marcusx2** [comment]
@rexrainbow could you do a plugin like this one, but for scaling? To keep the scale consistent across devices even if the scale mode isn't fit. Should I open a new issue?

**Comment by rexrainbow** [comment]
Sorry I can't reproduce your issue in my ipad Safari. Anchor works fine. I use
```javascript
    scale: {
        mode: Phaser.Scale.ENVELOP,
        autoCenter: Phaser.Scale.CENTER_BOTH,
    },
```
in this [test case](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/anchor/anchor.js#L61-L64)

**Comment by marcusx2** [comment]
> Sorry I can't reproduce your issue in my ipad Safari. Anchor works fine. I use
> 
> ```js
>     scale: {
>         mode: Phaser.Scale.ENVELOP,
>         autoCenter: Phaser.Scale.CENTER_BOTH,
>     },
> ```
> 
> in this [test case](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/anchor/anchor.js#L61-L64)

Yes it was a problem with the meta tag. What about the scaling plugin to work with the anchor? Because even though it anchors correctly, the scale is still looks different on different devices if I use ENVELOP mode.

**Comment by rexrainbow** [comment]
Ah, sorry, no idea about NOT using these configuration :
`<meta name="viewport" content="width=device-width, initial-scale=1">`
I only copy these configuration from other template directly.

**Comment by marcusx2** [comment]
@rexrainbow Your example doesn't work,it's only on the codepen that it works. It has the same problem I described, "initial-scale" has nothing to do with it, it creates another problem. Maybe it's my html that is wrong, but please see [what I did ](https://we.tl/t-WEotQjnwnx)

**Comment by rexrainbow** [comment]
Can't reproduce it on my ipad safari browser.

**Comment by marcusx2** [comment]
The problem is with this code on the getviewport function:
```
if (((autoCenter === 1) || (autoCenter === 2))) {
        out.width -= out.x;
    }
    if (((autoCenter === 1) || (autoCenter === 3))) {
        out.height -= out.y;
    }
```

It only works on Chrome, it breaks opera, firefox, and safari. Need to find a code that works on all of them ;_;

**Comment by rexrainbow** [comment]
What is your [`autoCenter` setting](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/anchor/anchor.js#L63) in this case?

**Comment by marcusx2** [comment]
CENTER_BOTH

**Comment by rexrainbow** [comment]
No idea. GetViewPort might not work if autoCenter is not CENTER_BOTH. But your are using CENTER_BOTH.

**Comment by marcusx2** [comment]
Here is the updated code that I am using that works on all browsers:
```
var GetViewport = function (out) {
    if (out === undefined) {
        out = new Phaser.Geom.Rectangle();
    } else if (out === true) {
        out = globRect;
    }

    var scaleManager = scene.scale;
    var bounds = scaleManager.canvasBounds;
    var scale = scaleManager.displayScale;
    var autoCenter = scaleManager.autoCenter;
    out.x = (bounds.x >= 0) ? 0 : -(bounds.x * scale.x);
    out.y = (bounds.y >= 0) ? 0 : -(bounds.y * scale.y);
    out.width = (bounds.width * scale.x) - out.x;
    out.height = (bounds.height * scale.y) - out.y;

	if (/Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor)) {
		if (((autoCenter === 1) || (autoCenter === 2))) {
			out.width -= out.x;
		}
		if (((autoCenter === 1) || (autoCenter === 3))) {
			out.height -= out.y;
		}
	}
    return out;
}
```

I explicitly check if it's the chrome browser. It's dirty and not very safe, but it's the solution I got for now.
