### ISSUE TITLE
scale plugin request

### ISSUE THREAD

**Issue by marcusx2** [rexrainbow/phaser3-rex-notes#177]
I'd like to request a scale plugin that works in a similar fashion as the anchor plugin. I want to be able to have images that look the same even with the scale mode set to ENVELOP. To illustrate what I mean, see this
![image](https://user-images.githubusercontent.com/5656275/120906701-f15c7e80-c631-11eb-870a-668a2436e868.png)

**Comment by rexrainbow** [comment]
[Here](https://codepen.io/rexrainbow/pen/jOBxKxE) is a demo of anchor position and resize according to [view-port](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-overview/#view-port). See line 30-40.

**Comment by marcusx2** [comment]
Thank you!
Code to get viewport correct dimensions: https://github.com/rexrainbow/phaser3-rex-notes/blob/master/plugins/utils/system/GetViewport.js

FIT mode, the view port is equal to camera width/height

**Comment by rexrainbow** [comment]
FIT mode will keep the ratio of game window inside the given div, thus it won't be the actual dimensions of the device.
