### ISSUE TITLE
Rex Toast Error

### ISSUE THREAD

**Issue by Maz-POTAT** [rexrainbow/phaser3-rex-notes#182]
Error Occurred after finish showing Dialog.
![image](https://user-images.githubusercontent.com/84121020/123728109-bfa3a400-d8cd-11eb-9888-44f267676c5f.png)

**Comment by Maz-POTAT** [comment]
Plz check this and let me know the solution

**Comment by Maz-POTAT** [comment]
plz make it live asap.
my all projects are not work.

**Comment by Maz-POTAT** [comment]
![image](https://user-images.githubusercontent.com/84121020/123729450-f4b0f600-d8cf-11eb-836f-a130038bdc9a.png)

**Comment by rexrainbow** [comment]
Ah, I change the method name today, please change
`toast.show(message)` to `toast.showMessage(message)`. 

I am writing typescript definition files, and find some naming conflict.

**Comment by rexrainbow** [comment]
Please join [discord channel](https://discord.gg/pZcYpjFbVs) of my rex-plugins. It includes change-log.

**Comment by Maz-POTAT** [comment]
I used showMessage() but it happened.

**Comment by rexrainbow** [comment]
Bug fixed, please get latest version of rexUI plugins. 
Sorry for this breaking changing.

**Comment by Maz-POTAT** [comment]
Thanks for your work.
Btw I want to tell you something.
In some cases, I am making games with PhserJS and release them to the
android/ios app with Cordova.
So if you change some function names, it would occur all of my games do not
work.
I hope you think of this prob in the future.

**Comment by rexrainbow** [comment]
Agree that it is hurt for breaking changing. I will ensure it won't happen too much.
Or I have to post a message of breaking changing somewhere to notify user.

**Comment by rexrainbow** [comment]
It seems that no more compatible problem in current updating, issue closed.
