### ISSUE TITLE
setResolution for TagText

### ISSUE THREAD

**Issue by Solid-Metal** [rexrainbow/phaser3-rex-notes#184]
Phaser 3 have really bad behaviour with scale manager, especially with text, i usually fix it with 

`.setResolution(2));` added on each text component

and it works fine and well for based text, i wish this functionality also added for TagText

**Comment by rexrainbow** [comment]
`tagText.setResolution(value)` was added to class of TagText/BBCodeText already. But I did not add it to document or test it before, will do that these days.

**Comment by Solid-Metal** [comment]
> `tagText.setResolution(value)` was added to class of TagText/BBCodeText already. But I did not add it to document or test it before, will do that these days.

is it possible it might be because i use your TS definition ?, since it said its not available there, hopefully its also updated

**Comment by rexrainbow** [comment]
Add a [test](https://codepen.io/rexrainbow/pen/ExmggYE) for resolution, also update the document and ts define.
NPM package will be upgraded next week.

**Comment by Solid-Metal** [comment]
> Add a [test](https://codepen.io/rexrainbow/pen/ExmggYE) for resolution, also update the document and ts define.
> NPM package will be upgraded next week.

awesome !, thanks for the fast response !

**Comment by rexrainbow** [comment]
How to improve text's display quality via set higher resoluition? In [my test](https://codepen.io/rexrainbow/pen/ExmggYE), resolution = 1 has best display quality.

**Comment by rexrainbow** [comment]
NPM package released, issue closed.
