### ISSUE TITLE
Using PerspectiveCard in a container

### ISSUE THREAD

**Issue by wzurborg** [rexrainbow/phaser3-rex-notes#186]
Hi, I recently discovered your plugins and I am trying to migrate my card game to using the PerspectiveCard, replacing my own class with face and back images. This works in principle, and I can also flip the cards nicely, which was one of my goals for the migration.

I use a container per player, each holding 3 cards, and one container with 3 cards in the middle of the table. A player may swap all 3 cards with the ones on the table, so I tried swapping the cards by taking them out of their respective container and adding them to the other (with the help of a temp object). But in the end the cards keep their place, even though they are exchanged in their containers.

I tried this with both the official container and your ContainerLite, where the latter gives me an additional problem because getChildren() only gives me a reference that changes when the container changes. But that is another problem.

I also tried to swap the containers as a whole by changing their respective x,y coordinates. Same result, all cards stay where they are.

I think the main issue is that the PerspectiveCard keeps its absolute world coordinates, in contrast to a standard GameObject, e.g. an Image, whose coordinates are relative to its parent container. So in the end swapping the cards or moving the container does not affect the position of the cards at all. This would contradict the purpose of the container, which is that you can move it around (rotate it, stretch it, whatever) and all children are moved together with it.

I suspect I am making a horrible mistake, but what am I missing, and how can I use the PerspectiveCard in a container properly?

**Comment by rexrainbow** [comment]
Could you post a simplest, runnable test code for this case?

**Comment by wzurborg** [comment]
ok will try

**Comment by wzurborg** [comment]
I tried to post on phaser labs but I could not get the import statements right. So I am posting a local example hoping that you can reproduce the issue or directly see what I am doing wrong. You will need a card image to run the demo.

```typescript
import { PerspectiveCard } from 'phaser3-rex-plugins/plugins/perspectiveimage';

/**
 * This demo creates two containers, the first holds a PerspectiveCard, 
 * the second an Image for comparison. Both contained objects are created 
 * with coordinates (0, 0) to put them into the center of the container.
 * 
 * Observations:
 * 1. The PerspectiveCard ignores the position of the container and is 
 * rendered at its own coordinates, while the image is rendered with 
 * coordinates relative to the container.
 * 
 * 2. Increasing the x coordinate of each container causes the image to
 * move to the right, as expected, while the PerspectiveCard keeps its 
 * position.
 * 
 */
export default class Demo extends Phaser.Scene {

    container1: Phaser.GameObjects.Container;
    container2: Phaser.GameObjects.Container;
    card1: PerspectiveCard;
    card2: Phaser.GameObjects.Image;

    constructor() {
        super({
            key: 'demo'
        })
    }

    preload() {
        this.load.image('front', 'some_card_image.png');
    }

    create() {
        // creates a PerspectiveCard
        this.card1 = new PerspectiveCard(this, {
            x: 0, y: 0,
            front: { key: 'front' }
        });

        // creates an image for comparison
        this.card2 = new Phaser.GameObjects.Image(this, 0, 0, 'front');

        // creates container 1 and adds PerspectiveCard to it
        this.container1 = this.add.container(300, 100).add(this.card1);

        // creates container 2 and adds Image to it
        this.container2 = this.add.container(300, 450).add(this.card2);

        // creates interactive text
        this.add.text(50, 300, "Click here").setInteractive().on('pointerdown', this.move, this);
    }

    // should move both cards but only moves one
    move(this: Demo) {
        this.container1.x += 100;
        this.container2.x += 100;

        console.log("container1.x: " + this.container1.x);
        console.log("container2.x: " + this.container2.x);
    }
}
```

**Comment by wzurborg** [comment]
I tried the same code with `ContainerLite` replacing `Phaser.GameObjects.Container`, changing `add()` to `addLocal()` to add the content. The PerspectiveCard is rendered in the correct position and moves nicely together with the container, but the image is not rendered at all...

**Comment by rexrainbow** [comment]
Add a new method [`addToContainer`](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/containerlite/#add-to-container) of [ContainerLite](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/containerlite/), to add this containerLite (PerspectiveCard is extended from ContainerLite) and its children into builtin container.
See this [test code](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/perspective-card/add-to-container.js#L19)

**Comment by rexrainbow** [comment]
[Here](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/perspective-card/add-to-containerlite.js#L52-L54) is another test case, to add PerspectiveCard and a text game object into a ContainerLite, and move together.

**Comment by wzurborg** [comment]
Yes, it works with ContainerLite but not with standard Container.

**Comment by rexrainbow** [comment]
New method for adding card to built-in container post [here](https://github.com/rexrainbow/phaser3-rex-notes/issues/186#issuecomment-878765953). Sorry for this inconvenience.

The better solution is using containerLite.
