### ISSUE TITLE
ContainerLite.getChildren() should allow for an array argument

### ISSUE THREAD

**Issue by wzurborg** [rexrainbow/phaser3-rex-notes#187]
Assigning the result of the method `ContainerLite.getChildren()` to a variable only gives a 'live' reference to the children of the container that changes when the container changes. E.g., when the container is cleared, the variable is cleared as well. There is no method to retrieve the top-level children in a persistent way.

Other methods like `getAllChildren()` and `getAllVisibleChildren()` also allow for an array argument that can store the result and is unaffected by modifications of the container. `getChildren()` should also have such an argument.

Code example:
``` typescript
        // creates container and adds object to it
        this.container = new ContainerLite(this, 300, 200).addLocal(this.card);
        this.add.existing(this.container);

        // Saving reference to children
        const temp = this.container.getChildren();
        console.log("temp.length: " + temp.length); // 1

        this.container.clear();
        console.log("temp.length: " + temp.length); // 0
```

As a workaround, you can of course copy the children to an own array:
``` typescript
        let children = new Array<PerspectiveCard>();
        for (var i = 0, cnt = temp.length; i < cnt; i++) {
            const myChild = temp[i] as PerspectiveCard;
            children.push(myChild);
        }
        console.log("children.length: " + children.length)  // 1
```

**Comment by rexrainbow** [comment]
Add `out` parameter to `ContainerLite.getChildren(out)` method, to return copy of children array. Default `ContainerLite.getChildren()` will still return internal children array.
Npm package will be upgraded this week.

**Comment by wzurborg** [comment]
Thank you!
