### ISSUE TITLE
Error with scroll area

### ISSUE THREAD

**Issue by Maz-POTAT** [rexrainbow/phaser3-rex-notes#188]
![image](https://user-images.githubusercontent.com/84121020/126499614-05c00c20-e4ee-4d7d-881f-141177d004a9.png)
I used scroll area in one of my scene
and when i tried to stop that scene error occurs.
And i found it is cause of the scroll area.

**Comment by Maz-POTAT** [comment]
![image](https://user-images.githubusercontent.com/84121020/126499852-b5888206-28dc-4bbd-8540-2b31d20ca593.png)

**Comment by rexrainbow** [comment]
Thanks for finding it, bug fixed. Please download latest version of minify rexUI.
