### ISSUE TITLE
Can I use it without importing?

### ISSUE THREAD

**Issue by matrizet** [rexrainbow/phaser3-rex-notes#19]
Is there a way to directly call the virtual joystick plugin file?
Because I'm having issues, I can't import it.
I'm new to JavaScript so I don't want to install node.js or other just for making a game.

Using script src doesn't work, 
script type="module" 
doesn't work too, using the import statement results in error.

Thanks for listening

**Comment by rexrainbow** [comment]
Yes, you can use that virtual joystick plugin without using `import`. [Here](https://codepen.io/rexrainbow/pen/oyqvQY) is an example about how to install phaser plugin.
In preload stage, call
```javascript
var url = 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/plugins/dist/rexvirtualjoystickplugin.min.js';
this.load.plugin('rexvirtualjoystickplugin', url, true);
```
to download and install virtual joystick plugin from an external file, then create a new virtual joystick instance via
```javascript
var joyStick = this.plugins.get('rexvirtualjoystickplugin').add(this, config);
```

**Comment by matrizet** [comment]
> Yes, you can use that virtual joystick plugin without using `import`. [Here](https://codepen.io/rexrainbow/pen/oyqvQY) is an example about how to install phaser plugin.
> In preload stage, call
> 
> ```js
> var url = 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/plugins/dist/rexvirtualjoystickplugin.min.js';
> this.load.plugin('rexvirtualjoystickplugin', url, true);
> ```
> 
> to download and install virtual joystick plugin from an external file, then create a new virtual joystick instance via
> 
> ```js
> var joyStick = this.plugins.get('rexvirtualjoystickplugin').add(this, config);
> ```

Thank you so much, it works now.

Looks like I've still got a lot to learn

**Comment by matrizet** [comment]
> Yes, you can use that virtual joystick plugin without using `import`. [Here](https://codepen.io/rexrainbow/pen/oyqvQY) is an example about how to install phaser plugin.
> In preload stage, call
> 
> ```js
> var url = 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/plugins/dist/rexvirtualjoystickplugin.min.js';
> this.load.plugin('rexvirtualjoystickplugin', url, true);
> ```
> 
> to download and install virtual joystick plugin from an external file, then create a new virtual joystick instance via
> 
> ```js
> var joyStick = this.plugins.get('rexvirtualjoystickplugin').add(this, config);
> ```

I used the example and am getting this error
``Uncaught TypeError: Cannot read property 'add' of null

**Comment by matrizet** [comment]
> Yes, you can use that virtual joystick plugin without using `import`. [Here](https://codepen.io/rexrainbow/pen/oyqvQY) is an example about how to install phaser plugin.
> In preload stage, call
> 
> ```js
> var url = 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/plugins/dist/rexvirtualjoystickplugin.min.js';
> this.load.plugin('rexvirtualjoystickplugin', url, true);
> ```
> 
> to download and install virtual joystick plugin from an external file, then create a new virtual joystick instance via
> 
> ```js
> var joyStick = this.plugins.get('rexvirtualjoystickplugin').add(this, config);
> ```

Thanks it works now

**Comment by gskriptor** [comment]
Hi,
I am using this same plugin and method, but I am getting an error in my console:
Uncaught TypeError: n.onDown is not a function
```
class MyScene extends Phaser.Scene{
  preload() {
    this.load.plugin('rexvirtualjoystickplugin', 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/dist/rexvirtualjoystickplugin.min.js', true);
  }
  create() {
    this.joyStick = this.plugins.get('rexvirtualjoystickplugin').add(this, {
      x: this.game.config.width * 0.5,
      y: 680,
      radius: 60,
      base: this.add.circle(0, 0, 100, 0x888888),
      thumb: this.add.circle(0, 0, 50, 0xcccccc),
      // dir: '8dir',   // 'up&down'|0|'left&right'|1|'4dir'|2|'8dir'|3
      // forceMin: 16,
      // enable: true
    }).on('update', this.dumpJoyStickState, this);

    this.text = this.add.text(0, 0);
    this.dumpJoyStickState();
  }
  dumpJoyStickState() {
        var cursorKeys = this.joyStick.createCursorKeys();
        var s = 'Key down: ';
        for (var name in cursorKeys) {
            if (cursorKeys[name].isDown) {
                s += name + ' ';
            }
        }
        s += '\n';
        s += ('Force: ' + Math.floor(this.joyStick.force * 100) / 100 + '\n');
        s += ('Angle: ' + Math.floor(this.joyStick.angle * 100) / 100 + '\n');
        this.text.setText(s);
    }
}
```
Is there something I am missing?

**Comment by rexrainbow** [comment]
Please use latest phaser3.

**Comment by gskriptor** [comment]
> Please use latest phaser3.

Thank you this worked for me.
