### ISSUE TITLE
Mouse wheel on scroll

### ISSUE THREAD

**Issue by Takyo** [rexrainbow/phaser3-rex-notes#190]
How it should be done to make the mouse wheel work on scroll grid?

**Comment by rexrainbow** [comment]
New mouse-wheel-scrolling feature added.

See demos:
- [GridTable](https://codepen.io/rexrainbow/pen/XyJbWX) , line 52-55
- [ScrollablePanel](https://codepen.io/rexrainbow/pen/YMyBom) , line 74-77
- [TextArea](https://codepen.io/rexrainbow/pen/JzBZzy) , line 40-43

Default behavior is no mouse-wheel-scrolling.

Please download latest minify file of rexUI.

**Comment by shishX86** [comment]
I tried to use example as is and have an error.

`TS2345: Argument of type '{ x: number; y: number; width: number; height: number; background: RoundRectangle; text: BBCodeText; slider: { track: RoundRectangle; thumb: RoundRectangle; }; scroller: { ...; }; mouseWheelScroller: { ...; }; header: Label; footer: Label; }' is not assignable to parameter of type 'IConfig'.
  Object literal may only specify known properties, and 'mouseWheelScroller' does not exist in type 'IConfig'.`
  
  typescript
  npm 7.18.1
  node 16.4.1
  "phaser": "^3.55.2",
  "phaser3-rex-plugins": "^1.1.57"
  
I tried to compile as any type. In this case error has gone but mouse wheel not working. 
Is 1.1.57 version is latest?

Thanks!

**Comment by rexrainbow** [comment]
MouseWheelScroll feature is in NPM package 1.1.58, upgraded 2 hr before.

**Comment by shishX86** [comment]
Wow!
Extremely fast fix&answer!
It works!
Like! I mean star )

**Comment by rexrainbow** [comment]
Issue closed
