### ISSUE TITLE
define pages in Text Box

### ISSUE THREAD

**Issue by hyleore** [rexrainbow/phaser3-rex-notes#192]
Hello! I hope it's ok to ask here:

I created a text box, with text and an icon, with the RexUI Text Box plugin, and I'd like to know if there is a simple way for me to split my content into different 'pages' myself, so that it cuts at the end of sentences, where I choose, rather than in the middle of a sentence. I tried installing and using the Page plugin as well to do that, but it didn't work, and I'd like to know if that is necessary at all. Before that I also tried creating an array but all it did was split them into paragraphs (maybe that was stupid but I thought it was worth a try xD). I loaded the minify file for the plugin.

Thank you!

**Comment by rexrainbow** [comment]
rexTextPage, rexUI - TextBox: Add `pageBreak` parameter. String after page-break symbol will be placed to a new page. Default value is `'\f\n'`.
- [Demo](https://codepen.io/rexrainbow/pen/JjNZZXv) 

Please download minify file to get this new feature.

**Comment by hyleore** [comment]
This works perfectly!
Thank you so much for taking care of it so quickly.
