### ISSUE TITLE
RexBoardPlugin: Custom class constructor error 

### ISSUE THREAD

**Issue by meetpatel1989** [rexrainbow/phaser3-rex-notes#193]
Installed the board plugin through npm and loading the plugin in the game config file. I'm getting the board class when I print the class in the console but when I'm trying to define the class like in this [demo](https://codepen.io/rexrainbow/pen/qvJwjJ) it is not working.

```
import RexBoardPlugin from 'phaser3-rex-plugins/plugins/board-plugin.js';
plugins: {
        scene: [{
            key: 'rexBoard',
            plugin: RexBoardPlugin,
            mapping: 'rexBoard'
        },
            // ...
        ]
    }
```

```
//Added in create function of scene class
this.board = new Board(this, config);

//Outside scene class
class Board extends RexPlugins.Board.Board {
    constructor(scene, config) {
        // create board
        super(scene, config);
    }
}
```

The game failed to load with the following error
**Uncaught TypeError: Class constructor Board cannot be invoked without 'new'**

![image](https://user-images.githubusercontent.com/47215461/128670401-6200fbe8-8c96-4fd0-9551-89bcb88fb7eb.png)

The error points to the constructor line of the Board class.

**Comment by rexrainbow** [comment]
I did not add type define of `RexPlugins.Board.xxx`, (have no idea how to add type define of global variable)

Please try import Board class from ['phaser3-rex-plugins/plugins/board-components.js'](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/plugins/board-components.js). See [this test code](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/board-pathfinder/find-area-get-path-ts.ts#L2-L7)

**Comment by meetpatel1989** [comment]
Thanks for the quick reply but I'm still getting the same error after importing board class from components as you have mentioned.

![image](https://user-images.githubusercontent.com/47215461/128680160-59ac6fbe-0a9a-437c-bf4c-f1d58ee1d1f5.png)

Sorry for the inconvenience.

**Comment by rexrainbow** [comment]
Perhaps it is an issue of typescript config, see [this discussion thread](https://stackoverflow.com/questions/50203369/class-constructor-cannot-be-invoked-without-new-typescript-with-commonjs).

**Comment by meetpatel1989** [comment]
@rexrainbow Thanks for the hint. It worked. I really appreciate your help.
