### ISSUE TITLE
Moving Diagonally in Quad grid

### ISSUE THREAD

**Issue by meetpatel1989** [rexrainbow/phaser3-rex-notes#196]
I have a couple of questions that I couldn't able to find from the documentation.

1) How can I move a chess object diagonally in the quad grid? I tried to set pathMode to 'diagonal' but still, the object moves to destination using vertical & horizontal path only.
2) Is it possible to get all the possible paths if I know the destination cell?
3) Can I move the chess to the destination by giving my own path?

For reference, please check the following image.

![Screenshot 2021-08-13 114120](https://user-images.githubusercontent.com/47215461/129317701-4fffa605-cd62-4fcc-a05c-ee7b8cc2e1e1.png)

**Comment by rexrainbow** [comment]
1. [Set `dir`](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board-quadgrid/#create-instance), to `8`, to allow path finder checks Left-down/Down-right/Right-up/Up-left direction.
2. Paths information are stored internally, but only build/return 1 path, according to `pathMode`.
3. You can [move chess](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board-moveto/) to anywhere without running PathFinder before.

**Comment by meetpatel1989** [comment]
@rexrainbow Thanks for the details it helped a lot! One last howTo question in the list. The plugin returns the shortest path from getPath but what if I want to move to destination from another path? For example, consider the orange arrow from the image I shared. Is there any option in which I can tell to find the path which includes a particular cell/node?

One more thing is, I checked the [draw path](https://codepen.io/rexrainbow/pen/JjjwPgE) demo. I noticed that path gets changed when I select the next block even if the cost of moving to a destination block is the same that is 4 blocks.

![Screenshot 2021-08-15 234620](https://user-images.githubusercontent.com/47215461/129488504-bbe577e3-9351-454d-be9a-866be7c0a3cc.png)

Please check the drawn path in the above image.

![Screenshot 2021-08-15 234645](https://user-images.githubusercontent.com/47215461/129488535-1da5dc6d-a287-4634-bba2-9251ce453433.png)

The new path should follow the 1st image path and should add the new block at the end but instead of that it creates a whole new path and changed the 3rd number block. I just wanted to know how the logic works here. Both paths have the same number of blocks to move then why does it gets changed? Is there a way I can stop this behavior?

**Comment by rexrainbow** [comment]
>  Is there any option in which I can tell to find the path which includes a particular cell/node?

No option for this use-case. You can divide path into multiple segments, find path along these segments.

> The new path should follow the 1st image path and should add the new block at the end but instead of that it creates a whole new path and changed the 3rd number block. I just wanted to know how the logic works here. Both paths have the same number of blocks to move then why does it gets changed? Is there a way I can stop this behavior?

In this demo, pathMode is set to `'A*'`, which is a faster way to find a path, but the result path might not be *shortest*, because that [A*](https://en.wikipedia.org/wiki/A*_search_algorithm)  mode did not search all possible paths. You might try to set pathMode to `'straight'', to get shortest path. BTW, the result path is reversed from end tile to start tile.

**Comment by meetpatel1989** [comment]
@rexrainbow Thanks for the help :). Can I use texture instead of shape for chess objects?

**Comment by rexrainbow** [comment]
Yes you can, use [addChess](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board/#add-chess) to add any kind of chess game object.
```javascript
board.addChess(chess, tileX, tileY, tileZ, align)
```
See [this test](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/board-texture/create-tile-texture.js#L25-L28)

**Comment by meetpatel1989** [comment]
Is it possible to find the path from A to B and B to C without moving the game object? Path finder's findPath or getPath takes only endtile as a parameter and assumes the game object is on the start tile. I want to know the path without moving the game object.

Thank you so much for your help. :)

**Comment by rexrainbow** [comment]
Try [`moveChess` method](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board/#move-chess), set chess to tileB, then find path from tileB to tileC. Finally, move chess to tileA back, using MoveTo behavior to move chess along path.

**Comment by meetpatel1989** [comment]
Yes but for that, I have to move the chess to tileB. I want to show the new alternate path without moving the chess to tileB. The chess will move from A to B and B to C when the button is clicked.

Hope this will help to understand my point.

**Comment by rexrainbow** [comment]
PathFinder supports `occupiedTest` and `blockerTest`, which means that user has to put a chess at a (tileX, tileY, tileZ) first.
To keep the character chess during path-finding stage, you might try to use another ghost chess, only used for path-finding.
BTW, set parameter `align` to `false` in [moveChess method](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board/#move-chess), can only move chess in board's logic position, without change position in game world.

**Comment by meetpatel1989** [comment]
It worked! Thank you for the help.
