### ISSUE TITLE
有时候使用抖动这个插件的会造成最终position改变

### ISSUE THREAD

**Issue by mayujuan981017** [rexrainbow/phaser3-rex-notes#198]
<img width="82" alt="截屏2021-08-21 下午9 26 39" src="https://user-images.githubusercontent.com/37371539/130323261-3a9dfd84-04fa-4c8c-8310-414ce6a1dd0d.png">
图片上数字应该和正方形图片一起抖动，使用抖动这个插件有时候会出现正方形图片脱离数字

**Comment by rexrainbow** [comment]
Bug fixed, please get latest version of minify file. [Test](https://codepen.io/rexrainbow/pen/JwMbxR)

**Comment by mayujuan981017** [comment]
采用更新后的版本仍然存在上述bug
小球在撞击障碍物的时候，障碍物仍然会有和数字脱离的情况，视频可见如下链接～

链接：https://pan.baidu.com/s/1YIyFP4LIfV39eEiY5sJQUg 
提取码：rL2e --来自百度网盘超级会员V3的分享

**Comment by rexrainbow** [comment]
Updated another version of minify file, which will set position back more earlier, under 'prestep' event.

**Comment by mayujuan981017** [comment]
Thanks！I will try it

**Comment by mayujuan981017** [comment]
您好～可以把修改的东西发一个npm包嘛

**Comment by rexrainbow** [comment]
Won't upgrade npm package this week. Maybe next or next two weeks later.

**Comment by mayujuan981017** [comment]
Thanks~

**Comment by mayujuan981017** [comment]
您好～我引入[](https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/dist/rexshakepositionplugin.min.js)这个文件还是会偶发方块和数字脱离的问题，碰撞会对抖动有影响嘛

**Comment by rexrainbow** [comment]
Shake behavior has [2 modes](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/shake-position/#create-instance), uses `'effect'` mode to set position back in game's 'prestep' event.

Static body won't be push out when arcade collided, general speaking.

Please provide a simplest runnable test code if this issue still occurs.
