### ISSUE TITLE
TestFont.js?47d2:2 Uncaught ReferenceError: Phaser is not defined

### ISSUE THREAD

**Issue by jdd4494** [rexrainbow/phaser3-rex-notes#201]
When trying to build getting the following error. Adding `import Phaser from 'phaser'` appears to fix this error.

**Comment by rexrainbow** [comment]
I did not have **TestFont.js** file. Could you provide the correct test file name?

**Comment by jdd4494** [comment]
The file is found in: phaser3-rex-plugins/plugins/loader/webfontloader/TestFont.js

**Comment by jdd4494** [comment]
It's an odd issue because I previously saw this issue on windows (but have been able to run fine without that import statement). However, another developer is running into the same issue and has been unable to get rid of that compile error without adding that import statement.

**Comment by rexrainbow** [comment]
Plugin will be loaded and executed after `import phaser` in application side, thus it won't be added into plugin.

**Comment by jdd4494** [comment]
Accidentally loaded in plugin before importing phaser. Feel free to close this issue.
