### ISSUE TITLE
Sizer vertical spacing doesn't work?

### ISSUE THREAD

**Issue by crapthings** [rexrainbow/phaser3-rex-notes#212]
```js
this.leftNav = this.rexUI.add.sizer(0, 0, 0, 0, 'y')
      .setOrigin(0)
      .setInnerPadding(32)
      .addSpace()
      .add(this.add.text(0, 0, '金币 10000'))
      .add(this.add.text(0, 0, '矿石 10000'))
      .add(this.add.text(0, 0, '水晶 10000'))
      .addSpace()
      .layout()
```

![image](https://user-images.githubusercontent.com/1147704/146742195-3e53d8cc-e3ab-4a32-8ed3-b9ba777a2134.png)

i think spacer should work like css: flex-auto

is this by design?

![image](https://user-images.githubusercontent.com/1147704/146742377-cae1e7e3-507e-49ec-9e03-728a9d656c76.png)

**Comment by crapthings** [comment]
okay cool i just forget to add height to sizer

**Comment by rexrainbow** [comment]
If you has several panels pin around boundary of viewport, you might try to [add them](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-overlapsizer/#add-child) into [overlapSizer](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-overlapsizer/).
Here is a [demo](https://codepen.io/rexrainbow/pen/WNpoMzx).

**Comment by crapthings** [comment]
what is the difference between sizer and overlapSizer?

**Comment by crapthings** [comment]
I don't know if this is the right approach, but it works.

what is the best practice for such job

```js
    const viewport = this.rexUI.viewport

    this.rexUI.add.overlapSizer()
      .setPosition(viewport.centerX, viewport.centerY)
      .setMinSize(viewport.width, viewport.height)
      .add((
        this.rexUI.add.sizer(0, 0, 0, this.game.config.height, 'y', { space: { item: 32 * 2 } })
          .setOrigin(0)
          .setInnerPadding(32)
          .addSpace()
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .addSpace()
      ), 'right', 'right', 0,  false)
      .layout()
```

![image](https://user-images.githubusercontent.com/1147704/146752469-786d385f-1c80-403b-8f8b-ec4ac2c23e4d.png)

**Comment by crapthings** [comment]
after trying play overlapSizer, this is something come up with.

```js
this.rexUI.add.overlapSizer(0, 0, this.rexUI.viewport.width, this.rexUI.viewport.height)
      .setOrigin(0)
      .add((
        this.rexUI.add.sizer(0, 0, 0, 0, 'y', { space: { item: 32 * 2 } })
          .setOrigin(0)
          .setInnerPadding(32)
          .addSpace()
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .addSpace()
      ), 'right', 'right', 0,  false)
      .add((
        this.rexUI.add.sizer(0, 0, 0, 0, 'y', { space: { item: 32 * 2 } })
          .setOrigin(0)
          .setInnerPadding(32)
          .addSpace()
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .add(this.add.text(0, 0, '场景图标'))
          .addSpace()
      ), 'left', 'left', 0,  false)
      .add((
        this.rexUI.add.sizer(0, 0, 0, 0, 'x', { space: { item: 32 } })
          // .setOrigin(0)
          .setInnerPadding(32)
          .add(this.add.text(0, 0, '铜币 10000'))
          .add(this.add.text(0, 0, '银币 10000'))
          .add(this.add.text(0, 0, '金币 10000'))
      ), 'top', 'right-top', 0,  false)
      .add((
        this.rexUI.add.sizer(0, 0, 0, 0, 'x', { space: { item: 32 * 2 } })
          // .setOrigin(0)
          .setInnerPadding(32)
          .add(this.add.text(0, 0, '图标'))
          .add(this.add.text(0, 0, '图标'))
          .add(this.add.text(0, 0, '图标'))
          .add(this.add.text(0, 0, '图标'))
          .add(this.add.text(0, 0, '图标'))
      ), 'bottom', 'bottom', 0,  false)
      .layout()
```

![image](https://user-images.githubusercontent.com/1147704/146755472-b8275e3e-e326-42e3-a21a-4bea2cfc34b6.png)

how to position bottom nav icons evenly

![image](https://user-images.githubusercontent.com/1147704/146755931-bd2f6fa0-7158-45a1-9e85-cb7976a15951.png)

and multiple columns on side, but icon might not  with the same rowcount

![image](https://user-images.githubusercontent.com/1147704/146756177-7326bf83-6353-4b5f-a554-5afaad727dc2.png)

**Comment by rexrainbow** [comment]
To build multiple columns, uses

- Sizer with horizontal orientation which contains
    - Sizer with vertical orientation , which contains 
        - Image, or Label
        - ...
    - Sizer with vertical orientation , which contains 
        - Image, or Label
        - ...

(BTW, to create buttons in a row/columns, might use [Buttons](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-buttons/), which is equal to horizontal/vertical Sizer with interactive children.)

Then put this (nested) horizontal size into overlapSizer.

**Comment by rexrainbow** [comment]
I don't get the previous issue *how to position bottom nav icons evenly*. 
Space between items is set by  user.

**Comment by rexrainbow** [comment]
> what is the difference between sizer and overlapSizer?
> 
> should I nest sizer inside an overlapSizer for multiple icons?
> 
> overlapSizer > sizer ?

To put children at center, sizer has to add 2 Spaces at first and last child. 
Within OverlapSizer, sizer does not have to add these Spaces. Set `align` parameter and set `origin` value of child sizer to put it at center of bound.
