### ISSUE TITLE
Touching joystick and button at the same time.

### ISSUE THREAD

**Issue by JayCasee** [rexrainbow/phaser3-rex-notes#213]
First of all, thank you so much for your great plugins...!

I'm trying to use 'rexvirtualjoystickplugin', 'rexbuttonplugin' at the same time on one scene.

But, it is not possible to click the button when the joystick is being used.

Is this a normal behavior, and is there any way to make both joystick and button to be touch-able at the same time...?

What if there is an example which can shows how to do this, I think it will be really great. : )

Thank you for reading my post.

**Comment by rexrainbow** [comment]
Try to enable [multiple touch](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/touchevents/#multi-touch)

**Comment by JayCasee** [comment]
Oh, thank you, it has been solved...!
