### ISSUE TITLE
Can I detect both of click down and up on one button...?

### ISSUE THREAD

**Issue by JayCasee** [rexrainbow/phaser3-rex-notes#214]
I always appreciate for your great library, and I have a more question.

In the UI Buttons, the button has a custom event as 'button.click'.

But it has a configuration as 'click' which only choose one of 'pointerdown' and 'pointerup'.

I want to make a button...
- at 'pointerdown', to keep touching as stacking power on a bullet,
- to 'pointerup', to shoot the bullet.

Is there any wat to detect both of click down and up on one button...?

Thank you for your reading.

**Comment by JayCasee** [comment]
Just FYI, I can use this to detect 'pointerup' to mix with the button's action. : )

```
scene.input.on('pointerdown', function(pointer){
    // ...
 });
```

BTW, I'm asking whether there is any better way to make the codes to be simpler.

**Comment by rexrainbow** [comment]
That's an application specific feature, not a normal ui behavior, imo. Thus I won't add it into Buttons.
On the other hand, there has [press behavior](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-overview/#touch-input) in rexui package
```javascript
var press = scene.rexUI.add.press(gameObject, config)
    .on('pressstart', function(press, gameObject, lastPointer){
})
    .on('pressend', function(press, gameObject, lastPointer){
})
```

**Comment by JayCasee** [comment]
Thank you so much for your quick response, I've noted well...! : )
