### ISSUE TITLE
Angular shows compilation error with NPM installed version (1.1.64)

### ISSUE THREAD

**Issue by richso** [rexrainbow/phaser3-rex-notes#215]
I have installed the phaser3-rex-plugins library into my Phaser3 project using the command: 
npm i phaser3-rex-plugins

however when running my program, the compiler complaints:
Error: node_modules/phaser3-rex-plugins/plugins/behaviors/containerperspective/ContainerPerspective.d.ts:1:27 - error TS2307: Cannot find module '../../gameobjects/perspective/rendertexture/RenderTexture' or its corresponding type declarations.
[ng] 1 import RenderTexture from "../../gameobjects/perspective/rendertexture/RenderTexture";
[ng]                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/phaser3-rex-plugins/plugins/gameobjects/mesh/perspective/utils/FaceContainer.d.ts:1:23 - error TS2307: Cannot find module '../../containerlite/ContainerLite' or its corresponding type declarations.
[ng] 1 import Container from '../../containerlite/ContainerLite';
[ng]                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: node_modules/phaser3-rex-plugins/templates/ui/utils/setchildreninteractive/SetChildrenInteractive.d.ts:2:10 - error TS2614: Module '"../../../../plugins/button"' has no exported member 'IConfig'. Did you mean to use 'import IConfig from "../../../../plugins/button"' instead?
[ng] 2 import { IConfig as IConfigClick } from '../../../../plugins/button';
[ng]            ~~~~~~~
[ng] Error: node_modules/phaser3-rex-plugins/templates/ui/utils/setchildreninteractive/SetChildrenInteractive.d.ts:3:10 - error TS2614: Module '"../../../../plugins/input/gestures/tap/Tap"' has no exported member 'IConfig'. Did you mean to use 'import IConfig from "../../../../plugins/input/gestures/tap/Tap"' instead?
[ng] 3 import { IConfig as IConfigTap } from '../../../../plugins/input/gestures/tap/Tap';
[ng]            ~~~~~~~
[ng] Error: node_modules/phaser3-rex-plugins/templates/ui/utils/setchildreninteractive/SetChildrenInteractive.d.ts:4:10 - error TS2614: Module '"../../../../plugins/input/gestures/press/Press"' has no exported member 'IConfig'. Did you mean to use 'import IConfig from "../../../../plugins/input/gestures/press/Press"' instead?
[ng] 4 import { IConfig as IConfigPress } from '../../../../plugins/input/gestures/press/Press';
[ng]            ~~~~~~~
[ng] Error: node_modules/phaser3-rex-plugins/templates/ui/utils/setchildreninteractive/SetChildrenInteractive.d.ts:5:10 - error TS2614: Module '"../../../../plugins/input/gestures/swipe/Swipe"' has no exported member 'IConfig'. Did you mean to use 'import IConfig from "../../../../plugins/input/gestures/swipe/Swipe"' instead?
[ng] 5 import { IConfig as IConfigSwipe } from '../../../../plugins/input/gestures/swipe/Swipe';

**Comment by rexrainbow** [comment]
These errors are from d.ts files, has been fixed yesterday. NPM package will be updated these weekend.

**Comment by rexrainbow** [comment]
NPM package upgraded to 1.1.65
