### ISSUE TITLE
let panel = scene.rexUI.add.scrollablePanel(config) Angular Typescript compilation error 

### ISSUE THREAD

**Issue by richso** [rexrainbow/phaser3-rex-notes#222]
I followed the instruction on this page: https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-scrollablepanel/

`
import Phaser from 'phaser';
import UIPlugin from 'phaser3-rex-plugins/templates/ui/ui-plugin.js';

class GameScene extends Phaser.Scene {
    preload() { ...}

    create() {
         let config = {...}
         let panel = this.rexUI.add.scrollablePanel(config);
    }
}

let game = new Phaser.Game({
    type: Phaser.AUTO,
                            scale: {
                                mode: Phaser.Scale.FIT,
                                parent: 'currency-p1-prepare-scene',
                                autoCenter: Phaser.Scale.CENTER_BOTH,
                                width: 800,
                                height: 600
                            },
                            input :{
                                activePointers:3
                            },
                            audio: {
                                disableWebAudio: true
                            },
                            plugins: {
                                scene: [{
                                    key: 'rexUI',
                                    plugin: UIPlugin,
                                    mapping: 'rexUI'
                                }]
                            },
                            scene: [ GameScene]
});
`

The Angular TS compiler complaints:
[ng] Error: src/app/page/games/currency-p1/currency-p1-prepare-scene.ts:357:26 - error TS2339: Property 'rexUI' does not exist on type 'GameScene'.
[ng] 357         let panel = this.rexUI.add.scrollablePanel({

Then I use another method on that page:

`
import { ScrollablePanel } from 'phaser3-rex-plugins/templates/ui/ui-components.js';
import Phaser from 'phaser';

class GameScene extends Phaser.Scene {
    preload() { ...}

    create() {
         let config = {...}
         var panel = new ScrollablePanel(this, config);
         this.add.existing(panel);
    }
}
`

The Angular TS compiler complaints another things:

[ng] Error: src/app/page/games/currency-p1/currency-p1-prepare-scene.ts:390:17 - error TS2322: Type '{ threshold: number; slidingDeceleration: number; backDeceleration: number; pointerOutRelease: true; }' is not assignable to type 'boolean | { threshold?: number; slidingDeceleration?: number | false; backDeceleration?: number | false; }'.
[ng]   Object literal may only specify known properties, and 'pointerOutRelease' does not exist in type '{ threshold?: number; slidingDeceleration?: number | false; backDeceleration?: number | false; }'.
[ng] 390                 pointerOutRelease: true,
[ng]                     ~~~~~~~~~~~~~~~~~~~~~~~
[ng]   node_modules/phaser3-rex-plugins/templates/ui/utils/scrollable/Scrollable.d.ts:36:9
[ng]     36         scroller?: (
[ng]                ~~~~~~~~
[ng]     The expected type comes from property 'scroller' which is declared here on type 'IConfig'

How to solve?

Thanks in advance.

**Comment by rexrainbow** [comment]
[Here](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/ui-d-ts/panel.ts) is the ts file of using scrollable panel. Works fine after fixed some d.ts bug in latest commit.

Could you post the config of constructor?

**Comment by richso** [comment]
Thanks for your prompt reply and fix. Previously, I just copy from your example on the ref page, and currently I just applied your changes in the .d.ts files and copied your given new demo config (uncommented the height to work otherwise will report height error); however although the panel shows up, the slider and its thumb did not and also the panel background color became transparent:
`{
            x: 400,
            y: 300,
            width: 400,
            height: 220,

            scrollMode: 1,

            background: this.rexUI.add.roundRectangle(0, 0, 2, 2, 10, COLOR_PRIMARY),

            panel: {
                child: createPanel(this, data),

                mask: {
                    padding: 1
                },
            },

            slider: {
                track: this.rexUI.add.roundRectangle(0, 0, 20, 10, 10, COLOR_DARK),
                thumb: this.rexUI.add.roundRectangle(0, 0, 0, 0, 13, COLOR_LIGHT),
            },

            mouseWheelScroller: {
                focus: false,
                speed: 0.1
            },

            space: {
                left: 10,
                right: 10,
                top: 10,
                bottom: 10,

                panel: 10,
            }
 }`

**Comment by richso** [comment]
Just found that the previous problem of not showing the scroller is because of Phaser 3 version, my previous version is 3.52; changing to 3.55.2 fixed the problem, however the "height" cannot be set. Why can't set the height?

**Comment by rexrainbow** [comment]
The `height` parameter here is the `minimal height`. 
Layout result is the max ( children width/height, minimal width/height). Leave `height` parameter to `undefined` will use children height.
You can set it to larger value like `300`, to see the result.
