### ISSUE TITLE
Continuous Shaking Object

### ISSUE THREAD

**Issue by john-trovalto** [rexrainbow/phaser3-rex-notes#223]
Hi @rexrainbow ,

Is there any option to set the continuous shaking on the gameobject in the Shake Position plugin?

Here is a code which I'm using to shake the graphics object.

`this.plugins.get('rexShakePosition').add(this.graphics, {
            mode: 1,
            duration: 1000,
            magnitude: 5,
            magnitudeMode: 0,
        });`
         
Please let me know if I'm missing anything.

**Comment by rexrainbow** [comment]
Set `duration` to a large value like `999999999999`.

**Comment by john-trovalto** [comment]
Understood. Thank you :)
