### ISSUE TITLE
弱弱的问一句 怎么样才可以 让dom层到所有游戏对象的底层呢~~

### ISSUE THREAD

**Issue by woshisheji** [rexrainbow/phaser3-rex-notes#228]
请问大佬们，怎么样才可以 让dom层到所有游戏对象的底层呢~~

**Comment by woshisheji** [comment]
额，可能大佬没有理解到我意思，我的意思是，当前 游戏的dom，是在所有游戏对象之上渲染的，不知道怎么才可以实现dom层在所有游戏对象的最下层，因为我想在dom层上面画一个半透明的矩形，来作为操作区域~

**Comment by woshisheji** [comment]
例如：
dom                                 text
text   ------想出现的是     text
text                                   dom

这样的层次。。因为看文档是可以将dom层放到最顶或者最底，但如何最底层，似乎没看到说明(*￣︶￣)

**Comment by rexrainbow** [comment]
All game objects are draw on a rendering canvas, exclude dom game objeects. Dom game objects will be put above rendering canvas.
To put dom behind rendering canvas, you might manipulate [depth/zindex](https://www.w3schools.com/jsref/prop_style_zindex.asp) of target dom.

**Comment by woshisheji** [comment]
原来如此，只能dom与canvas排序啊。我还以为是 dom与游戏对象可以进行最顶或最底的排序， 那只能把canvas背景透明了。。 谢谢大佬的指点
