### ISSUE TITLE
Wrong text position on ui-scrollablepanel or ui-textarea inside phaser container

### ISSUE THREAD

**Issue by raimon-segura** [rexrainbow/phaser3-rex-notes#231]
Hi!,

If I add a ui-scrollablepanel(or ui-textarea) into a phaser container with other position than {x:0, y:0} , the text has a wrong position. Any tip or fix... or its a plugin bug?

Here is the example demo with the bug
https://codepen.io/raimon-segura/pen/yLzWMzO

Many thanks!

**Comment by rexrainbow** [comment]
Replace 

```javascript
mainGroup.add(scrollablePanel.getElement('background'));
mainGroup.add(scrollablePanel.getElement('slider.track'));
mainGroup.add(scrollablePanel.getElement('slider.thumb'));
mainGroup.add(scrollablePanel.getElement('panel'));
```
by
```javascript
scrollablePanel.addToContainer(mainGroup);
```
to put ui element into built-in container.

But, **mask can't work in built-in container**. (ScrollablePanel, TextArea, GridTable have mask)

**Comment by raimon-segura** [comment]
Hi RexRainbow!

Thanks for you quick reply!.. althought I still have one small problem with text

I've modified the example to be more similar with my code
https://codepen.io/raimon-segura/pen/yLzWMzO

I use only one text object to put all text with wordWrap option, it has a similar issues than previous one if I add to mainGroup container.. without the container all works as expected... any clue?
`
var textObj = scene.add.text(0,0, content, {
      fontSize: 18,
      wordWrap: { width: 250  }
    })
sizer.add(textObj);
mainGroup.add(textObj)
`

By the way, I always need to add textObj to mainGroup container, now and in the previous example

Thanks!

**Comment by rexrainbow** [comment]
The issue is from mask. Set `mask: { padding: 1 }` to `mask: false`, to disable mask behavior, then text game object will show at correct position. But without mask, this scrollable panel  is broken.

As I said before, mask can't work well if put mask source game object and mask target game object into built-in container.
[Here](https://codepen.io/rexrainbow/pen/mdBZJmb) is a demo, enable line 22-24 to show result of  putting them into built-in container.

**Comment by raimon-segura** [comment]
seems that it works for textarea => https://codepen.io/raimon-segura/pen/gOGJEdo

Thanks!

**Comment by rexrainbow** [comment]
It is because that, game objects at header/footer are put above game object at textarea, thus mask can be disabled.
