### ISSUE TITLE
Text word wrap differs from Phaser3 syntax

### ISSUE THREAD

**Issue by bmpickford** [rexrainbow/phaser3-rex-notes#232]
I've been using the BBCodeText plugin for a bit and it works great! Only thing is that the syntax for setting word wrap width differs from the base Text object in Phaser 3. Would be good if these could be the same? Or is there a reason they differ?

**Text in Phaser 3**: `text.setWordWrapWidth()`
**Text using BBCodeText plugin**: `text.setWrapWidth()`

**Phaser docs**: https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Text.html#setWordWrapWidth
**BBCodeText plugin docs**: https://rexrainbow.github.io/phaser3-rex-notes/docs/site/bbcodetext/#wrap

Happy to raise a PR or contribute where I can

**Comment by rexrainbow** [comment]
Because that BBCodeText/TagText have word and character wrap modes. thus I use `setWrapWidth` instead of `setWordWrapWidth`.
I had added `setWordWrapWidth(width)` into BBCodeText, TagText. Please get latest version of plugin.
