### ISSUE TITLE
大佬 有给phaser3使用的 canvasinput 这个插件吗

### ISSUE THREAD

**Issue by woshisheji** [rexrainbow/phaser3-rex-notes#233]
大佬 有给phaser3使用的 canvasinput 这个插件吗

只搜到了phaser2的版本诶。这样就可以脱离dom了，不然 dom无法排序，输入框会在最上面很难看。。

**Comment by rexrainbow** [comment]
I don't have that plugin. Another similar plugin is [Text edit](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/textedit/), which shows the origin text game object in normal case, and creating a input-text DOM when editing.

- [Demo](https://codepen.io/rexrainbow/pen/GaxqLZ),
- [Work with rexui](https://codepen.io/rexrainbow/pen/YbvwBw)

**Comment by woshisheji** [comment]
谢谢大佬，我也考虑过这样的用法，用文本标签，点击时候弹出创建的dom input 。。 看来只能如此了。 canvasinput.js 还是不错的。不过似乎停更了。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月29日(星期六) 凌晨2:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rexrainbow/phaser3-rex-notes] 大佬 有给phaser3使用的 canvasinput 这个插件吗 (Issue #233)





 
I don't have that plugin. Another similar plugin is Text edit, which shows the origin text game object in normal case, and creating a input-text DOM when editing.
  
Demo,
 
Work with rexui
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rexrainbow** [comment]
Running [Example of CanvasInput](https://goldfirestudios.com/canvasinput-html5-canvas-text-input) on mobile device (ipad) seems not work well. 
- The focus will run away.
- Can't select text

I guess that the hidden input-text dom is not at correct position. And it can't receive touch event directly.

[TextEdit](https://codepen.io/rexrainbow/pen/YbvwBw) works better on mobile device.

**Comment by woshisheji** [comment]
非常感谢大佬，在大过年的还关注了这个帖子。
我年后试试TextEdit 大概是因为 CanvasInput 太久太久没有更新吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月3日(星期四) 中午12:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rexrainbow/phaser3-rex-notes] 大佬 有给phaser3使用的 canvasinput 这个插件吗 (Issue #233)





 
Running Example of CanvasInput on mobile device (ipad) seems not work well.
  
The focus will run away.
 
Can't select text
  
I guess that the hidden input-text dom is not at correct position. And it can't receive touch event directly.
 
TextEdit works better on mobile device.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rexrainbow** [comment]
I am working on a *hiddenInputText* plugin inspired from CanvasInput, it updates rendering result of a text/bbcodetext when value of HiddenInputText is changed. [Here](https://codepen.io/rexrainbow/pen/WNXxEMV) is a demo.
It won't have selecting text feature BTW.

**Comment by woshisheji** [comment]
一般情况下应该极少需要选择文本功能吧，不过按照其他经验，我一般是选择文本后，会切换到input组件上，然后input的背景完全透明，支持选择，不过，如果说要支持bbcode，那选择可能极为麻烦了


不过，不能排除需要选择的情况，例如 复制别人发布的公告之类的信息





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月3日(星期四) 下午4:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rexrainbow/phaser3-rex-notes] 大佬 有给phaser3使用的 canvasinput 这个插件吗 (Issue #233)






我正在研究隐藏输入文本受 Canvas Input 启发的插件,当隐藏输入文本的值发生更改时,它会更新文本/ bb code text 的渲染结果。在这里是小样
顺便说一句，它不会有选择文字功能。

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监察办或机器人. 
***@***.***与&gt;

**Comment by woshisheji** [comment]
测试了一下，似乎demo有点小，不过的确似乎好很多，没有那种切换文本到标签的差异，rexui里原版那个似乎鼠标离开后会出现一点坐标上下变化，这个似乎没有。


我是原先使用 construct2 下载过你很多插件，然后，觉得这款软件限制实在太多，开发其他游戏很不方便，然后又搜索你的ID，找到了phaser，感觉这个非常合适。嘿嘿。


先膜拜下大佬。。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rexrainbow/phaser3-rex-notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月3日(星期四) 下午4:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rexrainbow/phaser3-rex-notes] 大佬 有给phaser3使用的 canvasinput 这个插件吗 (Issue #233)





 
I am working on a hiddenInputText plugin inspired from CanvasInput, it updates rendering result of a text/bbcodetext when value of HiddenInputText is changed. Here is a demo.
 It won't have selecting text feature BTW.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rexrainbow** [comment]
Here are two text edit plugins in rexui :

- [Replace text by an input text](https://codepen.io/rexrainbow/pen/YbvwBw)
- [Using a hidden text input](https://codepen.io/rexrainbow/pen/MWOjJzZ)

**Comment by woshisheji** [comment]
非常感谢大佬，我研究一下。最近有些忙，在弄cef的浏览器。想直接能够在项目渲染




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月4日(星期五) 晚上7:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rexrainbow/phaser3-rex-notes] 大佬 有给phaser3使用的 canvasinput 这个插件吗 (Issue #233)





 
Here are two text edit plugins in rexui :
  
Replace text by an input text
 
Using a hidden text input
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by woshisheji** [comment]
大佬，我发现你这些插件都没有办法进行深度排序吗。。 有点难受呀，设置对象深度排序似乎无效




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rexrainbow/phaser3-rex-notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月4日(星期五) 晚上7:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rexrainbow/phaser3-rex-notes] 大佬 有给phaser3使用的 canvasinput 这个插件吗 (Issue #233)





 
Here are two text edit plugins in rexui :
  
Replace text by an input text
 
Using a hidden text input
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rexrainbow** [comment]
*Hidden input text* plugin uses built-in text game object to display text, built-in text game object has `setDepth` method.

**Comment by woshisheji** [comment]
额。我不是仅仅说这个 输入文字的问题，似乎所有的这里面的插件，都没法深度排序，我创建了一个动画对象，似乎这个个UI插件都是在同一层




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月16日(星期三) 中午12:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rexrainbow/phaser3-rex-notes] 大佬 有给phaser3使用的 canvasinput 这个插件吗 (Issue #233)






隐藏输入文字插件使用内置文字游戏对象显示文字，内置文字的游戏对象有塞德普方法。

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
随时随地使用 GitHub Mobile 进行分流通知,以便监察办或机器人. 
***@***.***与&gt;

**Comment by rexrainbow** [comment]
All game objects of rexui, are put at scene's list, so they are at the same *layer* indeed. You can use `setDepth` or change display order via [these method](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/structs-list/#order-of-child)

```js
scene.children.bringToTop(child);
scene.children.sendToBack(child);
scene.children.moveUp(child);
scene.children.moveDown(child);
scene.children.moveUp(child);
scene.children.moveTo(child, index);
scene.children.moveAbove(child1, child2); // Move child1 above child2
scene.children.moveBelow(child1, child2); // Move child1 below child2
scene.children.swap(child1, child2);
```

Or put some ui elements on layer game object. see this [demo](https://codepen.io/rexrainbow/pen/oNZKmKZ).

**Comment by woshisheji** [comment]
感谢大佬， 我用纯粹的容器 和 绘制也画了一些组件。。。&nbsp; 其中想画圆角矩形，然后使用您的那个九宫图来拉伸这些圆角矩形，发现并不能，只能使用图片key来填充参数，有可以直接九宫设置游戏对象的吗







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月16日(星期三) 中午12:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rexrainbow/phaser3-rex-notes] 大佬 有给phaser3使用的 canvasinput 这个插件吗 (Issue #233)






re xu i 的所有游戏对象，都放在场景列表中，所以它们在同一个地方层的确，你可以用设置深度或更改显示顺序这些方法
场景.孩子们.Bring To Top(儿童);场景.孩子们.发送 To back(儿童);场景.孩子们.动作(儿童);场景.孩子们.Move Down(儿童);场景.孩子们.动作(儿童);场景.孩子们.Move To(儿童,指数);场景.孩子们.上移(儿童 1,儿童 2);//在 child 2 上移动 child 1场景.孩子们.下移(儿童 1,儿童 2);//将 child 1 移动到 child 2 下面场景.孩子们.交换(儿童 1,儿童 2);

或者在层 game object 上放一些 ui 元素，看到这个演示.

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
使用 GitHub Mobile 随时随地发送分流通知IOS 系统或机器人. 
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;

**Comment by woshisheji** [comment]
额，大佬理解错了我的意思，我是想把 圆角矩形插件，使用你的九宫插件，进行拉伸。但是发现并不能。。。 九宫插件只能拉伸 key 资源图片




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月18日(星期五) 晚上10:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rexrainbow/phaser3-rex-notes] 大佬 有给phaser3使用的 canvasinput 这个插件吗 (Issue #233)





 
Round rectangle plugin, demo.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rexrainbow** [comment]
Frame in ninepatch must at the same texture, it can't render frame across different textures.

**Comment by woshisheji** [comment]
这个我知道。我是想知道&nbsp; 圆角矩形 这个 画出来的对象，可以使用九宫拉伸吗， 九宫设置的对象应该允许 圆角矩形，图片对象之类的。但似乎只能设置 key&nbsp; 帧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月18日(星期五) 晚上10:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rexrainbow/phaser3-rex-notes] 大佬 有给phaser3使用的 canvasinput 这个插件吗 (Issue #233)






nine patch 中的帧必须在相同的纹理上，不能跨不同的纹理渲染帧。

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
使用 GitHub Mobile 随时随地发送分流通知IOS 系统或机器人. 
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;

**Comment by woshisheji** [comment]
哦，原来如此，非常感谢。 我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月18日(星期五) 晚上10:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rexrainbow/phaser3-rex-notes] 大佬 有给phaser3使用的 canvasinput 这个插件吗 (Issue #233)






制图法和帆布两者都可以生成纹理。
这圆角矩形将绘制在画布上，从而渲染结果可以导出到纹理管理器。

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
使用 GitHub Mobile 随时随地发送分流通知IOS 系统或机器人. 
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;

**Comment by rexrainbow** [comment]
Close this issue, please create new thread in [discussions](https://github.com/rexrainbow/phaser3-rex-notes/discussions) section for another topic.

**Comment by woshisheji** [comment]
经过使用发现一个bug，那就是输入文本后，会倒着输入文字，光标会到最左边




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月19日(星期六) 下午5:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rexrainbow/phaser3-rex-notes] 大佬 有给phaser3使用的 canvasinput 这个插件吗 (Issue #233)





 
Closed #233.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rexrainbow** [comment]
Could you explain more detail? Like a simplest runnable demo or an image.

**Comment by woshisheji** [comment]
输入汉字之后就出现异常bug光标会到左边&nbsp; 引用的是&nbsp;rexhiddeninputtextplugin.min.js






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月9日(星期三) 上午9:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rexrainbow/phaser3-rex-notes] 大佬 有给phaser3使用的 canvasinput 这个插件吗 (Issue #233)






你能解释更多的细节吗？像一个简单的可运行的演示或图像。

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
使用 GitHub Mobile 随时随地发送分流通知IOS 系统或机器人. 
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;

**Comment by rexrainbow** [comment]
Can't reproduce this issue. 
Cursor will at **right** side of last character, when typing English or Chinese characters.
