### ISSUE TITLE
Uncaught ReferenceError: Percent is not defined

### ISSUE THREAD

**Issue by KeJunMao** [rexrainbow/phaser3-rex-notes#235]
Hi!,Happy Chinese new year!

I use `numberBar` and call easeValueTo function, but:
```
Uncaught ReferenceError: Percent is not defined
    at Slider.EaseValueTo [as easeValueTo] (EaseValueMethods.js:36)
    at NumberBar.easeValueTo (NumberBar.js:167)
```
I have to use this code to fix the bug:
```js
window['Percent'] = Phaser.Math.Percent
```
I try check `node_modules/phaser3-rex-plugins/plugins/utils/ease/EaseValueMethods.js` code:

https://github.com/rexrainbow/phaser3-rex-notes/blob/master/plugins/utils/ease/EaseValueMethods.js#L25-L46

`Percent` is not define.

Did I do something wrong?

**Comment by rexrainbow** [comment]
Missing variable declaration added. Thanks for reporting it.

**Comment by KeJunMao** [comment]
thank you!

if you publish to npm package,i would like test it.
thank you again

**Comment by rexrainbow** [comment]
I might upgrade npm package 2 weeks later.
