### ISSUE TITLE
Text area: Bounds are not updated when added to container

### ISSUE THREAD

**Issue by robinheidrich** [rexrainbow/phaser3-rex-notes#246]
I have created a Text area based on [this example](https://codepen.io/rexrainbow/pen/JzBZzy), and added it to a container using the `addToContainer` method.

The slider is positioned correctly, but the text remains in the same place and is partially hidden.

In the example add this above the textArea in the ```preload```method:

```js
var container = this.add.container(150, 30);
```

Then below the textArea:

```js
textArea.addToContainer(container);
```
![image](https://user-images.githubusercontent.com/23118399/156426070-96c53907-7549-48d4-86c3-d1af1fc8252e.png)

As you can see the bounds are not updated and the text is partly not visible.

**Comment by rexrainbow** [comment]
Don't put game object and its mask into a built-in container together. See this [test code](https://codepen.io/rexrainbow/pen/mdBZJmb).
And TextArea has a mask.

**Comment by rexrainbow** [comment]
Set `textMask` to `false` in config of TextArea's constructor, to disable mask feature. 
Then put Header and Footer elements above text game object, to replace mask feature. Now this TextArea has no mask and can put into built-in container.

**Comment by robinheidrich** [comment]
I tested it and it works fine! Thank you for the help!

While I'm at it, is it also possible to have the text start at the bottom instead of the top?
