### ISSUE TITLE
BBCode Text: Changing the cursor when hovering over area

### ISSUE THREAD

**Issue by robinheidrich** [rexrainbow/phaser3-rex-notes#255]
Currently there is no special behavior for the mouse pointer when you hover over an area. There is also no option to change the cursor.

This could be solved as follows:

1. Add `areaover` and `areaout` events to be able to change the cursor by yourself. 

2. An option that all areas get a hand cursor when hovering.

That would be a good addition!

**Comment by rexrainbow** [comment]
`areaover`, `areaout` events added. 

Changing cursor is another issue. It seems that no direct way to change cursor during runtime. I use this hack solution: 

```javascript
scene.input.manager.canvas.style.cursor = 'pointer';
```

See [this demo](https://codepen.io/rexrainbow/pen/voXPRM)

**Comment by robinheidrich** [comment]
Looks good, works as intended. I use `scene.input.setDefaultCursor('pointer');` instead.
