### ISSUE TITLE
Text area: Option for scroller thumb height based on content

### ISSUE THREAD

**Issue by robinheidrich** [rexrainbow/phaser3-rex-notes#257]
It would be great if there was an option or something to base the height of the scroller thumb on the content. Like the scrollbars in the browser, whose height is based on the content.

Maybe this can be the new standard and you have to set the height of the thumb yourself if you want it small (as it is now).

**Comment by rexrainbow** [comment]
rexUI: ScrollablePanel, GridTable, TextArea - Add `adaptThumbSize`, `minThumbSize` parameters, to adjust thumb height/width according to ratio of visible child
- [Demo](https://codepen.io/rexrainbow/pen/QWawEXZ) :  Change content in line 77
    ```js
    content: CreateContent(3)
    ```
    or
    ```js
    content: CreateContent(30)
    ```
    or
    ```js
    content: CreateContent(300)
    ```

**Comment by robinheidrich** [comment]
That is very good! Would it also be possible to add a button at the top and bottom to scroll, like in browsers? Optional of course.

Should I create a new issue for this idea?

**Comment by rexrainbow** [comment]
> That is very good! Would it also be possible to add a button at the top and bottom to scroll, like in browsers? Optional of course.

It is possible, I need more

**Comment by rexrainbow** [comment]
How to name these top and bottom buttons (or left and right buttons in horizontal scroll mode)?

**Comment by robinheidrich** [comment]
In browsers it's just called scrollbar button, maybe there could be a config for buttons and inside the game objects for each side.

For example something like that:

```js
{
  buttons: {
    top: scene.add.image(0, 0, 'scrollbar-button-top'),
    bottom: scene.add.image(0, 0, 'scrollbar-button-bottom'),
  },
  ...
}
```

**Comment by rexrainbow** [comment]
Might merge `buttons.top` to `topButton` to put configuration in the same level.

```javascript
{
    slider: {
        track: trackGameObject,
        thumb: thumbGameObject,
        topButton: topButtonGameObject,
        bottomButton: bottomButtonGameObject
    },
}
```

My concern is, there have horizontal and vertical scroll modes. 
- `topButton` for *top* and *left* button, `bottomButton` for *bottom* and *right* button, 
- Or name them as `button0` and `button1`

**Comment by rexrainbow** [comment]
I see, that would be a good solution, too. 
Or using `slider.buttons: []`?
```js
{
    slider: {
        track: trackGameObject,
        thumb: thumbGameObject,
        buttons: [buttonGameObject, buttonGameObject],
    },
}
```
Will the amount of buttons only be *2*?

**Comment by rexrainbow** [comment]
rexUI: ScrollablePanel, GridTable, TextArea - Add 
- `slider.buttons.top`,  `slider.buttons.bottom`
- `slider.buttons.left`,  `slider.buttons.right`
- `slider.buttons.step`,
parameters. 

Press these buttons to scroll content in each tick.  [Demo](https://codepen.io/rexrainbow/pen/QWawEXZ)

**Comment by robinheidrich** [comment]
Looks pretty good so far. Thanks for the implementation!

I noticed something else, and that is some of the text is behind the footer. But if you remove the footer, the text is visible and below the textarea.

Is that intentional?

![image](https://user-images.githubusercontent.com/23118399/158614523-eef723a3-577a-4cc6-adda-2b25802a5d1c.png)

**Comment by rexrainbow** [comment]
Yes, it is design intent. The extra line can make scroll more smoothly.

**Comment by robinheidrich** [comment]
It just feels weird because the text is below the slider and the same on top.

I don't know if it's because I disabled textMask, but it doesn't look very smooth either. One line always disappears at a time when scrolling instead of just showing part of the text.

**Comment by rexrainbow** [comment]
Ah, that's why textarea has a mask of text game object, or using header and footer game object to hide these extra area.

It is possible to create a scrollable text-area without mask, only drawing on canvas. I had made it in phaser4's bbcodetext class. ([demo](https://rexrainbow.github.io/phaser4-rex-plugins/public/home/#/BBCodeText_Scroll-text)).

**Comment by robinheidrich** [comment]
That looks better already. But Phaser 4 is still in early development, isn't it?

Also, I prefer the syntax of Phaser 3, so I'm not sure yet if I'll upgrade to Phaser 4 later.

**Comment by rexrainbow** [comment]
Update:

Cropping text game object when `textMask` is set to `false`. Default is `false` (won't have a mask by default)

**Comment by robinheidrich** [comment]
Seems a bit smoother, but new lines at the bottom are still cut off when scrolling and are only visible as a whole.

If that would be possible to make it like the top, it would be perfect.

**Comment by rexrainbow** [comment]
> Seems a bit smoother, but new lines at the bottom are still cut off when scrolling and are only visible as a whole.

Could you post a snapshot about this case?

**Comment by robinheidrich** [comment]
I have now tried a different font and it works, seems to have been due to the font.

Here with a different font where it cuts off at the bottom when scrolling:

![capture](https://user-images.githubusercontent.com/23118399/159827668-54f8b5e1-62b3-4c17-93be-d462d6e47317.gif)

**Comment by rexrainbow** [comment]
I see, that's weird. The last line disappears some time. What kind of font in this case?

**Comment by robinheidrich** [comment]
This is Burbank Small. It's not a problem, because I need Verdana anyway, but maybe there is a solution for this anyway?

**Comment by robinheidrich** [comment]
I guess it's not the font after all, but the font size. In the [Textarea example](https://codepen.io/rexrainbow/pen/JzBZzy) change text object to this:

```js
text: this.rexUI.add.BBCodeText(0, 0, '', { fontSize: '24px' })
 ```

![capture](https://user-images.githubusercontent.com/23118399/159831201-34e4c652-1cd0-4c70-a6d2-91f37d40e2a7.gif)

**Comment by rexrainbow** [comment]
It also depends on browser:

In firefox: 
![圖片](https://user-images.githubusercontent.com/817962/159833343-ba54db20-fc34-4d8e-8143-2f108f9e5ccb.png)

In chrome:
![圖片](https://user-images.githubusercontent.com/817962/159833533-ef352d22-0084-4683-86dc-482a04460deb.png)

**Comment by robinheidrich** [comment]
I also use Chrome.

I noticed another thing: Area in BBCode text does not work when `mouseWheelScroller.focus` is set to `true`. Is this intentional? So far it only did not work when `scroller` was on `true` but not that.

**Comment by rexrainbow** [comment]
`mouseWheelScroller.focus: true` will invoke `gameObject.setInteractive().on('wheel', ...)` [reference](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/plugins/input/mousewheeldcroller/MouseWheelScroller.js#L23-L30). 
It has `topOnly` issue, too, because that target game object of mouse wheel is not text game object.

**Comment by rexrainbow** [comment]
Update: TextArea, displays more 1 line to fix scrolling smooth issue.

**Comment by rexrainbow** [comment]
Set `topOnly` to `false` will allow multiple input targets, textarea and mouse wheel scroller both.

**Comment by rexrainbow** [comment]
Typo fixed, thanks for these suggestions

**Comment by robinheidrich** [comment]
Unfortunately, this is not a solution either, because area is then always clickable, even if there is a UI element above it.

I think then I have to disable the mouse scrolling for now.

**Comment by rexrainbow** [comment]
It seems that you have multiple stacked ui windows. There are some solutions for this case.

1. [Modal promise](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/modal-promise/), [reference](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-overview/#behaviors)
    ```js
    scene.rexUI.modalPromise(gameObject, config)
        .then(function(closeEventData){ })
    ```
    - [Demo](https://codepen.io/rexrainbow/pen/VwzbqEP)
1. [Cover](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/shape-cover/), which is a part of Modal. Put this game object behind background of ui window.
    ```js
    var shape = scene.rexUI.add.cover(config);
    ```
1. [TouchEventStop](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/toucheventstop/) behavior, which is a part of Cover. Put this behavior to background of ui window.
    ```js
    var touchEventStop = scene.rexUI.add.toucheventstop(gameObject, config);
    ```

**Comment by robinheidrich** [comment]
I don't think that's a solution either, because I don't want to block the whole background.

Is there no way that the events could only be extended and not overwritten?

**Comment by rexrainbow** [comment]
Don't have solution yet. In this case :

- Different touch targets  => Set `topOnly = false`
- Block unnecessary touch events via `event.stopPropagation()` [reference](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/touchevents/#touch-events)

**Comment by robinheidrich** [comment]
@rexrainbow Instead of setting setInteractive on the game object, wouldn't it be possible to just check in the callback if the mouse pointer is over the game object?

So that `mouseWheelScroller.focus` works with multiple inputs?

**Comment by rexrainbow** [comment]
You can get mouse-wheel event via
```js
scene.input.on('wheel', function(pointer, currentlyOver, dx, dy, dz, event){ /* ... */ });
```

It does not interactive with game object.
Under this event, test if mouse cursor is inside scrollable panel via
```js
var isTouching = scrollablePanel.isInTouching();
```

**Comment by robinheidrich** [comment]
I was talking about [this particular section of code](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/plugins/input/mousewheelscroller/MouseWheelScroller.js#L23-L30), if this were changed to always use the callback and instead check in the callback if the mouse pointer is over the game object instead of using setInteractive, `mouseWheelScroller.focus` would work without `topOnly` or other workarounds, wouldn't it?

**Comment by rexrainbow** [comment]
These 2 solution have a little different. 
For example, a big game object is put above scrollable panel. `scrollablePanel.isInTouching()` will still return true if pointer is inside the bounds of scrollable panel.
But `gameObject.on('wheel', ...)` won't be fired, if `topOnly` is `true`. Because that only the top game object will receive touch events.
