### ISSUE TITLE
typescript dev

### ISSUE THREAD

**Issue by jcyuan** [rexrainbow/phaser3-rex-notes#26]
this lib looks great and worth to have a try  :+1: 
but before that I have a few of questions:
1. is there .d.ts definition available?
2. is it possible to compile with ES5? (our environment can't fully support es6+ so have to use es5)

thank you~

**Comment by rexrainbow** [comment]
1. No, I don't have plan to support typescript recently.
2. My plugins are wrote in es6, and I only test them in firefox and chrome only.  So I guess the answer is no, either.

**Comment by jcyuan** [comment]
ok, thanks anyway

**Comment by khasanovbi** [comment]
Hi, I want to support typescript for this library, if you have some time you can help me to cover types https://github.com/khasanovbi/phaser3-rex-plugins-types

**Comment by rexrainbow** [comment]
@khasanovbi Thanks for this contribution. However, I still did not have time for adding typescript to my phaser3 plugins.
I am working in porting my phaser3 plugin to [phaser4, with typescript](https://github.com/rexrainbow/phaser4-rex-plugins).

**Comment by jcyuan** [comment]
oops, sorry, words to those who thumbs down at 2nd floor:

> 1. is there .d.ts definition available?

you can just write a very smple one (this is what i did and feel enough)

> 2. is it possible to compile with ES5? (our environment can't fully support es6+ so have to use es5)

use Babel to transpile. and it's just a easy task.

I'm using this plugin right now, and it's awesome.
