### ISSUE TITLE
GetDefaultBounds returns incorrect size when using Phaser.Scale.RESIZE

### ISSUE THREAD

**Issue by zpxp** [rexrainbow/phaser3-rex-notes#267]
Create a game with config scale `Phaser.Scale.RESIZE` and no height and width defined to auto resize the window.

`GetDefaultBounds` for some components like `Menu` doesn't return the current screen width, only the default value.

This creates an artificially small bounds even though the game window is larger.

**Comment by rexrainbow** [comment]
I replace `GetDefaultBounds` method by [`GetViewPort`](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/plugins/utils/system/GetViewport.js), now Menu can work with `Phaser.Scale.RESIZE` mode.
Please get latest version of minify file. NPM package will update at end of this month.
