### ISSUE TITLE
When using NPM package, rex UI plugin fails to load

### ISSUE THREAD

**Issue by djdabs** [rexrainbow/phaser3-rex-notes#268]
Setting up a scrollable panel. Was using rex UI plugin through NPM package, but its giving me an error pulling in plugin through game config. 

Error:
`TypeError: Cannot read properties of undefined (reading 'game')`

Plugin Setting:
```
import UIPlugin from 'phaser3-rex-plugins/templates/ui/ui-plugin.js';

{
        key: 'rexUI',
        plugin: UIPlugin,
        mapping: 'rexUI'
}
```

Versions:

```
"phaser3-rex-plugins": "^1.1.68",
"phaser": "^3.55.2",
```

Using the minified file in scene preload, everything works fine. Maybe NPM package needs an update?

**Comment by rexrainbow** [comment]
Please check that rexui is a [scene plugin](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/ui-scrollablepanel/panel.js#L267), not a global plugin.

**Comment by djdabs** [comment]
ah, yep that fixed it.. I was putting into globals. 

Thank you for the quick reply Rex and for building these modules for us! 💯
