### ISSUE TITLE
how to retrieve Pointer object?

### ISSUE THREAD

**Issue by jcyuan** [rexrainbow/phaser3-rex-notes#27]
when got a button.click event, I need to know the click coordinate, so is there a way to retrieve the pointer object generated by Phaser?

**Comment by rexrainbow** [comment]
Thank you for this feature suggestion.
In my lastest commit, I pass `pointer` into parameters of buttons-events,
See [buttons-event](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-buttons/#events), [dialog-events](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-dialog/#events), and [tabs-events](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-tabs/#events)
