### ISSUE TITLE
rex的minicontainer 怎么和现在对象层次排序呢

### ISSUE THREAD

**Issue by woshisheji** [rexrainbow/phaser3-rex-notes#271]
大佬 我发现gird table 添加后 为什么会一直在最顶层呢，设置深度排序也无效  有点难受

如图：

![image](https://user-images.githubusercontent.com/44597918/163735592-7d780651-0f16-45a3-98d0-e5e3a9137482.png)

然后我打开table
![image](https://user-images.githubusercontent.com/44597918/163735602-e3b82bdf-53e7-4ee4-a161-cfb003594017.png)

使用了你说的那个child 设置层次似乎无效 3.55的版本

**Comment by woshisheji** [comment]
按道理它在 mini容器中，不应该在下一层吗，为啥一直在最顶了，看他的深度也是0~奇怪了。。

**Comment by rexrainbow** [comment]
Could you post a simplest test code for this case?

**Comment by woshisheji** [comment]
let 高级表格= {};
&nbsp;let 背景图= {};
&nbsp;let 滑块条= {};
&nbsp;let 滑块条前= {};
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp; 背景图 = H5object.add.rectangle(0,0,100,100, 0x272822);
&nbsp; &nbsp;
&nbsp; 滑块条 = H5object.add.rectangle(0, 0, 20, 4, 0x404040);
&nbsp; &nbsp;
&nbsp; 滑块条前 = H5object.add.rectangle(0, 0, 20, 40, 0x383830);
&nbsp; &nbsp;
&nbsp;
	&nbsp; 高级表格 = H5object.rexUI.add.gridTable({x: 100, y: 100, anchor:0, width: 640, height: 200, scrollMode: 0, background: 背景图, table:{width:undefined, height:undefined, cellWidth: 100, cellHeight: 100, columns: 6, mask:{padding:-1}, interactive:true, reuseCellContainer:false, }, slider:{track: 滑块条, thumb: 滑块条前, }, scroller:{threshold:10, slidingDeceleration:2000, backDeceleration:5000, }, clamplChildOY:false, space:{left:0, right:0, top:0, bottom:0, table:0, table:{top:0, bottom:0, left:0, right:0, }, header:0, footer:0, }, expand:{header:true, footer:true, }, align:{header:'center', footer:'center', }, items:[], name:'', draggable:false, createCellContainerCallback:function(cell, cellContainer){
	&nbsp;
		&nbsp; if(cellContainer == undefined){
		&nbsp; cellContainer = H5object.rexUI.add.overlapSizer({x:0, y: 0, width: 100, height: 100,anchor: 0, space:{left: 0, right: 0, top: 0, bottom: 0}})
		&nbsp;
		&nbsp;
		&nbsp;
		&nbsp; let 临时背景 = H5object.add.rectangle(0, 0, 100, 100, 0x6C6C5E);
&nbsp; &nbsp;
		&nbsp; 临时背景.setStrokeStyle( 1,&nbsp; 0x007ACB,&nbsp; 1);
		&nbsp;
		&nbsp; cellContainer.add( 临时背景, {key: undefined, align: 'left', padding:{left: 0, right: 0, top: 0, bottom: 0}, expand: true, minWidth: undefined, minHeight: undefined})
		&nbsp;
		&nbsp;
		&nbsp;
		&nbsp;
		&nbsp; cellContainer.depth= 篮球盒子.depth + 1;
		&nbsp;
		&nbsp;
	&nbsp; }
	&nbsp; return(cellContainer);
&nbsp; }});
&nbsp;
&nbsp; 高级表格.setOrigin( 0,&nbsp; 0);
&nbsp; 高级表格.layout();
&nbsp;
&nbsp;
&nbsp; let 篮球盒子 = H5object.add.container(100,&nbsp; 100);
&nbsp; let 框子 = H5object.add.rectangle(0, 0, 100, 100, 0x404040);
&nbsp; &nbsp;
&nbsp; 框子.setOrigin( 0,&nbsp; 0);
&nbsp; 篮球盒子.add(框子);
&nbsp;
	&nbsp; H5object.input.keyboard.on('keydown-A', function (event) {
	&nbsp;
	&nbsp;
	&nbsp; let 临时对象 = {}
	&nbsp; 临时对象.key = '001';
	&nbsp; Phaser.Utils.Array.Add(高级表格.items,&nbsp; 临时对象);
	&nbsp; 高级表格.refresh();
	&nbsp;
&nbsp; }, H5object);





// 里面的 表格对象会覆盖这个容器的层次，导致 篮球盒子&nbsp; 这个对象看不到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月18日(星期一) 上午8:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rexrainbow/phaser3-rex-notes] rex的minicontainer 怎么和现在对象层次排序呢 (Issue #271)






你能为这个案例发布一个最简单的测试代码吗？

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;

**Comment by woshisheji** [comment]
![被覆盖掉了](https://user-images.githubusercontent.com/44597918/163738073-e7c07c17-10eb-46e7-8402-a89963e36d97.gif)

**Comment by woshisheji** [comment]
不知道该如何 让这个表格与官方的容器之间进行排序

**Comment by woshisheji** [comment]
H5object.children.bringToTop(篮球盒子)  哦，似乎必须在表格事件中添加这个命令才可以。。。似乎有些复杂。不能直接整个表格管理吗

**Comment by woshisheji** [comment]
额。反复尝试下可以了。感谢大佬。
