### ISSUE TITLE
Setting scrollable panel or grid table to draggable true, can't click on underlying objects anymore

### ISSUE THREAD

**Issue by djdabs** [rexrainbow/phaser3-rex-notes#274]
Looking at these examples below: 

Grid table - https://codepen.io/rexrainbow/pen/XyJbWX
Scrollable Panel - https://codepen.io/rexrainbow/pen/YMyBom

When setting the table or panel to draggable: true, can no longer click on the underlying buttons/items

**Comment by rexrainbow** [comment]
It is normal. To click children game object under draggable panel, you might set
```js
this.input.topOnly = false
```

See [scrollable panel demo](https://codepen.io/rexrainbow/pen/YMyBom), line 112.

**Comment by djdabs** [comment]
Works! You rock, thank you!
