### ISSUE TITLE
 is it possible to scroll gridTable horizontally in rexUI ?

### ISSUE THREAD

**Issue by www3563772** [rexrainbow/phaser3-rex-notes#28]
is it possible to scroll gridTable horizontally in rexUI ?

**Comment by rexrainbow** [comment]
I add a new parameter `scrollMode` in the config of gridtable in latest commit.
See this [demo](https://codepen.io/rexrainbow/pen/XyJbWX), set `scrollMode` to `1` in line 19, and run this demo again. It will show a horizontal gridtable.

**Comment by www3563772** [comment]
Thank you.
