### ISSUE TITLE
import CreateFixWidthSizer from './CreateFixwidthSizer.js'; Case error

### ISSUE THREAD

**Issue by junthink** [rexrainbow/phaser3-rex-notes#295]
There is a case error in this file
templates/ui/maker/builders/Builders.js 
`
import CreateFixWidthSizer from './CreateFixwidthSizer.js';
`
`
import CreateFixWidthSizer from './CreateFixWidthSizer.js';
`

**Comment by junthink** [comment]
`
import CreateTextBox from './CreateTextbox.js';
`
`
import CreateTextBox from './CreateTextBox.js';
`

**Comment by rexrainbow** [comment]
Typo fixed. NPM package will upgrade at end of this month.
