### ISSUE TITLE
Phaser 3 virtual joystick

### ISSUE THREAD

**Issue by corona1117** [rexrainbow/phaser3-rex-notes#3]
I am struggling to find the virtual joystick of phaser 3. but I can't find that. Please help me.

**Comment by rexrainbow** [comment]
I had made a virtual joystick plugin. Here are 
- [Document](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/virtualjoystick/index.html), 
- [Demo](https://codepen.io/rexrainbow/pen/oyqvQY), and
- [Discussing thread](http://www.html5gamedevs.com/topic/37830-plugin-rexdrag-rexslider-rexvirtualjoystick/) in forums.
