### ISSUE TITLE
Invalid Plugin: rexUI when loading rexuiplugin.min.js  via: plugins.install on Phaser 3.16.2

### ISSUE THREAD

**Issue by goedzo** [rexrainbow/phaser3-rex-notes#30]
Hi,

I am running Phaser within a Cordova / Phonegapp application so that I can combine various technologies in my app. Because of this, I am not able to use the import functionality to load the rexplugin, so using a workaround I am doing this:

In my index.html I have the following code (short snippet, not full code)
```
<!DOCTYPE html>
<html lang="en">
<head>
  <script type="text/javascript" src="cordova.js"></script>
  <script type="text/javascript" src="js/phaser.min.js"></script>
  <script language="javascript" type="module">
	import * as UIPlugin from '../Objects/rexuiplugin.min.js';
	window.UIPlugin=UIPlugin;
 </script>
</head>
<body>
  <div id="app" class="color-theme-white theme-blue">
        <div class="page-content page_image">
			  			<div id="game" class="row">
			</div>

        </div>
    </div>
  <script src="js/app.js" type=""></script>
</body>
</html>
```

Then in my app code, which is fully cordova compatible, I use the following code to load rexuiplugin:

```
function delayedStartActivities(){
    if (!window.plugins) {
        setTimeout(delayedStartActivities, 300);
        return;
    }
    
    appRequestReady();
    //Keep screen awake
    window.plugins.insomnia.keepAwake();
	
	
	//Now load Phaser

	phaserGame = new Phaser.Game(config);
	const model = new Model();
	phaserGame.globals = { model, bgMusic: null };
	phaserGame.scene.add('Boot', BootScene);
	phaserGame.scene.add('Preloader', PreloaderScene);
	phaserGame.scene.add('Title', TitleScene);
	phaserGame.scene.add('Options', OptionsScene);
	phaserGame.scene.add('Credits', CreditsScene);
	phaserGame.scene.add('Transition', TransitionScene);

	phaserGame.plugins.install('rexUI', window.UIPlugin);

	phaserGame.scene.add('Home', HomeScene);
	phaserGame.scene.start('Boot');
}
```

This results in the message: 
Invalid Plugin: rexUI

And phaserGame.plugins gives back 0 plugins, so it is not loaded.

For some reference, please note that I cannot load this in my config.js, as this is not a module file that can be imported and defined globally.

Hope you can explain if this is a bug, or I am doing something wrong here.

**Comment by goedzo** [comment]
As another test, I've loaded this in my config like this:

```
import * as UIPlugin from '../Objects/rexuiplugin.min.js';

var config = {
	//type: Phaser.WEBGL,
    //Set to canvas because my texture for map exceeds max size of 4096
    type: Phaser.CANVAS,
	//transparent: true,
	scale: {
		mode: Phaser.Scale.FIT,
		autoRound: true,
		autoCenter: Phaser.Scale.CENTER_BOTH,
		parent: "game",
		width: 576,
		height: 1024,

	},
	plugins: {
        scene: [{
            key: 'rexUI',
            plugin: UIPlugin,
            mapping: 'rexUI'
        },
        // ...
        ]
    },
	physics: {
		default: 'arcade',
		arcade: {
			gravity: { y: 0 },
			debug: false // set to true to view zones

		}
	},
	debug: false, 
};
window.config=config;
```

Then the error message appears:"Invalid Scene Plugin: rexUI", so it looks like there is something wrong with the code.

I've only imported this file into my code:
https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/plugins/dist/rexuiplugin.min.js

**Comment by rexrainbow** [comment]
How about import rexUI in html page
```html
<script type="text/javascript" src="../Objects/rexuiplugin.min.js"></script>
```
then install rexUI plugin from game config
```javascript
var config = {
    // ...
    plugins: {
        scene: [
            {
                key: 'rexUI',
                plugin: rexuiplugin,
                mapping: 'rexUI'
            }
        ]
    }
    // ...
};
var game = new Phaser.Game(config);
```

**Comment by goedzo** [comment]
Hi. Thanks for your suggestion but this cannot be done as the rexuiplugin.min.js is setup as a js module, thus if you import it like this you will get the error that rexuiplugin is undefined, unless the file itself exports it as a global variable. I was not able to read the code since i could only find the .min version is there, so its hard for me to debug this.

**Comment by goedzo** [comment]
Ok so I used your example and yes it works perfectly! It seems that your module also exports it's own class as rexuiplugin, so you can also add this to your documentation :). I will close this issue, as it seems to be the perfect solution if you cannot import the class as a module.

**Comment by rexrainbow** [comment]
Here is another way to load and install rexUI plugin.
```javascript
scene.load.scenePlugin({
    key: 'rexuiplugin',
    url: 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/plugins/dist/rexuiplugin.min.js',
    sceneKey: 'rexUI'
});
```
See [this demo](https://codepen.io/rexrainbow/pen/YMyBom), line 13.

It is equal to
1. Load `rexuiplugin.min.js` file via script tag.
2. Install `rexuiplugin` via game config.

**Comment by XXXiV-QN** [comment]
Hello rexrainbow, thank you for the advise. I have been trying to follow the instruction here, but still running into load problems. Here is what I did: 

I imported rexUI in html:
`<script src="./js/ui/rexuiplugin.min.js" type="text/javascript"></script> `

I added the plugin to the Phaser game config:
```
export var config = {
    type: Phaser.AUTO,
    audio: false,
    width: 1000,
    height: 600,
    scene: [...], //add all scenes here
    plugins: {
        scene: [{
            key: 'rexUI',
            plugin: rexuiplugin,  //load the UI plugins here for all scenes
            mapping: 'rexUI'
        }]
    }
```

Then in one of my scene within the create() function, I was trying to add a demo button:
`var buttons = this.rexUI.add.buttons({...})`

However, I keep getting "undefined" issues
<img width="623" alt="Screen Shot 2020-12-02 at 8 53 44 AM" src="https://user-images.githubusercontent.com/53305147/101169879-99ee3f00-360b-11eb-8dac-e30acbc95546.png">

Any idea or suggestions? Many thanks!

**Comment by XXXiV-QN** [comment]
> Here is another way to load and install rexUI plugin.
> 
> ```js
> scene.load.scenePlugin({
>     key: 'rexuiplugin',
>     url: 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/plugins/dist/rexuiplugin.min.js',
>     sceneKey: 'rexUI'
> });
> ```
> 
> See [this demo](https://codepen.io/rexrainbow/pen/YMyBom), line 13.
> 
> It is equal to
> 
> 1. Load `rexuiplugin.min.js` file via script tag.
> 2. Install `rexuiplugin` via game config.

I got this error when tried this: 

`phaser-arcade-physics.min.js:1 GET https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/plugins/dist/rexuiplugin.min.js 404 (Not Found)`

**Comment by rexrainbow** [comment]
@XXXiV-QN Url of rexUI is not correctly. Please download plugin from [here](https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/dist/rexuiplugin.min.js)

**Comment by XXXiV-QN** [comment]
Thank you! I changed the scene.load.scenePlugin, and without the config plugin set up.
```
this.load.scenePlugin({
            key: 'rexuiplugin',
            url: './js/ui/rexuiplugin.min.js',
            sceneKey: 'rexUI'
        });  
```
This currently gives me a warning:
`phaser-arcade-physics.min.js:1 Invalid Scene Plugin: rexuiplugin `

If I uncomment the config plugin part:
```
plugins: {
        scene: [{
            key: 'rexUI',
            plugin: rexuiplugin, //load the UI plugins here for all scenes
            mapping: 'rexUI'
        }]
    }
```
It gives me this error:
```
index.js:21 Uncaught ReferenceError: rexuiplugin is not defined
    at index.js:21
```

I haven't test any other demo yet, but this is the issue I am currently running into.

**Comment by rexrainbow** [comment]
Please try [phaser.min.js](https://github.com/photonstorm/phaser/releases/download/v3.24.1/phaser.min.js), instead of *phaser-arcade-physics.min.js*

**Comment by Esrat21** [comment]
> Hello rexrainbow, thank you for the advise. I have been trying to follow the instruction here, but still running into load problems. Here is what I did:
> 
> I imported rexUI in html:
> `<script src="./js/ui/rexuiplugin.min.js" type="text/javascript"></script> `
> 
> I added the plugin to the Phaser game config:
> 
> ```
> export var config = {
>     type: Phaser.AUTO,
>     audio: false,
>     width: 1000,
>     height: 600,
>     scene: [...], //add all scenes here
>     plugins: {
>         scene: [{
>             key: 'rexUI',
>             plugin: rexuiplugin,  //load the UI plugins here for all scenes
>             mapping: 'rexUI'
>         }]
>     }
> ```
> 
> Then in one of my scene within the create() function, I was trying to add a demo button:
> `var buttons = this.rexUI.add.buttons({...})`
> 
> However, I keep getting "undefined" issues
> <img alt="Screen Shot 2020-12-02 at 8 53 44 AM" width="623" src="https://user-images.githubusercontent.com/53305147/101169879-99ee3f00-360b-11eb-8dac-e30acbc95546.png">
> 
> Any idea or suggestions? Many thanks!

Hi, i have the same errors while loading the rexuiplugin, it was working fine, then suddenly stopped, i tried to change the load but didnt work

**Comment by rexrainbow** [comment]
@Esrat21 Not enough information for reproducing your case, please open a new issue with simplest test code.

**Comment by cleve02** [comment]
@rexrainbow I'm getting the same error while loading this 
<img width="565" alt="Screenshot 2023-05-17 at 13 59 42" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/35739047/96223e02-62b8-4cc1-b963-6de511b7917a">
<img width="410" alt="Screenshot 2023-05-17 at 14 00 46" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/35739047/1dc83c22-5ade-4bbb-8f46-ce7c87a92fef">
