### ISSUE TITLE
ui-textbox usage problem

### ISSUE THREAD

**Issue by Ouskit** [rexrainbow/phaser3-rex-notes#31]
Hi, your notes and examples is greatly helpful for me, but I tried to use the example of ui-textbox to apply to my game project, I don't know modified the code to make the 
1. textbox stop when it comes to last page, and 
2. when user click the last page, it will become invisible ?

![圖片](https://user-images.githubusercontent.com/17953466/57785471-623b5000-7764-11e9-8f00-248234801ccb.png)

It always automatically be invisible after showing the last word in last page, but I want player to click the last page make it invisible.

**Comment by Ouskit** [comment]
OK, let me answer myself, I found that just modified to this then it solved my problem.
![圖片](https://user-images.githubusercontent.com/17953466/57786470-1e494a80-7766-11e9-8328-64d985747ac2.png)

**Comment by rexrainbow** [comment]
When a child is added to parent (textbox), the current visible status will be saved. In this demo, action icon object is `invisible`. 
If you change textbox to `invisible` then `visible` again, action icon object will be reset to `invisible`. It might be annoying if you set action icon object to `visible` before change textbox's visible state.
To fix this issue, you can call `parent.resetChildVisibleState(child)` to save current visible status of child again, like this -- 
```javascript
var icon = this.getElement('action').setVisible(true);
this.resetChildVisibleState(icon);
```

**Comment by Ouskit** [comment]
I got it, thanks for your replay!  😃
