### ISSUE TITLE
Unable to get rexVirtualJoyStick

### ISSUE THREAD

**Issue by gnesher** [rexrainbow/phaser3-rex-notes#32]
Hi,

I might be missing something but using latest Phaser (3.17) I've copied rexvirtualjoystickplugin.min.js to a local plugin folder and instantiated it - 

```
    plugins: {
        global: [{
            key: 'rexVirtualJoyStick',
            plugin: VirtualJoyStickPlugin,
            start: true
        }],
    },
```

but when I try to call it from the scene 

```
    let plugin = this.plugins.get('rexVirtualJoyStick');
```

it returns null

**Comment by rexrainbow** [comment]
[Here](https://codepen.io/rexrainbow/pen/oyqvQY) is an example of installing plugin from (rexvirtualjoystickplugin.min.js) file:

1. In preload stage, line 10, `scene.load.plugin('rexvirtualjoystickplugin', url, true);`
2. Get plugin via `scene.plugins.get('rexvirtualjoystickplugin')`

Note that the key in `scene.load.plugin` method, and `scene.plugins.get` method must be *rexvirtualjoystickplugin*.

**Comment by gnesher** [comment]
Thanks for the quick reply.
If you try to use the plugin under this typescript boilerplate (https://github.com/digitsensitive/phaser3-typescript - just drop the plugin in the /boilerplate lib and try to use it in the scene) the plugins.get returns null.

I'm happy to set up a demo - though it'll take you a second to set it up

**Comment by rexrainbow** [comment]
Sorry I don't have any experience of using typescript, I have no idea how to solve it. ( as I know, 3.17.0 also updated lots of typescript files )
Fortunately, you have post it on phaser's [issue](https://github.com/photonstorm/phaser/issues/4533), hope somebody can provide a good solution.

**Comment by gnesher** [comment]
@rexrainbow so it seems the import is returning undefined (but Phaser doesn't do any type of sanity check so I only discover the problem when I try to use the plugin).

Long story short it's a little hard for me to debug this, as I'm not sure how you generate the minified version - but I'm guessing there's a problem there? which module system are you exporting to?

**Comment by rexrainbow** [comment]
[Here](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/webpack.plugins.config.js#L127-L129) is the webpack setting of exporting plugin.

BTW. I can install plugin via external file, or use `import` instruction to include minify file as well.

**Comment by shanelanghans** [comment]
I have tried  `import` of the minify file and plugins key in game config, as well as `scene.load.plugin()` of minify file. Either way, scene.plugins.get() returns null
