### ISSUE TITLE
webpack optimization

### ISSUE THREAD

**Issue by jcyuan** [rexrainbow/phaser3-rex-notes#33]
![image](https://user-images.githubusercontent.com/850854/57946635-6788ce00-790f-11e9-9bfc-820151b81a57.png)

don't know why, I have already comment this out in the webpack.plugins.config.js:
![image](https://user-images.githubusercontent.com/850854/57946649-72dbf980-790f-11e9-880f-7d5ba0565456.png)

but somehow it was still combined into the output.

**Comment by jcyuan** [comment]
besides, can we just use `Phaser.Events.EventEmitter` instead of putting the `EE` classes into the final output? this increases the output file size, actually our environment is a bit special, we need to always take the file size into account.

**Comment by jcyuan** [comment]
sorry it works, it was a wrong I edited...

**Comment by rexrainbow** [comment]
Usually I will try to use `Phaser.Events.EventEmitter` in a object class, unless I suppose this object could be used standalone, for example, used in node.js in server side.

**Comment by rexrainbow** [comment]
I change the EventEmitter class from local file to built-in EventEmitter class (`Phaser.Events.EventEmitter`). which can reduce the output size.

**Comment by jcyuan** [comment]
@rexrainbow awesome!! :+1:  thanks so much.
