### ISSUE TITLE
Missing TS types for "nameText" and "valueText" (nameValueLabel)

### ISSUE THREAD

**Issue by kibertoad** [rexrainbow/phaser3-rex-notes#337]
https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-namevaluelabel/ mentions parameters `nameText` and `valueText`, and they actually work, but TS complains that they are not defined.

**Comment by rexrainbow** [comment]
[d.ts file](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/templates/ui/namevaluelabel/NameValueLabel.d.ts#L29-L30) has been updated. NPM package will upgrade at middle of this month.

**Comment by rexrainbow** [comment]
NPM package had been upgraded.
