### ISSUE TITLE
Invalid TS types for tabPages

### ISSUE THREAD

**Issue by kibertoad** [rexrainbow/phaser3-rex-notes#338]
`this.scene.rexUI.add.tabPages({` complains that there is no method `tabPages`, but it works. 

`TabPages`, which is how it defined in types, does not work.

**Comment by rexrainbow** [comment]
It's typo. Now it has been [fixed](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/templates/ui/ui-plugin.d.ts#L182). 
Thanks for reporting this issue.

**Comment by rexrainbow** [comment]
NPM package had been upgraded.
