### ISSUE TITLE
Invalid TS type for ColorPicker configs

### ISSUE THREAD

**Issue by jqpoon** [rexrainbow/phaser3-rex-notes#339]
Hello,

`valuechangeCallbackScope` is a valid config for `ColorPicker` according to https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-colorpicker/. It works if typechecking is disabled.

However, it seems like the typescript definitions at https://github.com/rexrainbow/phaser3-rex-notes/blob/master/templates/ui/colorinput/colorpicker/ColorPicker.d.ts are not updated.

Thanks!

**Comment by rexrainbow** [comment]
[Added](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/templates/ui/colorinput/colorpicker/ColorPicker.d.ts#L19), thanks for this reporting.
