### ISSUE TITLE
Button class shutdown

### ISSUE THREAD

**Issue by jcyuan** [rexrainbow/phaser3-rex-notes#34]
in the newest version it seems a mistake caused by code maintainance:
in `plugins\input\button\Button.js`

    class Button {
        ....
        shutdown() {
                super.shutdown();    // error throws: TypeError: (intermediate value).shutdown is not a function

there is no super class..      :)

**Comment by rexrainbow** [comment]
Now they are fix.
Sorry, it's my mistake. I tried to replace inheriting from an event emitter class by adding an event emitter member.

**Comment by jcyuan** [comment]
cool, thanks so much~
