### ISSUE TITLE
Modal on open doesn’t fire

### ISSUE THREAD

**Issue by 343dev** [rexrainbow/phaser3-rex-notes#341]
Hi there.

Since v1.1.79 the “open” event doesn’t fire when modal `duration.in` is set to zero.

https://codepen.io/343dev/pen/BaOdpXm

**Comment by rexrainbow** [comment]
Thanks, this issue has been fixed in latest commit. 

The root cause is, modal behavior opens dialog game object too early before registering 'open' event. 
Now the modal will open dialog next tick after creating this modal behavior.
