### ISSUE TITLE
ui-edit/login example is not working

### ISSUE THREAD

**Issue by dranitski** [rexrainbow/phaser3-rex-notes#35]
1) https://github.com/rexrainbow/phaser3-rex-notes/blob/a3a27f78b6162a6181ba7569dd79ab200654d4ce/examples/ui-edit/login.js

![image](https://user-images.githubusercontent.com/27373393/58417561-d68fc080-808d-11e9-8322-e6aebc82dedc.png)

**Comment by dranitski** [comment]
it works, seems like the issue was in the **set testmode=2** line here https://github.com/rexrainbow/phaser3-rex-notes/blob/a3a27f78b6162a6181ba7569dd79ab200654d4ce/examples/ui-edit/login.bat

**Comment by rexrainbow** [comment]
`testmode=2` is used to get the latest version (current is 3.18 dev) of phaser3 in my local folder `../phaser`.

The reason why I use latest version of phaser3 is -
Touch events in 3.17 is not worked fine, so I use 3.16.2 for the all general cases.
But this `ui-edit/login.js` need DOM element released in 3.17, therefore I use the latest version of phaser3.

Sorry for inconvenience.
