### ISSUE TITLE
Tap is delayed and settings have no effect on responsiveness

### ISSUE THREAD

**Issue by vinny-888** [rexrainbow/phaser3-rex-notes#350]
How can the tap happen instantly?

Right now the tap is delayed

Setting these has no effect

```
time: 1,
tapInterval: 1,
```

**Comment by vinny-888** [comment]
I was able to just use this for instant triggering

```
this.input.on('pointerdown', function(pointer, localX, localY, event){ 
      this.tapped = true;
    }, this);
```

**Comment by rexrainbow** [comment]
Tap event is fired when pointerdown and pointerup very quickly, and it will has a delay to distinguish for next tapping. To discard next tapping detecting, you can assign `taps` parameter of constructor config, ex:

```js
scene.rexGestures.add.tap({
    //...
    taps: 1
});
```

- Only detect 1 tap. i.e. 2 taps will be treated as 1 tap. [Test code](https://codepen.io/rexrainbow/pen/KLWZPq)
