### ISSUE TITLE
TS type typo for statesRoundRectangle

### ISSUE THREAD

**Issue by jqpoon** [rexrainbow/phaser3-rex-notes#352]
Hello,

I believe there is a missing 's' on this line:
https://github.com/rexrainbow/phaser3-rex-notes/blob/master/templates/ui/ui-plugin.d.ts#L184

It should be `statesRoundRectangle` instead of `stateRoundRectangle`, according to the usage documentation [here](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-statesroundrectangle/#usage).

Thanks!

**Comment by rexrainbow** [comment]
Thanks. Has fixed it in [latest submit](https://github.com/rexrainbow/phaser3-rex-notes/commit/93d8ae2fb0db18d22740bf6a9f3c47ab2a2fc2e3).

**Comment by rexrainbow** [comment]
Upgrade npm package to 1.60.1
