### ISSUE TITLE
phaser.min.js:1 Invalid Scene Plugin: rexuiplugin

### ISSUE THREAD

**Issue by cleve02** [rexrainbow/phaser3-rex-notes#354]
I'm getting this error while loading the UI plugin on phaser. Gestures plugin works fine but this one doesn't
<img width="565" alt="Screenshot 2023-05-17 at 13 59 42" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/35739047/9d1a1740-6252-4a83-b753-d13490d13cab">
<img width="410" alt="Screenshot 2023-05-17 at 14 00 46" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/35739047/8cad5694-7f14-4fdb-9485-7b9f25c8f8d3">

**Comment by rexrainbow** [comment]
Latest version of my plugins/rexUI only work with phaser3.60. Might check phaser3 version first.

**Comment by cleve02** [comment]
@rexrainbow This is correct. Thanks
