### ISSUE TITLE
Please add strikethrough for bbcode

### ISSUE THREAD

**Issue by dtturcotte** [rexrainbow/phaser3-rex-notes#358]
Hello,

Firstly, thanks for all of the work you've done on RexUI. 

Secondly, I need to add strikethrough for your [BBCode](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/bbcodetext/) module. As you know, BBCode strikethrough is supported by [BBCode standard](https://en.wikipedia.org/wiki/BBCode) as `[s][/s]`. Are you able to add it? Thank you!

**Comment by rexrainbow** [comment]
Feature added, see [this demo](https://codepen.io/rexrainbow/pen/OZbOyg), text object at left side, the last line.

```
[s]Last line[/s]
```

You can override line color via

```
[s=yellow]Last line[/s]
```

NPM package will be upgraded at end of this month.

**Comment by dtturcotte** [comment]
Awesome, thank you!

**Comment by dtturcotte** [comment]
Also note your underline `[u][/u]` does not work.

**Comment by rexrainbow** [comment]
`[u]...[/u]` is provided. 
From previous [demo](https://codepen.io/rexrainbow/pen/OZbOyg), I add `[u]...[/u]` to the last line of left text object

```
[s][u]Last line[/u][/s]
```

You can see the underline and strikethrough both on that text line.

The color of underline is set to `#000` in this demo.
