### ISSUE TITLE
many of the codepen example are not working

### ISSUE THREAD

**Issue by cristlee** [rexrainbow/phaser3-rex-notes#36]
for example   https://codepen.io/rexrainbow/pen/YMyBom

**Comment by cristlee** [comment]
![Capture](https://user-images.githubusercontent.com/1849042/58477423-120db600-8186-11e9-8c80-1ea4110bf8db.PNG)

**Comment by rexrainbow** [comment]
Thanks for this bug reporting. I had fixed it, they ought to work now.

I use DOMElement game object released in 3.17, for new `edit` method in latest rexUI package. But I did not change phaser version to 3.17 in these codepen demos.
