### ISSUE TITLE
Set textbox element

### ISSUE THREAD

**Issue by dtturcotte** [rexrainbow/phaser3-rex-notes#361]
Hello, I'm using your awesome [RexUI textbox](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-textbox/#get-element). I initialize the "background" property to a rounded rectangle. But at some point in my game, I want to set a texture to the textbox background. The rounded rectangle doesn't have a texture property, so I figured the best way to do that would be set the "background" to an image object. The textbox, however, doesn't seem to have a `setElement(...)` method, only a `getElement(...)` method. Any suggestions?

**Comment by rexrainbow** [comment]
Remove background child then add a new one. See this new [demo](https://codepen.io/rexrainbow/pen/abQdxmQ), line 55-63.
`sizer.removeBackground` method is existed but not in document, will add it to document.

**Comment by dtturcotte** [comment]
Thank you!
