### ISSUE TITLE
ScrollTo element in scrollable container, similar to HTML <a> tag

### ISSUE THREAD

**Issue by dtturcotte** [rexrainbow/phaser3-rex-notes#362]
Hi, I'm looking for functionality similar to anchor tag in your [scrollablePanel](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-scrollablepanel/#scroll-content). Basically, I need the scrollable panel to automatically scroll down to a textElement added using "this.scene.rexUI.add.BBCodeText(...)". I've tried doing this manually by getting the `y` coordinate of the target scrollTo element and getting a scroll percentage based on `targetY/scrollablePanel.height`,  but this doesn't get me exactly where I want. Just like anchor tag, I want it to scroll to where the target element begins, just to reveal the full target element, and not past it to show content below.

```
		let scrollToElement = this.todoTextElements.find((t) => t.isCurrentMission)
		let scrollToElementY = scrollToElement.textElement.y + scrollToElement.textElement.height
		let contentHeight = this.todoTextElements.reduce((totalHeight, currentElement) => {
			return totalHeight + currentElement.textElement.height
		}, 0)
		let scrollToPercentage = scrollToElementY / contentHeight

		leftScrollablePanel = this.updateScrollablePanel(
			leftScrollablePanel,
			this.todoTextElements.map((t) => t.textElement),
			scrollToPercentage,
			true
		)
```

Which calls:

```
	updateScrollablePanel(scrollablePanel: any, elementArr: Array<any>, scrollToY: number, usePadding: boolean) {
		let sizer = scrollablePanel.getElement('panel')
		sizer.clear(true)
		elementArr.forEach((element) => {
			sizer.add(element)
		})
		scrollablePanel.layout()

		scrollablePanel.setT(scrollToY, true)

		return scrollablePanel
	}
```
In this example: it should scroll to "Objective: Scenario 4" so that it's fully visible:
<img width="285" alt="Screen Shot 2023-06-17 at 1 49 04 PM" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/4550049/49392cb9-ea23-41f3-a7c4-106bfe84d420">

In the result of the code, however, it's scroll way past it:
<img width="294" alt="Screen Shot 2023-06-17 at 1 48 44 PM" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/4550049/c374f1f0-4977-41c7-addf-cd8df2bdd7cc">

**Comment by rexrainbow** [comment]
Add method `scrollToChild` to align top/left of child to top/left of panel. See this [demo](https://codepen.io/rexrainbow/pen/ZEmWwaN), line 41.

**Comment by dtturcotte** [comment]
I was hoping for it to only scroll down to the element to reveal it, but not past it. So, for example, if scrolling to item-20 (`panel.scrollToChild(panel.getByName('item-20', true));)`, it would look like this: 

<img width="107" alt="Screen Shot 2023-06-18 at 1 36 05 PM" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/4550049/8105ec44-e576-40ea-8559-2128e771644d">

**Comment by rexrainbow** [comment]
Here is the result in my browser (chrome && firefox) : 
![圖片](https://github.com/rexrainbow/phaser3-rex-notes/assets/817962/8381543e-42f5-4553-a3c0-5a5834118c80)

It will *align top/left of child to top/left of panel*. I am not idea why the `item-20` is at bottom of scrollablePanel

**Comment by rexrainbow** [comment]
Add `align` parameter to [`scrollToChild` method](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-scrollablepanel/#scroll-to-child). Now `item-20` will be scrolled at bottom of panel in this demo.

**Comment by dtturcotte** [comment]
Thank you. Please let me know when you're able to update the `npm` package. Hopefully soon?

**Comment by rexrainbow** [comment]
NPM package will be upgraded at end of this month.

**Comment by dtturcotte** [comment]
Re-opening this. I'm trying to use scroll to child, but with a `Phaser.GameObjects.Container`. The `scrollToChild` works with anything that's not a container, but I need it to work with a container. I've set the size of my containers to the total size of their contents, but I still get this error.

"ScrollToChild.js:60 Uncaught (in promise) TypeError: child.getTopLeft is not a function
    at RexUIScrollablePanel.AlignChild (ScrollToChild.js:60:56)
    at RexUIScrollablePanel.ScrollToChild [as scrollToChild] (ScrollToChild.js:9:24)
    at RexUIScrollablePanel.update (rexUIScrollablePanel.ts:151:1)
    at QuestStatusUI.addMissionJourney (questStatusUI.ts:229:1)
    at new QuestStatusUI (questStatusUI.ts:22:1)
    at WatchComponent.addSubUi (watchComponent.ts:91:1)
    at WatchComponent.addUi (watchComponent.ts:122:1)
    at new WatchComponent (watchComponent.ts:21:1)
    at GUIScene.addComponents (guiScene.ts:709:1)
    at GUIScene.addUi (guiScene.ts:719:1)"

Referencing the source code, it's happening here

```
        default:
            var dTop = scrollableBlock.top - child.getTopLeft().y; <---------- ERROR HERE
            var dBottom = scrollableBlock.bottom - child.getBottomLeft().y;
            if ((dTop <= 0) && (dBottom >= 0)) {
                delta = 0;
            } else {
                delta = (Math.abs(dTop) <= Math.abs(dBottom)) ? dTop : dBottom;
            }
            break;
        }
```

Can you help?

**Comment by dtturcotte** [comment]
The way I've tried to solve this is to manually add the required methods: see the forked `scrollTo` rexUI demo [here](https://codepen.io/dtturcotte/pen/dyEGwgx).

I'd love a better solution though.

```
    for (var i = 0; i < 50; i++) {
        var name = `item-${i}`;
        var label = scene.rexUI.add.label({
            background: scene.rexUI.add.roundRectangle({
                color: COLOR_PRIMARY
            }),
            text: scene.add.text(0, 0, name),
            space: { left: 10, right: 10, top: 10, bottom: 10 },
            name: name,
        });

        let container = scene.add.container(0, 0, label).setSize(label.width, label.height);

        container.getTopLeft = function (output) {
            if (!output) {
                output = new Phaser.Math.Vector2();
            }
            output.x = this.x - this.displayWidth * this.originX;
            output.y = this.y - this.displayHeight * this.originY;
            return output;
        };

        container.getBottomLeft = function (output) {
            if (!output) {
                output = new Phaser.Math.Vector2();
            }
            output.x = this.x - this.displayWidth * this.originX;
            output.y = this.y + this.displayHeight * (1 - this.originY);
            return output;
        };

        container.name = name;
        panel.add(container, { expand: true });
    }
```

**Comment by rexrainbow** [comment]
Sorry for missing this thread.
I had rewrote some logic of scrollToChild method, to [avoid using built-in method to get top-left/bottom-left position](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/templates/ui/scrollablepanel/ScrollToChild.js#L48). Thus you don't have to add extra method at all.
NPM package will be upgraded at end of this month.
