### ISSUE TITLE
Adding callbacks to textbox start, stop, etc

### ISSUE THREAD

**Issue by dtturcotte** [rexrainbow/phaser3-rex-notes#364]
Hello, I need to pass in a custom callback to textbox start, e.g., `textBox.start(text, 50, () => { doSomething() } )`

I cannot rely on event properties (e.g., `on('complete')`) etc since I set those earlier when the textbox is created.

This would be helpful for `stop()`, `pause()` and `resume()` as well. 

Thank you!

**Comment by rexrainbow** [comment]
Add `pause`, `resume` events in latest submit. Fired when typing paused, or typing resume.
`start` event was added previously.
