### ISSUE TITLE
Show all text immediately in textbox

### ISSUE THREAD

**Issue by dtturcotte** [rexrainbow/phaser3-rex-notes#365]
I'd like certain times in my game to show dialogue immediately. I've tried `textBox.start(...)` then`textBox.stop(true);` immediately after, and typingSpeed 1 for `textBox.start(content, 1);` (`0` doesn't work) but it still shows a flicker and any custom fonts are messed up and revert to default game font. 

Can you add a method to just take text as input and simply display it, without the typewriter effect?

Thank you for all of your hard work!

**Comment by rexrainbow** [comment]
Do you mean that typing all characters include last page immediately?

**Comment by rexrainbow** [comment]
Add `textBox.showLastPage()` method, to stop typing and show content of last page. ([demo](https://codepen.io/rexrainbow/pen/GRwMrrP))
`textBox.stop(true)` is used to stop typing and show content of current page.

Please get latest minify file of rexUI.
