### ISSUE TITLE
Add image support for dialog

### ISSUE THREAD

**Issue by dtturcotte** [rexrainbow/phaser3-rex-notes#366]
Hello, I know I've been requesting many features lately. I thank you for your support.

Can you add image support for https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-dialog/? I want to be able to use the popup functionality, but also add an image. 

This means that when the popup shows, the title is at the top, followed by text content, followed by an image. The use case is to show if a player picked up an item.

Thanks!

**Comment by dtturcotte** [comment]
For now, I am setting content to image, and description to text, but I think this is a hacky workaround because the property its receiving should be more descriptive.

**Comment by rexrainbow** [comment]
Child of dialog like `content` could be a [label](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-label/), or a [sizer](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-sizer/), or any kind of sizer. Then designer can place image with text into `content` child, or `description` child, ... etc.
