### ISSUE TITLE
Failed to load in Phaser 3.60 version.

### ISSUE THREAD

**Issue by letmegoforit** [rexrainbow/phaser3-rex-notes#367]
Failed to load in Phaser 3.60 version:

![image](https://github.com/rexrainbow/phaser3-rex-notes/assets/6482545/31fe0445-d331-408b-84ec-e29830083935)

![image](https://github.com/rexrainbow/phaser3-rex-notes/assets/6482545/46eee531-58f0-424b-82f0-98002e68ce99)

**Comment by rexrainbow** [comment]
[This test demo](https://codepen.io/rexrainbow/pen/YMyBom) uses phaser3.60 and works well, please check your phaser3 version again.
