### ISSUE TITLE
Node 16 Support?

### ISSUE THREAD

**Issue by scottcanoni** [rexrainbow/phaser3-rex-notes#368]
The new version of phaser-rex-notes now requires node 18+ because of the dependency `marked` which has this listed in its package.json:

```
"engines": {
    "node": ">= 18"
  }
```

Anyway around this?  I am not even using the markdown feature of the event sheets.  Thank you kindly for your time.

**Comment by rexrainbow** [comment]
I used minify file of marked module internally before, but had not removed the dependence in package.json. Now it has been removed.
Will upgrade npm package at end of this month.

**Comment by scottcanoni** [comment]
Awesome, thanks, I can help confirm.
