### ISSUE TITLE
rexVirtualJoyStick - Prevent snapping back to 0?

### ISSUE THREAD

**Issue by nt294** [rexrainbow/phaser3-rex-notes#369]
Is there a way to prevent the joystick snapping back to zero? in other words, increase the area that the joystick can be moved around in?

**Comment by rexrainbow** [comment]
I can create a test for increasing the area (base on `radius` input parameter) later. 
However, I don't know why *increase the area* can *prevent the joystick snapping back to zero*. Could you explain *prevent the joystick snapping back to zero* more detail? An image might be better, imo.

**Comment by nt294** [comment]
Sorry, I should of been more clear - what I mean is when the joystick returns to the centre it 'snaps back' in the sense of the force and angle snapping back to zero when it comes under a certain threshold. 

![joystickGif](https://github.com/rexrainbow/phaser3-rex-notes/assets/79095109/1d95ff0c-ae8c-4cdc-b5ab-755bd06fd21b)

**Comment by rexrainbow** [comment]
Might try to set `forceMin` input parameter to `0` ( see [create instance](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/virtualjoystick/#create-instance)), then you can have a small force value.

**Comment by nt294** [comment]
Thanks, that works nicely
