### ISSUE TITLE
pages的demo字体很大

### ISSUE THREAD

**Issue by cristlee** [rexrainbow/phaser3-rex-notes#37]
> https://codepen.io/rexrainbow/pen/vPWzBa

如图

<img width="847" alt="屏幕截图 2019-05-30 17 25 45" src="https://user-images.githubusercontent.com/1849042/58623134-dac31480-82ff-11e9-9649-2f67496cb7ee.png">

**Comment by rexrainbow** [comment]
Fixed, thanks for this bug report.
The root cause is, I added the text size expanding feature yesterday, but did not test that feature well. 
Now only set `expandTextWidth`, `expandTextHeight` parameter can expand text size, in Label object.
