### ISSUE TITLE
update functions missing from IStateConfig type in FSMBase.d.ts

### ISSUE THREAD

**Issue by wayfu** [rexrainbow/phaser3-rex-notes#373]
Only specifies enter and exit atm...

**Comment by rexrainbow** [comment]
type of `update`, `preupdate`, `postupdate` parameters are defined in [FSM.d.ts](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/plugins/logic/fsm/FSM.d.ts#L8-L10).
[FSMBase.js](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/plugins/logic/fsm/FSMBase.js) (FSMBase.d.ts) is a phaser independent class (i.e. can be used without phaser3), 
[FSM.js](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/plugins/logic/fsm/FSM.js) (FSM.d.ts) is designed for phaser (scene's update/preupdate/postupdate).

**Comment by rexrainbow** [comment]
Fixed in latest commit
