### ISSUE TITLE
Lock joystick on horizontal axis

### ISSUE THREAD

**Issue by Sulorb** [rexrainbow/phaser3-rex-notes#375]
Hello,

After modifying the source code to prevent the function setVector() with a y axis different than 0 in vain, I'd like to ask **how could i lock the joystick axis horizontally?**

I am using the joystick parameter `dir: 'left&right'`
But if the user can visually move the joystick up & down he may not understand why if he can only move the sprite left or right.

Thanks.

**Comment by rexrainbow** [comment]
Feature added, please test it on this [demo](https://codepen.io/rexrainbow/pen/oyqvQY), change `dirMode` to `'up&down'`, or `'left&right'`.
NPM package will be upgraded at end of this month.

**Comment by Sulorb** [comment]
This is awesome. Thank you so much, for this quick answer and for all your work that helps so many people. 🙏
