### ISSUE TITLE
dynamic set card face

### ISSUE THREAD

**Issue by pkl-kirito** [rexrainbow/phaser3-rex-notes#376]
Hi, I like your plugin, I try to use [perspective-card](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/perspective-card/). But how to change card face to new `{key, frame}` before `card.flip.flipRight();`

**Comment by rexrainbow** [comment]
Feature added : Can change texture by `card.frontFace.setTexture(key, frame)` method. [Demo](https://codepen.io/rexrainbow/pen/abQragB)
NPM package will be upgraded at end of this month.

**Comment by rexrainbow** [comment]
Could you post an image or a video to explain this *card perspective* more detail?

**Comment by pkl-kirito** [comment]
![image](https://github.com/rexrainbow/phaser3-rex-notes/assets/133939547/9b65c126-32eb-4f55-bf4e-10e854dc4afb)
@rexrainbow something like this

**Comment by rexrainbow** [comment]
A workaround solution is to render game scene on render scene using perspective-image game object. [Demo](https://codepen.io/rexrainbow/pen/BavBdgw).
