### ISSUE TITLE
Monopoly not finding the path

### ISSUE THREAD

**Issue by pedroddomingues** [rexrainbow/phaser3-rex-notes#378]
Hi! I don't know exactly what I'm doing wrong.

I've tried to mix the monopoly example with the tilemap one.
No matter how I create the board (with the tilemap or mannualy above the tilemap) it doesn't change the direction, so it only searchs the path for face direction of ChessA.

This is the running example: https://morram-vermes.vercel.app/phaser

This is te source code: https://github.com/pedroddomingues/morram-vermes 

Thanks!

**Comment by rexrainbow** [comment]
Please provide a simplest, runnable test code for your issue. A project folder with many files will take too much time from setup to run and debug.

**Comment by pedroddomingues** [comment]
Sorry, the source code url was wrong, I meant the [page url.](https://github.com/pedroddomingues/morram-vermes/blob/master/src/app/phaser/page.tsx). 

Here is a working codepen: https://codepen.io/pedroddomingues/pen/dywPdRP
Click on map to move in path.

**Comment by rexrainbow** [comment]
As you see this [demo](https://codepen.io/rexrainbow/pen/WWJxZL), board only contains moveable tiles, yo can replace line 39 by `board.removeChess(tile);`, to keep moveable tiles only.
If your requirement is keeping all tiles on board, i.e. the moveable path might be created during runtime. I could try to add that feature.

**Comment by rexrainbow** [comment]
rexBoard (monopoly) has been updated, now invalid cost (`null`, or `undefined`) will be discarded from monopoly path.

```js
            if (tile.index === 113) {
                var cost = ((tileXY.x === 2) && (tileXY.y === 5)) ? -1 : 1;
                scene.rexBoard.add.shape(board, tileXY.x, tileXY.y, 2, 0xffffff, 0.4).setOrigin(0).setData('cost', cost);
            } else {
                scene.rexBoard.add.shape(board, tileXY.x, tileXY.y, 2, 0xffffff, 0.1).setOrigin(0).setData('cost', undefined);
            }
```

Also return `-1` at the path end tile (2,5).

NPM package will upgraded at end of this month.

**Comment by pedroddomingues** [comment]
This is perfect @rexrainbow ! Thank you very much.

Although creating path during runtime can be an awesome feature, it's not necessary for my case.

Congratulations on this project!

**Comment by rexrainbow** [comment]
Both solutions (`removeChess()`, or `setData('cost', undefined)` will work in latest minify rexBoard file.
