### ISSUE TITLE
[img] not working with rexUiTextbox typewriter.

### ISSUE THREAD

**Issue by dtturcotte** [rexrainbow/phaser3-rex-notes#379]
I'm following [this](https://codepen.io/rexrainbow/pen/yLKNVaW) guide for adding inline bbcode images in conjunction with rexUiTextbox.

I preload the image using "this.load.image('bolt', 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/assets/images/bolt.png')"

I noticed that the image does not appear if I use typewriter effect, but does appear if I just create a bbcode text element and display the text directly. Is this a limitation of [img] and rexUiTextbox?

If textbox doesn't support images currently, is there a way you can add support?

**Comment by rexrainbow** [comment]
Here is a [demo](https://codepen.io/rexrainbow/pen/zYyxBOx) of typing on bbcodetext with img tag. Works fine.

**Comment by dtturcotte** [comment]
Put the text as "[img=key] Find the open the door." The key will not appear. Is it because it's hidden somehow by the icon?

**Comment by rexrainbow** [comment]
It seems a bug of textyyping behavior, will fix it later.

**Comment by dtturcotte** [comment]
Thank you! Please let me know when it's resolved.

**Comment by rexrainbow** [comment]
Bug fixed, please grab latest minify files. NPM package will be upgraded at end of this month.

**Comment by rexrainbow** [comment]
NPM package upgraded.
