### ISSUE TITLE
"hidden" objects added to scrollable panel (both fixWidthSizer and Sizer) reappear on scroll

### ISSUE THREAD

**Issue by dtturcotte** [rexrainbow/phaser3-rex-notes#380]
I've added several rexUI bbcode text elements to a scrollable panel.

I hide one of the text elements using `bbcodeText.setVisible(false)`. The text element within the scrollablePanel immediately hides in as expected.

When I scroll, the bbcodeText element reappears. 

I've tried finding the element using `on('scroll'` then sifting through the panel's children, but cannot locate the text elements.

How can I prevent this unwanted behavior from happening?

**Comment by rexrainbow** [comment]
- Set child game object to invisible : `parentSizer.setChildVisible(child, visible)`  [ref](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/containerlite/#visible). Parent does not know (does not check child's properties) if child is set to invisible.
- Hide child and don't layout this child : `scene.rexUI.hide(child)` [ref](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-overview/#showhide). Invisible child will be layout with other children if not *hide*

**Comment by dtturcotte** [comment]
@rexrainbow Hi, I've finally gotten back to this. If I use `parentSizer.setChildVisible(child, false)`, or a workaround such as `child.setAlpha(0)`, it hides, and keeps the child hidden even on scroll, but the children still take up space in the layout:

**Not hidden:**

<img width="234" alt="Screen Shot 2023-10-27 at 4 30 33 PM" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/4550049/4c6c6983-ee5a-459f-a555-76e01d8d646e">

**Hidden:**

<img width="233" alt="Screen Shot 2023-10-27 at 4 29 27 PM" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/4550049/a20ff934-54aa-4195-b592-f95d2f27e763">

But the elements should collapse to what's visible.

**Comment by rexrainbow** [comment]
Please see my above post.

Hide child and don't layout this child : `scene.rexUI.hide(child)` [ref](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-overview/#showhide). Invisible child will be layout with other children if not hide
