### ISSUE TITLE
Property 'Board' does not exist on type 'typeof BoardPlugin'.

### ISSUE THREAD

**Issue by songyukino1** [rexrainbow/phaser3-rex-notes#382]
I am writing a Board class in TypeScript, and following the example, I have written the following code. However, the italicized and bold part is being flagged with the error message mentioned in the title. What could be the issue?
`
import BoardPlugin from "phaser3-rex-plugins/plugins/board-plugin";
class MyBoard extends BoardPlugin.**_Board_**.Board {

}
`

**Comment by rexrainbow** [comment]
```js
class MyBoard extends RexPlugins.Board.Board {
}
```
See [this note](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board/#custom-class)

**Comment by rexrainbow** [comment]
Or [import Board class directly](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board/#import-class).

**Comment by songyukino1** [comment]
Thank you, I solved it by directly importing.
