### ISSUE TITLE
How to set a fixed width and scale a board?

### ISSUE THREAD

**Issue by songyukino1** [rexrainbow/phaser3-rex-notes#385]
I want to make the board have a fixed width, such as 600px, and then scale the board to fill the entire x-axis because I have a preset screen width of 600px. How can I achieve this?

**Comment by rexrainbow** [comment]
Board plugin series does not support this feature directly. Set `x`, `y`, `cellWidth`, `cellHeight` parameters in [Quad](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board-quadgrid/), or [Hexagon](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/board-hexagongrid/)
