### ISSUE TITLE
scene.rexUI.add.label is broken

### ISSUE THREAD

**Issue by MartinPlascencia** [rexrainbow/phaser3-rex-notes#396]
The last update broke some functions of the rexUI script.
When trying to create a label it show this error, I need access to the last version, and I won´t trust using online versions again.
![Captura](https://github.com/rexrainbow/phaser3-rex-notes/assets/10503306/d897ba5c-f56f-4162-a986-ee188d87f594)

**Comment by MartinPlascencia** [comment]
I updated the game locally using a prior version and it's working.

**Comment by rexrainbow** [comment]
The last commit is for this [demo](https://codepen.io/rexrainbow/pen/YzBOYgK), to change children's alignment mode. It works fine in my environment.

Anyway, I will rewrite some logic to prevent that error message.

**Comment by rexrainbow** [comment]
New version submitted, please try that online minify file again.

**Comment by MartinPlascencia** [comment]
I tested and now it shows this error when using "scene.rexUI.add.label", as I said prior version is working so I'll keep that one for now.
This is the code I am using, I am not using any new feature so I think I'll leave as it is.
![image](https://github.com/rexrainbow/phaser3-rex-notes/assets/10503306/7c39b124-4dc0-4ec1-9be0-4285a0025e20)

![Captura](https://github.com/rexrainbow/phaser3-rex-notes/assets/10503306/cc495fec-7395-4094-849c-74b4d0feb38d)

**Comment by rexrainbow** [comment]
Got it, it is a Label without Icon and Text elements.
I update another new version, please try again.

**Comment by MartinPlascencia** [comment]
It is working now, thank you for the support.

**Comment by rexrainbow** [comment]
Today will upgrade npm package, lucky that we fix this bug before that.
