### ISSUE TITLE
Wrong touch with Virtual Joystick using the camera (PHASER 3)

### ISSUE THREAD

**Issue by convitesamigo** [rexrainbow/phaser3-rex-notes#399]
Hello! I'm using **phaser 3.70.0** together with its VIRTUAL JOYSTICK plugin.

The Virtual JoyStick works perfectly as long as I'm within the limits (W: 0-600px and H: 0-800px).

But when the player leaves this limit and the **camera** starts following him, the joystick's drag button starts to behave wrongly. You can't drag it anywhere, it goes to a random position.

**Comment by rexrainbow** [comment]
Please provide a simplest, runnable test code for demonstrate this use-case.

**Comment by convitesamigo** [comment]
index.html: 
  `
  <!DOCTYPE html>
  <html>
  <head>
	  <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <title>Test</title>
  </head>
  <body>
	  <script type="text/javascript" src="phaser.js"></script>
	  <script type="text/javascript" src="rexvirtualjoystickplugin.min.js"></script>
	  <script type="text/javascript" src="game.js"></script>
  </body>
  </html>
  `
  game.js
  `
  var config = {
    type: Phaser.AUTO,
    backgroundColor: 0xcccccc,
    width: window.innerWidth,
    height: window.innerHeight,
    scene: {
        preload: preload,
        create: create,
        update: update
    },
    scale: {
        mode: Phaser.Scale.LANDSCAPE,
        mode: Phaser.Scale.RESIZE,
        autoCenter: Phaser.Scale.CENTER_BOTH
    },
    render: {
        pixelArt: true,
    },
    physics: {
        default: 'matter',
        matter: {
            gravity: { x: 0, y: 0 },
            debug: true
        }
    },
    plugins: {
    global: [
      {
        key: "VirtualJoystick",
        plugin: rexvirtualjoystickplugin,
        mapping: "joystickPlugin"
      }
    ]
  }
};

var game = new Phaser.Game(config);

function preload() {    
    console.log(this)

    this.load.image('ball', 'ball.png');
}



function create() {

    this.player = this.matter.add.image(100, 100, 'ball');

    this.cameras.main.setBounds(0, 0, 13000, 13000);
    this.cameras.main.startFollow(this.player);

    joystick = this.joystickPlugin.add(this, {
        x: 150,
        y: 450,
        radius: 100,
        fixed: true,
        base: this.add.circle(200, 200, 80, 0x6666ff),
        thumb: this.add.circle(0, 0, 30, 0x0011ff)
      });

}


let lastUpdateTime = 0;
function update(time, delta) {

    this.player.setVelocity(0);
    //player.setAngle(0)

    if(joystick.up){
        this.player.setVelocityY(-3);
    }
    if(joystick.down){
        this.player.setVelocityY(3);
    }
    if(joystick.left){
        this.player.setVelocityX(-3);
    }
    if(joystick.right){
        this.player.setVelocityX(3);
    }

}

  `

**Comment by convitesamigo** [comment]
Here is the example code.

`var config = {
    type: Phaser.AUTO,
    backgroundColor: 0xcccccc,
    width: window.innerWidth,
    height: window.innerHeight,
    scene: {
        preload: preload,
        create: create,
        update: update
    },
    scale: {
        mode: Phaser.Scale.LANDSCAPE,
        mode: Phaser.Scale.RESIZE,
        autoCenter: Phaser.Scale.CENTER_BOTH
    },
    render: {
        pixelArt: true,
    },
    physics: {
        default: 'matter',
        matter: {
            gravity: { x: 0, y: 0 },
            debug: true
        }
    },
    plugins: {
    global: [
      {
        key: "VirtualJoystick",
        plugin: rexvirtualjoystickplugin,
        mapping: "joystickPlugin"
      }
    ]
  }
};
var game = new Phaser.Game(config);`

`function preload() {    
    this.load.image('ball', 'ball.png');
}`

`function create() {

    this.player = this.matter.add.image(100, 100, 'ball');

    this.cameras.main.setBounds(0, 0, 13000, 13000);
    this.cameras.main.startFollow(this.player);

    joystick = this.joystickPlugin.add(this, {
        x: 150,
        y: 450,
        radius: 100,
        fixed: true,
        base: this.add.circle(200, 200, 80, 0x6666ff),
        thumb: this.add.circle(0, 0, 30, 0x0011ff)
      });

}`

`function update(time, delta) {

    this.player.setVelocity(0);
    //player.setAngle(0)

    if(joystick.up){
        this.player.setVelocityY(-3);
    }
    if(joystick.down){
        this.player.setVelocityY(3);
    }
    if(joystick.left){
        this.player.setVelocityX(-3);
    }
    if(joystick.right){
        this.player.setVelocityX(3);
    }

}
`

**Comment by convitesamigo** [comment]
When the camera starts following the player, the joystick button behaves incorrectly.

**Comment by convitesamigo** [comment]
> Forneça um código de teste executável mais simples para demonstrar este caso de uso.

LINK:
   https://convitesamigo.github.io/virtualjoystckerr/

**Comment by convitesamigo** [comment]
> Please provide a simplest, runnable test code for demonstrate this use-case.

https://convitesamigo.github.io/vjoystick/

**Comment by convitesamigo** [comment]
Very good, problem solved!
Worked perfectly. Now I can finish my multiplayer game. **Thank you very much!**
