### ISSUE TITLE
Wrong at typescript: this.rexUI.add.confirmActionButton({..., confirmDialog: {style: dialogStyle,content: dialogContent,},})

### ISSUE THREAD

**Issue by chaunguyen125** [rexrainbow/phaser3-rex-notes#401]
I found in your code at confirmdialog that 'confirmActionButton: typeof ConfirmActionButtonFactory;'. But, it was defined 'interface IResetChoiceDisplayContentConfig extends Label.IResetDisplayContentConfig {
        value?: any;
  }'. It makes an issue at style and content. I try to fix and I saw that if I change interface IResetChoiceDisplayContentConfig extends Label.IResetDisplayContentConfig {
        value?: any;
  } to interface IResetChoiceDisplayContentConfig extends IResetDisplayContentConfig {
        value?: any;
  }', It work. Please check and noti me. Thank you!!!!!

**Comment by rexrainbow** [comment]
Type of`confirmDialog` and `confirmActionButton` ( https://github.com/rexrainbow/phaser3-rex-notes/blob/master/templates/ui/ui-plugin.d.ts#L142-L143 ) seems correct. Could you point out the wrong class of type define more precisely?

**Comment by rexrainbow** [comment]
I will add a test case of creating ConfirmActionButton in typescript later, to see the missing type define.

**Comment by rexrainbow** [comment]
Update typedefine in [latest commit](https://github.com/rexrainbow/phaser3-rex-notes/commit/6f12f8647c7f363d0f427e215632a568e56efc8d), ([test code](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/ui-confirmactionbutton/test-ts.ts))
NPM package will upgrade at end of this month.

**Comment by chaunguyen125** [comment]
Thanks for your help!!! You and rexUI are really cool.
