### ISSUE TITLE
typescript texttyping.d.ts debug

### ISSUE THREAD

**Issue by yongzheng7** [rexrainbow/phaser3-rex-notes#403]
![image](https://github.com/rexrainbow/phaser3-rex-notes/assets/42328880/87262898-7148-42f4-978c-5e27d1c42909)
![image](https://github.com/rexrainbow/phaser3-rex-notes/assets/42328880/c5847f9f-7dce-4c17-9fad-d034b26a001d)

**Comment by rexrainbow** [comment]
Add these type definitions in [this commit](https://github.com/rexrainbow/phaser3-rex-notes/commit/8c057bc75995f4aff73136c0534591e0bcfe8d27).
BTW, `text`, `typingIdx`, `elapsed` are designed for internal usage.
