### ISSUE TITLE
Bugs with textpage-plugin , texttyping-plugin.js and bbcodetext-plugin 

### ISSUE THREAD

**Issue by lilhuy0405** [rexrainbow/phaser3-rex-notes#405]
i use these three plugins textpage-plugin , texttyping-plugin.js and bbcodetext-plugin to make a typing text effect the code worked well but few days ago, all typing text with bb rex code is broken. Even the example on code pen is broken. Instead of showing my text it showing a random image objects of my game
- The rexBBCodeText example link here: https://codepen.io/rexrainbow/pen/OZbOyg. You can see it not showing the text
![image](https://github.com/rexrainbow/phaser3-rex-notes/assets/63459413/5356e221-fdfa-454d-b536-a703c58f848a)
Any ones have same problem ? And how can i fix it or any kind of workaround ?

**Comment by rexrainbow** [comment]
https://github.com/rexrainbow/phaser3-rex-notes/issues/404#issuecomment-1960963830

**Comment by lilhuy0405** [comment]
> [#404 (comment)](https://github.com/rexrainbow/phaser3-rex-notes/issues/404#issuecomment-1960963830)

Thanks i've update my phaser to version 3.80 and it works like a charm. I'll close this issue.
