### ISSUE TITLE
Can I use image or sprite for checkboxes/radio

### ISSUE THREAD

**Issue by chaunguyen125** [rexrainbow/phaser3-rex-notes#411]
If I follow the [demo](https://codepen.io/rexrainbow/pen/PowMEjX), can I use image, sprite and so on for bullets of list instead?

**Comment by rexrainbow** [comment]
Yes you can. 

- Create image game object at line 78.
- `button.getElement('icon')` (line 38) will return this image game object.

**Comment by chaunguyen125** [comment]
Yeah I love that. Thank you!!!
