### ISSUE TITLE
Type Scene Parameter with typescript

### ISSUE THREAD

**Issue by ngodinhdai286** [rexrainbow/phaser3-rex-notes#416]
I make a scrollablePanel and I create function createGrid to create child for scrollablePanel with Typescript
But I don't know exactly what the type for the scene parameter, I tried Phaser.Scene but I warned me 
Could you help me declear type for scene parameter
![code](https://github.com/rexrainbow/phaser3-rex-notes/assets/74429890/d49f0b59-8999-4eb2-8c50-a21c4ff6b0f1)

**Comment by rexrainbow** [comment]
Might add define of `rexUI` member like that :

```typescript
import 'phaser';
import RexUIPlugin from 'phaser3-rex-plugins/templates/ui/ui-plugin.js';
declare module 'phaser' {
  interface Scene {
    rexUI: RexUIPlugin;
  }
}
```
