### ISSUE TITLE
How can I completely remove scrollablepanel

### ISSUE THREAD

**Issue by ngodinhdai286** [rexrainbow/phaser3-rex-notes#419]
I am using Scrollable Panel. but when I call remove removeAllBackgrounds(true) and removeAll(true), the scrollableBlock and scrollablePanel is not be removed, still overthere

**Comment by rexrainbow** [comment]
Try `scrollablepanel.destroy()`

**Comment by ngodinhdai286** [comment]
I have used destroy(), but it is still not removed

**Comment by rexrainbow** [comment]
[Test case](https://codepen.io/rexrainbow/pen/rNvKdqg), disable/enable line 25 to see the result of destroy()
