### ISSUE TITLE
GridTable Dynamic width each column

### ISSUE THREAD

**Issue by coxsy1** [rexrainbow/phaser3-rex-notes#42]
can you tell me how to, resize each column each column.. please

**Comment by rexrainbow** [comment]
Currently, the cell width is a fixed value in scroll-vertical mode.
In scroll-horizontal mode ( set `scrollMode`  parameter to `1` in config object), you can set cell width via
```javascript
gridTable.setCellWidth(cellIdx, width);
```

It seems that I missed this method in document, I will add it later.
```

**Comment by rexrainbow** [comment]
Grid table has 2 scroll modes:
- scroll mode = `vertical` : Changing cell width is not supported now.
- scroll mode = `horizontal` : Changing cell width via 
```javascript
table.setCellWidth(cellIndex, cellWidth).updateTable(true)
```
[Here](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/gridtable/vary-cell-width.js#L47) is a test case.

**Comment by coxsy1** [comment]
var gridTable = this.rexUI.add.gridTable({tableoption}); 
i am using this method.. but now im confusing how to call table inside gridTable variable...?

**Comment by rexrainbow** [comment]
In this case,
```javascript
var gridTable = this.rexUI.add.gridTable({tableoption});
```
use `gridTable.setCellWidth(cellIndex, cellWidth).updateTable(true)`

**Comment by rexrainbow** [comment]
Try [scroll-able panel](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-scrollablepanel/) ui plugin if you need more flexible table. [Here](https://codepen.io/rexrainbow/pen/YMyBom) is a demo of scroll-able panel

**Comment by coxsy1** [comment]
Thank you so much.. I'll check it out.. Heheheh..

**Comment by rexrainbow** [comment]
Issue solved.
