### ISSUE TITLE
RexCutJigsawImage is not working on iPad

### ISSUE THREAD

**Issue by timoKarin** [rexrainbow/phaser3-rex-notes#420]
Hello,
I created a Jigsaw Puzzle game using the RexCutJigsawImage plugin, after I finished my game I realized there is an issue with the edges on iPads, where some of the pieces don't get the correct edges...

![IMG_50BCBE6E8348-1](https://github.com/rexrainbow/phaser3-rex-notes/assets/16371018/06e8d743-424a-42ba-b501-ba49a4b09852)

Any ideas what could cause this?

**Comment by rexrainbow** [comment]
Bug fixed, please get latest version of minify file. NPM package will upgrade at end of this month.

**Comment by timoKarin** [comment]
Thank you for fixing this so fast! I'm impressed and will keep using your awesome plugins for Phaser :)
