### ISSUE TITLE
Does the text in this component support scrolling beyond the height of the container instead of pagination

### ISSUE THREAD

**Issue by cy920820** [rexrainbow/phaser3-rex-notes#424]
https://codepen.io/rexrainbow/pen/GRYLrje

**Comment by rexrainbow** [comment]
Using [TextArea](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-textarea/), [demo](https://codepen.io/rexrainbow/pen/JzBZzy)

**Comment by cy920820** [comment]
But I want to use components like dialog boxes, can I implement them

**Comment by rexrainbow** [comment]
TextBox does not support scrolling content feature. It is designed for typing page by page.

**Comment by rexrainbow** [comment]
For typing on textArea, it is another kind of use case, can you describe it more detail?

**Comment by cy920820** [comment]
I need an interactive approach like TextBox Demo, but I don't want to use pagination. I want it to scroll and output as the word by word content increases

This is a bit like CSS attributes, overflow: auto

**Comment by rexrainbow** [comment]
For example, TextBox has 4 lines, once typing at end of 4th line, it will move up 1 line = 2nd, 3rd, 4th lines + an empty new line for typing 5th lines.

```
1st line
2nd line
3rd line
4th line
```
-->
```
2nd line
3rd line
4th line
... typing 5th line...
```

Do I get your requirement?

**Comment by rexrainbow** [comment]
I don't get your requirement. Sorry. Can you explain about word animation?

**Comment by cy920820** [comment]
I actually want to combine these two demos

**Comment by cy920820** [comment]
It's just an AVG conversation guide, and then the user and NPC will have a conversation. The NPC will put the reply into the dialogue box, and the text content of this dialogue box is uncertain, completely depending on the server's return

**Comment by rexrainbow** [comment]
Since you had [implemented this feature](https://github.com/rexrainbow/phaser3-rex-notes/issues/425#issuecomment-2046323384), issue closed.
