### ISSUE TITLE
BBCodeText background corner radius becomes square on editing

### ISSUE THREAD

**Issue by charlie-says** [rexrainbow/phaser3-rex-notes#432]
Minor issue, I was just implementing an editable textfield, and noticed that when I applied rounded corners to the background, this became square when you were editing the text.

**Comment by rexrainbow** [comment]
Text-edit will place an [InputText](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/inputtext/) object at the same position of text game object. However, I did not add round-corner feature for [InputText](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/inputtext/). Add this feature to TODO.

**Comment by rexrainbow** [comment]
Support backgroundCornerRadius parameter, please see [this demo](https://codepen.io/rexrainbow/pen/dyezeQN), line 23.
NPM package will upgrade at end of this month.
