### ISSUE TITLE
How to only interact with child of sizer in scrollable panel?

### ISSUE THREAD

**Issue by ngodinhdai286** [rexrainbow/phaser3-rex-notes#433]
I create a scrollable panel with the code below, but I can not find way to only interact with the child of the sizer (here is the button), please help me

![code](https://github.com/rexrainbow/phaser3-rex-notes/assets/74429890/55f3a7ee-6d4a-4ae8-81e0-f35e54422901)

**Comment by rexrainbow** [comment]
Sorry for missing this issue.
[Here](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-scrollablepanel/#input-events) is the solution of interactive with children of scrollable panel.
The [easy way](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-scrollablepanel/#individual-input-events) is to set `scene.input.topOnly` to `false`.

**Comment by rexrainbow** [comment]
Or, disable scroller by adding 
```js
{
    // ...
    scroller: false
}
```
in [config parameter of creating scrollablepanel](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-scrollablepanel/#add-scroll-able-panel-object)

**Comment by ngodinhdai286** [comment]
Thanks for replying me rex, but I am still stuck in that issue. The situation is I just want to be able to click in the red marked button in the picture
![image](https://github.com/rexrainbow/phaser3-rex-notes/assets/74429890/6c501bff-9f8f-42d3-9de9-2650f2a6f2fe)

**Comment by rexrainbow** [comment]
[Here](https://codepen.io/rexrainbow/pen/WNWqzyP) is a test case, interactive logic is at line 49-62.
