### ISSUE TITLE
Add game objects from outside rexUI dialog

### ISSUE THREAD

**Issue by dtturcotte** [rexrainbow/phaser3-rex-notes#436]
For some reason, I can't pass in a game object, like an image, into rexUI dialog and have it display. The image seems to only show if I create the image directly within the config object of dialog. This is the case even when I add the image to the same scene, and set the depth to higher than its other elements. If I remove the background (a roundrectangle), however, the image shows. So, it seems to be simply blocked by other elements.

```
    create() {
        var dialog = this.rexUI.add.dialog({
            x: 400,
            y: 300,

            background: ...,

            title: ...,

            content: this.add.image(0, 0, 'https://i.imgur.com/123.png'), // This shows the image
```

```
    create() {
        const image = this.add.image(0, 0, 'https://i.imgur.com/123.png')
      
        var dialog = this.rexUI.add.dialog({
            x: 400,
            y: 300,

            background: ...,

            title: ...,

            content: image, // This doesn't show the image
```

**Comment by rexrainbow** [comment]
UI element of rexUI usually does not change depth (order of rendering) of children game objects.
It seems that Background is created after Image, thus Background will render after Image.
To solve this issue, you can set depth of Background manually, or

```javascript
var background = dialog.getElement('background');
dialog.sendChildToBack(background);
```

[Reference](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-basesizer/#depth)
