### ISSUE TITLE
How to interact with buttons in gridButtons

### ISSUE THREAD

**Issue by ngodinhdai286** [rexrainbow/phaser3-rex-notes#437]
Below is the code I use to create a gridButtons, although I follow your example but I can not interact with button, plz help me

![code 1](https://github.com/rexrainbow/phaser3-rex-notes/assets/74429890/f3fa03d4-303a-4cbb-b288-6744b7e337ed)
![code](https://github.com/rexrainbow/phaser3-rex-notes/assets/74429890/f6b85584-8ab3-47dc-b314-e597eabc54e1)

**Comment by rexrainbow** [comment]
A possible bug might be `return window.rexUI.add.label({...}`  -> `return scene.rexUI.add.label({...}`
