### ISSUE TITLE
Phaser 3.60.0 don't work,error "ReferenceError: Phaser is not defined     at IsSceneObject.js:1:20"

### ISSUE THREAD

**Issue by cydd007** [rexrainbow/phaser3-rex-notes#439]
import RexUIPlugin from 'phaser3-rex-plugins/templates/ui/ui-plugin.js';
class GameScene extends Phaser.Scene {
  
  constructor(config:any) {
    super(config);
  }
 preload(){}
create(){}

}
var config:Phaser.Types.Core.GameConfig = {
      type: Phaser.AUTO,
      width: width,
      height: height,
      plugins: {
        scene: [
             { key: 'rexUI', plugin: RexUIPlugin, mapping: 'rexUI'}
         ]
      },
      physics: {
        default: 'arcade',
        arcade: {
          gravity: {y: 200 },
          debug: false
        }
      },
      scale: {
        width: width,
        height:  height,
        mode: Scale.CENTER_BOTH  ,
      },      
      
      scene: GameScene,
};

let phaserGame = new Phaser.Game(config);

When I am running in the browser，console error:

"ReferenceError: Phaser is not defined     at IsSceneObject.js:1:20"

when i use this config:
var config:Phaser.Types.Core.GameConfig = {
      type: Phaser.AUTO,
      width: width,
      height: height,
      physics: {
        default: 'arcade',
        arcade: {
          gravity: {y: 200 },
          debug: false
        }
      },
      scale: {
        width: width,
        height:  height,
        mode: Scale.CENTER_BOTH  ,
      },      
      
      scene: GameScene,
};

My program is running normally，Why？

**Comment by rexrainbow** [comment]
Import phaser before rexUI package. Once phaser is imported, it will run [`window.Phaser = Phaser`](https://github.com/phaserjs/phaser/blob/master/src/phaser.js#L89), therefore rexUI can get reference of phaser module.
Please check that `window.Phaser` is valid. Bundle toolchain might not export that instruction.

**Comment by cydd007** [comment]
import RexUIPlugin from 'phaser3-rex-plugins/templates/ui/ui-plugin.js';
import Phaser from 'phaser';

The import order is wrong，modify:

import Phaser from 'phaser';
import RexUIPlugin from 'phaser3-rex-plugins/templates/ui/ui-plugin.js';

It's running
