### ISSUE TITLE
scrollable gridTable is destroying on scene start 

### ISSUE THREAD

**Issue by shohan4556** [rexrainbow/phaser3-rex-notes#443]
I have two scene `Menu` and another scene `Level` where I used `gridTable` once I start that `Level` scene from Menu it keep crashing. 

<img width="543" alt="image" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/8347571/3c7914c6-02bf-49de-a9f5-783a7f149f96">

<img width="693" alt="image" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/8347571/00891d0a-1659-4f8e-b5db-b4c552e67c2c">

**Comment by rexrainbow** [comment]
Close because that bug is fixed
