### ISSUE TITLE
RexColorReplace: artifacts in changing skin colors

### ISSUE THREAD

**Issue by dtturcotte** [rexrainbow/phaser3-rex-notes#448]
I am trying to change skin tones on a sprite's image using your rexColorReplace: [see here](https://codepen.io/dtturcotte/pen/gOJvZWK)

The top of the head, and the face, both have a unified color pixel across their respective regions, but there seems to be discolored "outlines" around the head and face for epsilons 0.1 and 0.25 respectively. How can I remove those artifacts?
<img width="424" alt="Screen Shot 2024-06-19 at 11 50 32 AM" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/4550049/63e5f921-7fea-4b95-b168-02b60f6f0032">

If I change the epsilons higher (0.4, 0.4) the colors are completely off from the ones I want to swap in:

<img width="417" alt="Screen Shot 2024-06-19 at 11 53 36 AM" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/4550049/9f4bb87a-7ecb-4c7c-ab63-7fcd49ba67f4">

Desired output (this was manually done in Photoshop):

<img width="289" alt="Screen Shot 2024-06-19 at 1 16 34 PM" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/4550049/22869839-b240-42b1-aafe-49cd63f461af">

**Comment by rexrainbow** [comment]
How about setting `pixelArt: true` in game config?

**Comment by dtturcotte** [comment]
@rexrainbow I have some non-pixel art items in my game, and setting `pixelArt: true` pixelates the splash images, etc and makes it look terrible. 

Any other suggestions? Do you know if Aseprite exports images with semi-transparent pixels? Because, if I open one of the images exported from Aseprite in Photoshop, and use the wand tool to select pixels of a certain region, it won't select all of the pixels in the supposed matching color region.

In Aseprite, if I use the wand tool to select the darker top head region, it selects all matching colors as expected:

<img width="850" alt="Screen Shot 2024-06-20 at 12 50 14 PM" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/4550049/b692e1f0-2f1c-4d96-96ae-b26e61fd36b4">

However, if I open the image in Photoshop and select the same region, it appears there are some "semi-transparent" pixels. Perhaps this is throwing off the rexColorReplace?

<img width="890" alt="Screen Shot 2024-06-20 at 12 50 19 PM" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/4550049/11f9e026-68fa-400b-bfd3-7ee1fe508037">

**Comment by rexrainbow** [comment]
From source code of phase engine, you can set a texture to antialias render mode. ([Demo](https://codepen.io/rexrainbow/pen/KKLoLdw), line 15).

```js
this.textures.get('face').setFilter(1)
```

**Comment by dtturcotte** [comment]
@rexrainbow This is looking awesome!!! 

I use a TexturePacker atlas, so anyway to do something like the following?

```
this.textures.getFrame(textureKey, framePath).setFilter(1);
```

**Comment by rexrainbow** [comment]
It seems texture based (whole image source). so I guess no possible for dedicate frame.

**Comment by rexrainbow** [comment]
[Reference](https://github.com/phaserjs/phaser/issues/6886#issuecomment-2325258912)
