### ISSUE TITLE
rexCameraController: zoom around cursor position in place of center of the view

### ISSUE THREAD

**Issue by PatBG** [rexrainbow/phaser3-rex-notes#449]
Could it be possible to allow the zoom action to take cursor position in account (mouse x,y for mouse-wheel, center of the two touches for pinch), for zooming at cursor position in place of center of the view.

**Comment by rexrainbow** [comment]
rexCameraController update : 

- Mouse-wheel zoom will zoom at cursor pointer.
- Pinch zoom will zoom at middle of 2 touch pointers
