### ISSUE TITLE
How to install text box plugin

### ISSUE THREAD

**Issue by Aashik30** [rexrainbow/phaser3-rex-notes#45]
Am a beginner for phaser 3. I want to user rex textbox(This Plugin only, Dont Need other Plugins). I don't know how install in ES6. Please Guide Me. 
    I need to install or download your plugin folder and import into my game and use it.

Please give Some instruction to me.

**Comment by rexrainbow** [comment]
You might try these steps to install text box class (not plugin) manually:
1. Copy folder `plugins` and `templates` into your folder, like `rexPlugins`
2. Import text box class via `import TextBox from 'rexPlugins/templates/ui/textbox/TextBox.js';`
3. Finally you can create textBox instance via `var textBox = new TextBox(scene, config);`

**Comment by Aashik30** [comment]
in config what i need set?

**Comment by rexrainbow** [comment]
If you uses import TextBox  class solution, you won't need add anything in config, because that TextBox class is not a plugin, just a class of game object.

**Comment by Aashik30** [comment]
it throw this error-Uncaught TypeError: scene.add.text is not a function : Textbox.js

pls give the solution for this error?

**Comment by rexrainbow** [comment]
@Aashik30 

`scene.add.text(...)` will create a built-in text game object. Usually you will create it in *create* or *update* stage of scene. Therefore, this code will become `this.add.text(...)`.

**Comment by Aashik30** [comment]
Please check Your Mail, I send Input Box Full Coding to you. I Add as a collaborators. Please check and find what is the issue. Reply ASAP.

**Comment by rexrainbow** [comment]
Here is your source code:
```javascript
    var textBox = new TextBox(this.scene,  {
      wrapWidth: 500,
  });
    this.scene.add.existing(textBox);
```

Not `this.scene`, only `this`.

The modified result might be
```javascript
    var textBox = new TextBox(this,  {
      wrapWidth: 500,
  });
    this.add.existing(textBox);
```

Btw, there is no config key named `wrapWidth` in textbox object, [here](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-textbox/#add-textbox-object) is a list of key in textbox's config object

**Comment by Aashik30** [comment]
Remove the wrapWidth in config, But nothing working. Could You try that in my code.
I got this following Error when i pass "this" -
```
Uncaught TypeError: Cannot read property 'scene' of undefined
    at GetSceneObject (GetSceneObject.js:6)
    at new TextPagePlugin (TextPage.js:10)
    at new TextBox (TextBox.js:19)
    at youwin.create (youwin.js:23)
    at SceneManager.create (SceneManager.js:612)
    at SceneManager.bootScene (SceneManager.js:483)
    at SceneManager.start (SceneManager.js:1193)
    at SceneManager.bootQueue (SceneManager.js:238)
    at EventEmitter.emit (index.js:180)
    at Game.texturesReady (Game.js:398)
```

**Comment by rexrainbow** [comment]
Here is a modified test code, which works well in my environment.

```javascript
class Demo extends Phaser.Scene {
    constructor() {
        super({
            key: 'examples'
        })
    }

    preload() {
    }

    create() {
        var textBox = new TextBox(this);
        this.add.existing(textBox);
    }

    update() { }
}
```

**Comment by Aashik30** [comment]
Now All error's are cleared, But No Input TextBox Displayed.

**Comment by rexrainbow** [comment]
Sure, there is no text content in that textbox game object. [Here](https://codepen.io/rexrainbow/pen/MzGoJv) is a demo of textbox.

**Comment by Aashik30** [comment]
but in that demo page there is no Input Box Displayed. In That Page There is text only Displayed. I need A Input Box.  Input is given by User Only.

**Comment by rexrainbow** [comment]
[Here](https://codepen.io/rexrainbow/pen/GaxqLZ) is a demo of editing text object via input dom ([document](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/textedit/)).

**Comment by Aashik30** [comment]
Here is a demo of editing text object via input dom (document).
I successfully created inputtext by your demo instruction,
But i need  to type only Numbers ?

**Comment by rexrainbow** [comment]
> But i need to type only Numbers ?

Sorry I don't understand your requirement in the last post.

**Comment by rexrainbow** [comment]
I see, you want to let text input only can accept number character to keyin.
[Here](https://codepen.io/rexrainbow/pen/OJLQyKz) is a new demo, see line 28-31.

**Comment by rexrainbow** [comment]
If you still need more things to control, try built-in DOM game object. [here](https://labs.phaser.io/view.html?src=src\game%20objects\dom%20element\input%20test.js) is a demo of input text using DOM game object.

**Comment by Aashik30** [comment]
I set that type password in textbox is working fine, aftr out of focus textbox values are visible.
What can I do?

**Comment by rexrainbow** [comment]
To replace characters by '•', you might see these code : https://codepen.io/rexrainbow/pen/YbvwBw , line 87-90

**Comment by Aashik30** [comment]
I set the password successfully working,But in that page I have one register Button(It goes to register Page) I Click  the register button its throws an error.

Error 

> Uncaught TypeError: Cannot read property 'contains' of undefined
>     at Group.remove (rexuiplugin.min.js:1)
>     at emit (rexuiplugin.min.js:1)
>     at e.destroy (rexuiplugin.min.js:1)
>     at e.value (rexuiplugin.min.js:1)
>     at e.value (rexuiplugin.min.js:1)
>     at e.value (rexuiplugin.min.js:1)
>     at DisplayList.shutdown (rexuiplugin.min.js:1)
>     at EventEmitter.emit (rexuiplugin.min.js:1)
>     at Systems.shutdown (rexuiplugin.min.js:1)
>     at SceneManager.stop (rexuiplugin.min.js:1)
> remove @ rexuiplugin.min.js:1
> emit @ rexuiplugin.min.js:1
> destroy @ rexuiplugin.min.js:1
> value @ rexuiplugin.min.js:1
> value @ rexuiplugin.min.js:1
> value @ rexuiplugin.min.js:1
> shutdown @ rexuiplugin.min.js:1
> emit @ rexuiplugin.min.js:1
> shutdown @ rexuiplugin.min.js:1
> stop @ rexuiplugin.min.js:1
> processQueue @ rexuiplugin.min.js:1
> update @ rexuiplugin.min.js:1
> step @ rexuiplugin.min.js:1
> step @ rexuiplugin.min.js:1
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1
> requestAnimationFrame (async)
> step @ rexuiplugin.min.js:1

This is a back button Coding:
```
this.back = new GameObject(this, 0, 0, 'back')
    .placeAtIndex(119)
    .scaleToGameW(0.125)
    .setOrigin(0.5, 0.8)
    .setInteractive();
    this.back.on('pointerup', function(pointer) {
      this.scene.scene.stop(SCENES.LOGINPAGE);
      this.scene.scene.resume(SCENES.INIT);
      console.log('scnepage:'+SCENES.LOGINPAGE);
    });
```

**Comment by rexrainbow** [comment]
Sorry I can't debug with these piece of code, could you please provide an executable test code?

**Comment by Aashik30** [comment]
Finall I find The Solution Of That above Problem. I have 3 scenes(scenes1, scenes2, scenes3). Scene1 is my main page starting of the game it display register and login button. scenes 2 is login and scenes3 is register page. Scene 2 i implement your textbox code. 1st i click the login page it's working fine. then i want to back to main page(scenes1).

`this.back = new GameObject(this, 0, 0, 'back')
    .placeAtIndex(119)
    .scaleToGameW(0.125)
    .setOrigin(0.5, 0.8)
    .setInteractive();
    this.back.on('pointerup', function(pointer) {
      this.scene.scene.start(SCENES.LOGINPAGE);
    
    });`
this is back button code. if i click this back button i got the below Error.

In Chrome :- 
`Uncaught TypeError: Cannot read property 'contains' of undefined
    at Group.remove (rexuiplugin.min.js:1)
    at emit (rexuiplugin.min.js:1)
    at e.destroy (rexuiplugin.min.js:1)
    at e.value (rexuiplugin.min.js:1)
    at e.value (rexuiplugin.min.js:1)
    at e.value (rexuiplugin.min.js:1)
    at DisplayList.shutdown (rexuiplugin.min.js:1)
    at EventEmitter.emit (rexuiplugin.min.js:1)
    at Systems.shutdown (rexuiplugin.min.js:1)
    at SceneManager.stop (rexuiplugin.min.js:1)`

In FireFox:-
`TypeError: this.children is undefinedGroup.js:558
    remove Group.js:558
    emit index.js:181
    destroy GameObject.js:579
    value rexuiplugin.min.js:1
    value rexuiplugin.min.js:1
    value rexuiplugin.min.js:1
    shutdown DisplayList.js:169
    emit index.js:203
    shutdown Systems.js:727
    stop SceneManager.js:1215
    processQueue SceneManager.js:291
    update SceneManager.js:552
    step Game.js:475
    step self-hosted:1007
    step TimeStep.js:576
    step self-hosted:1003
    step RequestAnimationFrame.js:105`

QUESTION 1:- IF i use Switch scene Instead of start is working fine WHY?

`this.scene.scene.switch(SCENES.LOGINPAGE);`

This code is working fine.  WHY?

QUESTION 2:-FINALLY I want to implement placeholder in textBox. Anyoption There for Placeholder ?

**Comment by Aashik30** [comment]
Why no Reply from Your Side? If i implement your plugin we cannot stop the scene This is the Error.

**Comment by rexrainbow** [comment]
Please provide an executable, simple test code for this issue.
