### ISSUE TITLE
"FixWidthSizer" unwanted expansion

### ISSUE THREAD

**Issue by dtturcotte** [rexrainbow/phaser3-rex-notes#454]
Please see [this](https://codepen.io/dtturcotte/pen/XWwQEZP?editors=0010) forked code.

I've set the `width: 100`, but you'll notice extra long content forces the rexUIScrollablePanel to expand beyond its set width.

This is causing a lot of UI issues currently. How can I fix this and force the width I set?

Note: In [this Fix-Width Sizer Documentation](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-fixwidthsizer/), it says that `width, height : Minimum width, minimum height.`, meaning only the minimums are set. The same is true for [Scroll-able Panel with Fix-Width Sizer](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-scrollablepanel/). Any recommendations? Even if I set `wordWrap`, it still causes an issue.

Note, I am using both RexUIBBCodeText and Phaser.GameObjects.Text and it's causing the same issues. 

-------------

I checked my scrollablePanel width and height after adding elements then `layout()` and the width seems to adjust itself. How can I prevent this?

**Comment by rexrainbow** [comment]
*Minimum width*, *minimum height*, is the **minimum size** of ui element, not the *maximun* size, therefore the actual size after layout might larger these minWidth, minHeight setting.

From that use case, might try [sliderXY mode](https://codepen.io/rexrainbow/pen/VwVVyYV).
