### ISSUE TITLE
Remove gaps between jigsaw pieces

### ISSUE THREAD

**Issue by meetpatel1989** [rexrainbow/phaser3-rex-notes#455]
Hi, I've been using your `rexcutjigsawimageplugin`. I wrote some code to remove the preFX once a piece is successfully placed in its original position. However, there's still a visible gap between the pieces where the edge was created.

For reference, please see the image below.

<img width="368" alt="image" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/47215461/ab190422-54ea-4277-aa93-7556f15c9950">

I even removed the FX from the beginning of the game but the gap is still there.

<img width="364" alt="image" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/47215461/eb81a98b-2741-43f6-bbfa-fd2805aa73fd">

Am I missing anything here?

I know the preFX process is very resource-intensive, and I'm not considering applying it to all pieces because it causes the game’s FPS to drop significantly if I add them to all pieces. However, even when I remove the preFX from the pieces once they're placed, the issue persists. Do you have any idea why this might be happening?

Thanks!

**Comment by rexrainbow** [comment]
Update minify file of CutJigsawImage plugin, overlap curve of edge, to eliminate gap between pieces.

**Comment by meetpatel1989** [comment]
Thank you for the quick update! Yes, it is working fine now(when I don't use prefx), as shown in the following image.

<img width="375" alt="image" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/47215461/91f4ed92-b50e-47ee-836b-c4d41f1362dc">

However, if I use preFX, and remove the outer glow when the piece is placed, it works fine except the last row.
<img width="371" alt="Screenshot 2024-07-07 at 6 38 54 pm" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/47215461/76e5359b-1f10-4d1a-921a-3ab571c211dc">
<img width="368" alt="Screenshot 2024-07-07 at 6 39 48 pm" src="https://github.com/rexrainbow/phaser3-rex-notes/assets/47215461/454eb8a1-0185-485d-9346-a102f16e0d5a">

I'm using an image with a resolution of 540x720 and have the following settings to create jigsaw pieces
`var pieces = this.plugins
      .get('rexCutJigsawImage')
      .gridCut(this.sourceImage, {
        piecesKey: 'pieces',
        columns: 5,
        rows: 7,
        edgeWidth: 15,
        edgeHeight: 15,
        useDynamicTexture: false,
        createImageCallback: function (scene, texture, frame) {
          return new Jigsaw(scene, 0, 0, texture, frame)
        }
      })`

I also didn't get you here: **overlap curve of edge, to eliminate gap between pieces**

**Comment by rexrainbow** [comment]
There have concave edges and convex edges. I draw convex edges larger (more 1 pixel) and concave edges smaller (less 1 pixel), so that they will overlap.

**Comment by rexrainbow** [comment]
[Here](https://codepen.io/rexrainbow/pen/NWegLLK) is a test case with preFx outline, works well.
Please provide a simplest test example for the latest issue.

**Comment by meetpatel1989** [comment]
@rexrainbow Please get the source code from this link.

https://drive.google.com/file/d/1O81C5JkGCyUaHDwGJ5N-hSNnQzetgyHh/view?usp=drive_link

Using your webpack template :) Just drag the piece and place it in the same place to remove the preFX. You will see the missing pixels on the last row.

**Comment by rexrainbow** [comment]
[Here](https://codepen.io/rexrainbow/pen/jOjOyGR) is a test case, using your image and setting, It looks well too.
![圖片](https://github.com/rexrainbow/phaser3-rex-notes/assets/817962/8130b97a-5746-4c3e-86a6-b595a2080651)

**Comment by meetpatel1989** [comment]
@rexrainbow Thank you for creating a demo. Yes, it works fine as I said earlier but not for the last row. Please click on the last row's pieces to see a visible black line between the jigsaw pieces when I remove the preFX. 

https://codepen.io/meetpatel1989/pen/yLdLEJp

**Comment by rexrainbow** [comment]
This behavior is correct.

Edges of pieces are overlapping, to eliminate gaps between pieces, as I mention before.
The dragging piece will bring to top, then the outline effect is removed when dropping. 
This edge top piece will overlap outline edges of neighbor pieces, therefore this bound of outline edge is gone.

**Comment by rexrainbow** [comment]
[Modified test case](https://codepen.io/rexrainbow/pen/bGPNpXa), line 36.

**Comment by meetpatel1989** [comment]
@rexrainbow  Here is a final game I built using the plugin. I can see the edges which you mentioned but to cover it up, I removed all the pieces and enabled the original source image when the puzzle is completed.

https://game-test.sgp1.digitaloceanspaces.com/jigsaw-puzzle/v0.0.2/index.html
