### ISSUE TITLE
Toast will flash when pressedstart

### ISSUE THREAD

**Issue by weizhi9958** [rexrainbow/phaser3-rex-notes#46]
My English is not good, use google translation for help.
I use GesturesPlugin.press and rexUI.toast.
When I showed taost a second time in pressstart.
Toast will flash.
The code looks like this.

```
const press = this.rexGestures.add.press(gameObject, { time: 1000 });
press.on('pressstart', (press) => {
  this.rexUI.add.toast({
    x: press.x,
    y: press.y,
    background: this.rexUI.add.roundRectangle(0, 0, 2, 2, 20, '#ABABAB'),
    text: this.add.text(0, 0, '', { fontSize: '24px' }),
    space: {
      left: 20,
      right: 20,
      top: 20,
      bottom: 20,
    },
  }).show('message');
});
```

**Comment by rexrainbow** [comment]
Thanks for reporting this issue. It is a bug of toast plugin, and fixed. Please try last version of rexUI plugins.

**Comment by weizhi9958** [comment]
I re-use rexuiplugin.min.js
Flashing still occurs in pressstart
But in the general click event or pressend event is no problem

**Comment by rexrainbow** [comment]
I had updated rexUI again. [Here](https://codepen.io/rexrainbow/pen/JjPLywb) is a test case of pressing-then-toast. It seems no flashing now.

**Comment by weizhi9958** [comment]
Thank you.
The latest version is no longer flashing.
