### ISSUE TITLE
bbcode中的命令大多不存在~ 

### ISSUE THREAD

**Issue by woshisheji** [rexrainbow/phaser3-rex-notes#461]
例如：     let aaa=   this.add.rexBBCodeText(400, 30, s2, {
            fontSize: '30px',
            backgroundColor: '#888',
            backgroundColor2: '#222',
            backgroundHorizontalGradient: false,
            backgroundStrokeColor: 'red',
            backgroundStrokeLineWidth: 2,
            backgroundCornerRadius: -20, // 20
            // backgroundCornerIteration: 0,
            padding: 20
        })
//这下面命令，大多set的都不存在。。 没有一个个测试 这些附加属性，大多有问题了。。 用的是目前最新的3.8
     aaa.setUnderlineColor(5)

**Comment by rexrainbow** [comment]
Thanks for this bug reporting.

Add missing method implementation of BBCodeText : `setUnderline`, `setUnderlineColor`, `setUnderlineThickness`, `setUnderlineOffset`, `setStrikethrough`, `setStrikethroughColor`, `setStrikethroughThickness`, `setStrikethroughOffset`.
