### ISSUE TITLE
DynamicText error

### ISSUE THREAD

**Issue by JF-png** [rexrainbow/phaser3-rex-notes#462]
Im using rex’s dynamic text plugin in my current project and ran into an error

`object is not iterable (cannot read property Symbol(Symbol.iterator))`

When i trying to spawn it in create of my scene like that:

`var text = this.add.rexDynamicText({  
            x: 841.5,
            y: 658.5,
            width: 132,
            height: 61,

            background: {
                color: null,
                color2: null,
                horizontalGradient: true,
        
                stroke: null,
                strokeThickness: 2,
        
                cornerRadius: 0,
                cornerIteration: null
            },

            style: {
                bold: true,
                fontSize: '45px',
                fontFamily: 'Inter',
                color: '#fff',
                backgroundColor: null,
                backgroundHeight: undefined,
                backgroundBottomY: undefined,
            },
        });
        text.setText('400');`

**Comment by rexrainbow** [comment]
Can't get any error message with that test code. ([Live demo](https://codepen.io/rexrainbow/pen/MWMEqxd))

**Comment by JF-png** [comment]
Im using Phaser 3.60.0 and installing plugin global, building the game via parcel

**Comment by JF-png** [comment]
here, https://emtodev.itch.io/blocks2048. Also if i use the preload installation, i dont get such errors, but webgl warnings appear in the console, and the text itself turns into a blue rectangle

**Comment by rexrainbow** [comment]
> Im using Phaser 3.60.0 and installing plugin global, building the game via parcel

Use latest version of phaser (3.80) with latest rex plugin.
If you still need run with phaser 3.60, choose rex plugin 1.60.x ( [versuions](https://www.npmjs.com/package/phaser3-rex-plugins?activeTab=versions))

**Comment by rexrainbow** [comment]
Please upgrade phaser3 to latest version with latest rex plugin. 
[live demo](https://codepen.io/rexrainbow/pen/MWMEqxd)) shows that no error in this case.
