### ISSUE TITLE
Typo while destroying pinch zoom

### ISSUE THREAD

**Issue by vpjapp** [rexrainbow/phaser3-rex-notes#463]
Hi.

It seems that there is a typo `destro` instead of `destroy` while destroying pinchZoom.

https://github.com/rexrainbow/phaser3-rex-notes/blob/90a1e2af26545a3e8dd4a65d4eb9cd2878f11530/plugins/camera/controllerpack/ControllerPack.js#L73

**Comment by rexrainbow** [comment]
[Fixed](https://github.com/rexrainbow/phaser3-rex-notes/commit/6e92bafd6d31a4c9fbd3415fb751f5d72dc54f44). 👍

**Comment by vpjapp** [comment]
Very fast response. Impressive :zap: :muscle:
