### ISSUE TITLE
Error in CodePen Sprite Control Text Player Demo

### ISSUE THREAD

**Issue by tdgao** [rexrainbow/phaser3-rex-notes#464]
Sprite control demo is stopping after text displays "Hello." Does not show any sprites.

Reference to CodePen: https://codepen.io/rexrainbow/pen/jOBroeY?editors=1111
From doc: https://rexrainbow.github.io/phaser3-rex-notes/docs/site/textplayer/
Error in console: 
![image](https://github.com/user-attachments/assets/9f181872-d576-4692-9e01-7802bf95520b)

**Comment by rexrainbow** [comment]
Thanks for this bug reporting, this bug has been fixed. Please run that test case again.
NPM package will upgrade at end of this month.

**Comment by tdgao** [comment]
Works. Thank you for the quick fix!
