### ISSUE TITLE
BUG: Cannot run destroy on TextPlayer

### ISSUE THREAD

**Issue by tdgao** [rexrainbow/phaser3-rex-notes#465]
After creating a TextPlayer, it cannot be destroyed and removed from the scene. The following error occurs: 

![image](https://github.com/user-attachments/assets/053c28d2-9712-440d-9974-d422fc053be7)

Replicated in CodePen using TextPlayer destroy example:

CodePen: https://codepen.io/Truman-Gao/pen/BagJWYp?editors=1011
Github example: https://github.com/rexrainbow/phaser3-rex-notes/blob/master/examples/textplayer/destroy.js#L1C1-L62C36

**Comment by tdgao** [comment]
Just a note, currently I'm just hiding all the TextPlayers on complete using `setVisible(false)` instead of destroy them as a temporary solution. My use case is customizing the TextPlayer on runtime which requires recreating the game object with new config. Otherwise I would have to specifically handle each customization option (That would be a pain!).

**Comment by rexrainbow** [comment]
Thanks for this bug reporting, this bug has been fixed. Please run that test case again.
NPM package will upgrade at end of this month.

**Comment by tdgao** [comment]
Working now, again thanks for the quick fix!
