### ISSUE TITLE
Error in CodePen TextPlayer Choices Demo

### ISSUE THREAD

**Issue by tdgao** [rexrainbow/phaser3-rex-notes#466]
Text Player stops at end of "Prelogue" and waiting on pointerdown but nothing triggers it. Choices also not showing.

CodePen: https://codepen.io/rexrainbow/pen/dydQjow
From doc "choices demo": https://rexrainbow.github.io/phaser3-rex-notes/docs/site/textplayer/#create-instance

Sorry to bring up another demo with an error! This one is less urgent but I'm more curious just to see what the choices looks like.

![image](https://github.com/user-attachments/assets/caeb0cb8-dd67-41e6-8fd7-4cb87eeb1fff)

**Comment by rexrainbow** [comment]
I fix that demo case, line 87 `text.resume()` -> `text.resumeTyping()`, because that `text.pauseTyping()` and `text.resumeTyping()` are a pair.
Also fix a bug in `text.resume()` method.

**Comment by rexrainbow** [comment]
[Here](https://codepen.io/rexrainbow/pen/ZEdvPme) is a new demo of textplayer - choices, which open a choice dialog made by rexUI ([confirmDialog](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-confirmdialog/))

**Comment by rexrainbow** [comment]
Note that 'choices' is not a built-in feature of TextPlayer, it is composed of custom tags (`question`, `choice`) and custom game objects (rexUI)

**Comment by tdgao** [comment]
Gotcha. Makes sense, thanks for the clarification. Closing issue now.
