### ISSUE TITLE
How to block input event to lower layer UI? 

### ISSUE THREAD

**Issue by rexrainbow** [rexrainbow/phaser3-rex-notes#469]
When two UI overlap, if mouse drag up down on upper layer UI, the lower layer UI also scroll up down.
I try to call setScrollerEnable() when upper layer UI shown, it works.
But is any way to block event to lower layer UI without call setScrollerEnable()?
(I use scrollablePanel)
![未命名](https://github.com/user-attachments/assets/690864fc-756e-41a2-a2fc-f9447d31bdc8)

_Originally posted by @bwm0822 in https://github.com/rexrainbow/phaser3-rex-notes/discussions/468_

**Comment by rexrainbow** [comment]
I update the scrolling detecting of [TextArea](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-textarea/), please use TextArea on top level [modal dialog](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-dialog/#modal)

**Comment by bwm0822** [comment]
I use TextArea on upper level UI, but when scroll on upper level UI, lower level UI also scroll. 
I attach my test code.
[test.zip](https://github.com/user-attachments/files/16691633/test.zip)

**Comment by rexrainbow** [comment]
Update scrollablepanel, now the overlapping scrollable game object works fine. [live demo](https://codepen.io/rexrainbow/pen/poXVoZM)

**Comment by bwm0822** [comment]
Thanks. It works fine.
