### ISSUE TITLE
ui-gridtable 中的bug反馈

### ISSUE THREAD

**Issue by woshisheji** [rexrainbow/phaser3-rex-notes#471]
1.将 let aaa=this.rexUI.add.gridTable() 添加到官方默认容器中，它的遮罩似乎会无效 如图效果：
![bug1](https://github.com/user-attachments/assets/aedcd91d-494f-4009-b77b-b959a0595dd3)

正常效果：
![bug2](https://github.com/user-attachments/assets/1b0c05cc-d56c-4eef-a88d-5f92b7dc41e7)

2.如果相机偏移坐标，相机视野坐标设定到10000,10000，（任意超出窗口坐标）
那么除了滚动有效，其他所有点击表项的事件均失效，尝试固定过里面内部对象，但似乎也无效。.
aaa.setScrollFactor(0, 0);  
又尝试
let tableBody = aaa.getElement('table')
tableBody .setScrollFactor(0, 0);  
依旧无效。

**Comment by rexrainbow** [comment]
Duplicated #363

**Comment by rexrainbow** [comment]
That issue has been assigned as milestone of [Phaser Beam](https://github.com/phaserjs/phaser/milestone/3)
see https://github.com/phaserjs/phaser/issues/6177 , the last line

**Comment by woshisheji** [comment]
不加入到容器，相机坐标偏移后，事件也会丢失无效。不知道这个问题是什么异常。就是我所说的第二个问题

**Comment by rexrainbow** [comment]
[Test code](https://codepen.io/rexrainbow/pen/PordqGL), slider, scroller, clicking child all work.

Please provide a simplest runnable sample code for reproducing that case.

**Comment by woshisheji** [comment]
https://codepen.io/rexrainbow/pen/XyJbWX?editors=1010
在代码行 183行后面添加以下命令
     gridTable.setScrollFactor(0);
    this.cameras.main.setScroll(20000, 0);
所有表格中的cell事件将会失去响应。可能是内部没有跟随。

**Comment by rexrainbow** [comment]
Bug fixed, see this [test case](https://codepen.io/rexrainbow/pen/PordqGL). Camera scrolling is at line 186.

**Comment by woshisheji** [comment]
测试OK。

**Comment by rexrainbow** [comment]
Thank you for finding the bug
