### ISSUE TITLE
Breaking change.

### ISSUE THREAD

**Issue by zachpainter77** [rexrainbow/phaser3-rex-notes#475]
I've been using this in a small phaser game for a while now.. 

Some recent change now causes this error to break my app.. 

![image](https://github.com/user-attachments/assets/8d04f40d-06cc-475f-ba32-fb228104049f)

I have downloaded a previous working version as a workaround, but referencing the master distribution breaks my app. Just letting you know.

**Comment by rexrainbow** [comment]
Please provide a simplest, runnable test case for reproducing this error.

**Comment by rexrainbow** [comment]
No feedback, close this issue.

**Comment by zachpainter77** [comment]
That's fine close it. I have the version that works for me.
