### ISSUE TITLE
Typo in ChildrenMaskMethods.js

### ISSUE THREAD

**Issue by tickle-monster** [rexrainbow/phaser3-rex-notes#483]
Line 23 of [https://github.com/rexrainbow/phaser3-rex-notes/blob/master/plugins/gameobjects/container/containerlite/mask/ChildrenMaskMethods.js](ChildrenMaskMethods.js) has:

`this.onMaskGameObjectVisible = GetValue(config, 'onVisivle');`

Should read: 

`this.onMaskGameObjectVisible = GetValue(config, 'onVisible');`

**Comment by tickle-monster** [comment]
My first submitted issue! I am sure I stuffed up the formatting, please forgive me.

**Comment by rexrainbow** [comment]
Fixed that typo at latest commit.
