### ISSUE TITLE
Feature Request: Nine patch repeating texture gap filling

### ISSUE THREAD

**Issue by MarlQ** [rexrainbow/phaser3-rex-notes#486]
Hi, I have been trying to use NinePatch2 to create the background/borders for my UI.
Unfortunately, currently, if you try to use a repeating texture, 
there will be gaps when the width or height of the UI element is not divisible by the size of the nine patch. 

Example of the issue:
![image](https://github.com/user-attachments/assets/7e557b0d-8f83-4d57-8f36-cd4573a26d61)

I would expect that the gap is filled by a crop of the corresponding edge.

Example for a solution in GIMP:
![image](https://github.com/user-attachments/assets/05087d56-562b-464c-9167-a275205d2af9)

**Comment by rexrainbow** [comment]
Using [NinePatch](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ninepatch/) which support this gap-filling feature first.
I can try to implement it in NinePatch2 later.

**Comment by MarlQ** [comment]
Oh sorry, I did not realise that NinePatch actually supported this already :)

**Comment by rexrainbow** [comment]
Rendering feature added. (it is a bug, imo)
Please get latest minify file, npm package will upgrade at end of this month.
[Demo](https://codepen.io/rexrainbow/pen/dyxVeOZ), drag the gray box to resize this nine patch2 game object.
