### ISSUE TITLE
dropDownList 设 wrap 为 true 不起作用了

### ISSUE THREAD

**Issue by gzjayvan** [rexrainbow/phaser3-rex-notes#489]
以前运行正常的，现在使用最新的 rexuiplugin.min.js ，下拉选项不能分列列表了。
https://codepen.io/ 上的 Drop-down wrap-list 例子(https://codepen.io/rexrainbow/pen/PoQWobV) 也是如此。

另外，gridSizer 的 InsertEmptyRow 似乎拼错为 InseryEmptyRow 了？

**Comment by rexrainbow** [comment]
Typo (`InseryEmptyRow`) in GridSizer is fixed. Please get latest minify file.
NPM package will upgrade at end of this month.
