### ISSUE TITLE
Destroying bbcode text area

### ISSUE THREAD

**Issue by alexandernst** [rexrainbow/phaser3-rex-notes#49]
Is there a way I can destroy a particular area inside a bbcode text object?

I made a small demo: https://codepen.io/alexandernst/pen/LYPobqO?editors=0010

**Comment by rexrainbow** [comment]
1. Read text content back.
2. Remove string content of area, by regex
3. Set new text content.

**Comment by alexandernst** [comment]
But this will cause a reflow in the text (the gap that will be left from the removed text will be filled by the text on the right). Is there a way I can destroy that area without causing a reflow?

**Comment by rexrainbow** [comment]
How about replace string content of area by space(' '), to prevent *reflow*?

Or, [here](https://codepen.io/rexrainbow/pen/eYOdKBR) is a demo of assembling text content via text objects (per word). Each text objects (per word) could change color, or be destroyed.

**Comment by alexandernst** [comment]
I was able to parse my bbcode and insert each word in a `fixWidthSizer`.

My code:

```
export default class Code {
    constructor(world) {
        this.world = world;

        this.open_tag = "[color";
        this.close_tag = "[/color]";

        this.sizer = world.UIPlugin.add.fixWidthSizer({
            x: 0,
            y: 0,
            width: world.game.scale.width,
            height: world.game.scale.height,
            space: {
                left: 10,
                top: 10,
                item: 0
            }
        });
        this.sizer.setOrigin(0, 0);

        return this;
    }

    *bbcode_parser(bbcode) {
        while(true) {
            if(bbcode.length === 0) {
                return;
            }

            let start = bbcode.indexOf(this.open_tag);
            let end = bbcode.indexOf(this.close_tag) + this.close_tag.length;

            const res = bbcode.slice(start, end);
            bbcode = bbcode.slice(0, start) + bbcode.slice(end);
            bbcode = bbcode.replace(/^\s+|\s+$/g, '');

            yield res;
        }
    }

    fill(text) {
        var text_lines = text.split('\n');
        for(let li = 0, lcnt = text_lines.length; li < lcnt; li++) {
            for(let res of this.bbcode_parser(text_lines[li])) {
                var word = this.world.make.rexBBCodeText({
                    text: res,
                    style: {
                        fontSize: 14
                    },
                    add: true
                });
                this.sizer.add(word);
            }

            if (li < (lcnt - 1)) {
                this.sizer.addNewLine();
            }
        }
        this.sizer.layout();
    }
}
```

Use it like:

```
code = new Code(scene);
code.fill(my_bbcode);
```

I have one further problem. This is a quite expensive operation (the instantiation of `rexBBCodeText` objects). 

Is there a way I can leverage / optimize this? Maybe creating objects in batch?

**Comment by rexrainbow** [comment]
You might use official text object instead of rexBBCodeText object, if all words only have single color. Thus they don't need to parse each content of bbcode text.

**Comment by alexandernst** [comment]
No, I have bbcode text, that's why I'm using rexBBCodeText objects.

**Comment by rexrainbow** [comment]
I have no other idea how to optimize this case, sorry.

**Comment by alexandernst** [comment]
Don't worry ;) Thanks for the help!

**Comment by rexrainbow** [comment]
Or, set color of area to `none`, like `[color=none]content[/color]`, which will draw content without any color, to pretend this content is destroyed.
