### ISSUE TITLE
Error with Phaser 3.87

### ISSUE THREAD

**Issue by XWILKINX** [rexrainbow/phaser3-rex-notes#491]
When updating to the latest version of Phaser (3.87), the following error occurs:

`Uncaught TypeError: Cannot read properties of null (reading '1')
    at CheckP3Version`

**phaser3-rex-plugins/plugins/utils/system/CheckP3Version.js**
`var currentVersion = parseInt(Phaser.VERSION.match(/\.(\d+)\./)[1]);`

This error seems to be due to `Phaser.VERSION` being `'3.87'` instead of `'3.87.0'`.

**Comment by rexrainbow** [comment]
That was fixed today ([commit](https://github.com/rexrainbow/phaser3-rex-notes/commit/92a283384e12da43a8b22e76b02800ee04cf6651))
I will upgrade npm package at end of this month.

**Comment by rexrainbow** [comment]
Okey, npm package also upgrade
