### ISSUE TITLE
MiniBoard & Board

### ISSUE THREAD

**Issue by rexrainbow** [rexrainbow/phaser3-rex-notes#494]
Hello @rexrainbow ,

I’m using the Board and MiniBoard classes for my grid game.

1-When two MiniBoards overlap and both are set to draggable, dragging one moves both together. How can I make it so only one of them is dragged?
2-I need to access the position information of the GameObjects inside the MiniBoard. How can I achieve this? Should I use a `getAll` function for this?
3-I want to use a `getBounds()` method like in a `Container`, but in the MiniBoard, the width and height return 0 even if there are objects inside. How can I fix this?
4-I noticed in the example [here](https://codepen.io/rexrainbow/pen/PoeZOGo) that functions like `var bounds = board.getBoardBounds(true); `and similar ones do not appear in TypeScript, and the VS Code editor shows compile errors. However, the game runs without any issues. How can I prevent this?

Kind regards,

_Originally posted by @meturgut in https://github.com/rexrainbow/phaser3-rex-notes/discussions/493_

**Comment by rexrainbow** [comment]
Minboard class is updated :

- Add `miniboard.getBounds()` method (Q3)
- Add `miniboard.getAllChess()` method (Q2)
- When dragging on overlapped minboard, only upper one will be dragged ( [demo](https://codepen.io/rexrainbow/pen/KwPwOjO) ) (Q1)
- Add missing type define `board.getBoardBounds` (Q4)

**Comment by meturgut** [comment]
Thanks @rexrainbow
