### ISSUE TITLE
script标记方式引入后如何加载rexuiplugin

### ISSUE THREAD

**Issue by ixqbar** [rexrainbow/phaser3-rex-notes#495]
假设phaser是用script引入， 如何使用script标记引入后加载rexuiplugin

https://github.com/rexrainbow/phaser3-rex-notes/blob/dbbd392dcbd617c8d8aba3566cf081245f509f94/examples/ui-label/two-scenes.js#L13
![image](https://github.com/user-attachments/assets/4d13e798-cfc2-4335-8412-364c2faac42f)

**Comment by rexrainbow** [comment]
Sure it works. See this [demo](https://codepen.io/rexrainbow/pen/YMyBom).
If you still can't load from url, might check the accessible of script url, it might be blocked in your environment.

**Comment by ixqbar** [comment]
thanks
