### ISSUE TITLE
Cannot read property 'matrix' of undefined

### ISSUE THREAD

**Issue by denostr** [rexrainbow/phaser3-rex-notes#5]
After running
`scene.add.rexBBCodeText(0, 0, 'test text');`

get this error

> Uncaught TypeError: Cannot read property 'matrix' of undefined
> at TextureTintPipeline.batchTexture

**Comment by rexrainbow** [comment]
Please fetch latest bbcode plugin from this repo, or download from [this link](https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/plugins/dist/rexbbcodetextplugin.min.js)
[Here](https://codepen.io/rexrainbow/pen/yjZveb) is a demo of latest bbcode plugin running in phaser 3.11.0.

**Comment by denostr** [comment]
Thanks, problem solved by updating phaser to latest version, recently i used 3.10.1 version
