### ISSUE TITLE
Problem with rollup and terser compression.

### ISSUE THREAD

**Issue by iKest** [rexrainbow/phaser3-rex-notes#50]
Hello. When compressing the bundle compiled by rollup, terser throws an error: 
```
Components$1.Alpha,
 Components$1.Flip, );
                  ^ Unexpected token: punc ())
```
The problem is solved if in module phaser3-rex-notes/plugins/gameobjects/containerlite/ContainerLite.js the last comma in the assigned object is removed.

```
Object.assign(
ContainerLite.prototype,
....
 Children,

Components.Alpha,
Components.Flip , <------ this comma need to removed
);
```

Thanks for your great plugins!

**Comment by rexrainbow** [comment]
This bug has been fixed in latest commit. Thanks for reporting this issue.

**Comment by rexrainbow** [comment]
Issue solved.
