### ISSUE TITLE
WebFontLoader issue.

### ISSUE THREAD

**Issue by ikeba** [rexrainbow/phaser3-rex-notes#51]
Hi Rex.
First of all, I'd like to thank you for all the work you're doing. Thanks to you, the lives of thousands of developers around the world have become easier :)
I have a question about your WebFontLoader plugin. Maybe it's not the right place to ask, but still.
I download fonts in the preload() phase. We're talking about the 'Noto Sans' family, but perhaps the same problem is true for other fonts as well.
When I use the usual font "Noto Sans" - everything works as it should. 
But the gap occurs when I try to use "Noto Sans Hebrew".

Judging by the Network tab, the font is loaded on time, before the text is initialized, but the first time it is used it does not work. For example, in the create() phase, I'm trying to create text - in Chrome, it will load a standard font for the system instead of special, but in Firefox, for example, it will not appear at all. 
If you reload the page (without clearing the cache), it will work. If you clear the cache, the error occurs again.

What do you think may be the problem?
Thanks in advance for the answer. 

Links to the demo repo:
https://gitlab.com/ikeba/phaser-typescript-skeleton
**pages:** https://ikeba.gitlab.io/phaser-typescript-skeleton/

**Comment by rexrainbow** [comment]
![圖片](https://user-images.githubusercontent.com/817962/66380470-18d8ef00-e9ea-11e9-8665-58a20aab929e.png)
Here is my result of running [demo](https://codepen.io/rexrainbow/pen/OJJPwYv) in chrome(upper texts) and firefox (lower texts), the looks of font in these 2 browsers seems not the same. 

But the result in anther environment looks good.
![圖片](https://user-images.githubusercontent.com/817962/66380771-a4528000-e9ea-11e9-87db-8f8c8ac9dbbb.png)

It might be a complex issue I guess. I will try to solve it later.

**Comment by ikeba** [comment]
Thanks for the answer. 
To see more complex result for this specific font, you should consider using native letters, e.g. 
> 'שלום עולם!'
I mentioned Chrome and Firefox because it is not visible at all in Firefox and it is easier to see the problem (imho).

For example,
first time:
![image](https://user-images.githubusercontent.com/7779156/66382378-c553aa80-e9c3-11e9-9d10-08ae9cb94c62.png)
and second (with cache)
![image](https://user-images.githubusercontent.com/7779156/66382474-ed430e00-e9c3-11e9-9684-1420882b4eec.png)

**Comment by ikeba** [comment]
Reproduced in your test snipped also:

1st time
![image](https://user-images.githubusercontent.com/7779156/66383070-03050300-e9c5-11e9-997c-c9c0230187c3.png)

And second time
![image](https://user-images.githubusercontent.com/7779156/66383106-131ce280-e9c5-11e9-931c-2437f375ada8.png)

**Comment by rexrainbow** [comment]
Yes, I see that weird result. I modified test code to show 'Hello' and שלום' עולם!' . 
1st time, 'Hello' will be shown, 2nd time, all words will be shown, like you said. Since 'Hello' is shown, I thought that font was loaded completed. But I have no idea why  עולם!'  is not shown, sorry.

**Comment by rexrainbow** [comment]
It seems that some parts of font is not loaded completed, i.e. trigger 'active' event (an internal event of google webfont loader) too early.
Maybe I could add a string parameter, to check if this specific string is drawn on a background text object.

**Comment by rexrainbow** [comment]
Add string parameter `testString` into config, to test if the font is loaded completed or not.

1. Fill `0` within an internal canvas.
1. Draw `testString`.
1. Check if any pixel has non-zero value.

[Here](https://codepen.io/rexrainbow/pen/OJJPwYv) is a test.

**Comment by ikeba** [comment]
Wow, looks like a magic :)

**Comment by rexrainbow** [comment]
Issue solved.
