### ISSUE TITLE
'complete' event from Scale and Fide

### ISSUE THREAD

**Issue by iKest** [rexrainbow/phaser3-rex-notes#52]
Good day!
Is it possible to add 'complete' event for the Scale and Fide clases like MoveTo when property destoy is false?
Thx.

**Comment by rexrainbow** [comment]
It is easy to add this feature, but I prefer not to add this feature. 
Scale and fade behavior are created for scale-down-destroy, or fade-out-destory more easier. Game object will be destroyed after scale-down/fade-out completed. thus, using 'destroy' event is a possible solution.
To have more features of scale/fade behavior, please use [tween task](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/tween/) directly. [Here](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/tween/#events) is events of tween task.

**Comment by rexrainbow** [comment]
Finally I still add 'complete' event into scale/fade behavior. 
I redirect internal tween task event to scale/fade, therefore it won't have to add extra event emitter.

**Comment by rexrainbow** [comment]
Issue solved.
