### ISSUE TITLE
TextArea: ugly adding new lines from the bottom when scrolling

### ISSUE THREAD

**Issue by iKest** [rexrainbow/phaser3-rex-notes#53]
Good day! Thx for yor great plugins.

I have a bit problem with TextArea. When scrolling, the bottom strings do arise no smoothly, but sharp. Your demo has the same problem.
Video showing the problem (pay attention to the lower bound of TextArea):
https://youtu.be/koA-c2IH8oQ

**Comment by rexrainbow** [comment]
Bug fixed, please download the latest version of rexUI plugins from github. And thanks for reporting this issue.

**Comment by rexrainbow** [comment]
Issue solved
