### ISSUE TITLE
LifeTime Plugin src link in docs not rworking

### ISSUE THREAD

**Issue by adrianoenrico** [rexrainbow/phaser3-rex-notes#54]
The links for the source code in [docs](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/lifetime/) is not working.

**Comment by adrianoenrico** [comment]
Neither is Sample usage

**Comment by adrianoenrico** [comment]
Just realized this is github. I'll get to it.

**Comment by rexrainbow** [comment]
Thanks for finding this link errors, they are fixed now.
