### ISSUE TITLE
Multiple rexBBCodeText on same scene makes the first one lose its lineHeight

### ISSUE THREAD

**Issue by vinerz** [rexrainbow/phaser3-rex-notes#58]
Hey Rex! First of all thanks for this amazing toolset. It does wonders!

I'm curious about commenting this line at `TextStyle.buildFont` from `TextBase`:

https://github.com/rexrainbow/phaser3-rex-notes/blob/2c0d3a3221256ee8446b2560cbc366003df4f01f/plugins/gameobjects/text/textbase/textstyle/TextStyle.js#L236

This works fine when there is not other BBCodeText elements on the same scene, but some weird lineHeight issues arise when adding multiple instances on a scene unless I remove this comment. The lines cover each other and become shorter.

But only uncommenting this brings some jittering when using it alongside `TextTyping`, because the **bold** styling usually makes the font a few pixels taller.

I made this shameful ugly hack because I'm short on time to think on an elegant solution, but basically it should only rebuild metrics when the font or its size changes, not the style:

```js
buildFont() {
  const oldFont = this._font;
  const newFont = this.fontStyle + ' ' + this.fontSize + ' ' + this.fontFamily;

  if(newFont !== this._font) {
    this._font = newFont;

    if(!oldFont.match(new RegExp(this.fontSize + ' ' + this.fontFamily))) {
      this.metrics = MeasureText(this);
    }
  }

  return this;
}
```

What are your thoughts?

**Comment by rexrainbow** [comment]
[Here](https://codepen.io/rexrainbow/pen/LYYdoZM) is a demo of creating 2 bbcodetext object with different default text size. Their lineHeight are different.

`buildFont` method is used to assign font (include style, size, and family) to canvas, to draw different font into a single text object.
`metrics` property is calculated according to default font, and get lineHeight from `metrics` property. 
A text object only has an uniform lineHeight for each line. Therefore `metrics` property won't be updated in `buildFont` method.
To get larger lineHeight, you might try to provide larger text size.

**Comment by dranitski** [comment]
@rexrainbow @vinerz Hi guys, I have noticed same bug with multiple BBCodeTexts, here is how to reproduce it

https://codepen.io/dranitski/pen/rNNrYed?editors=0010#0

**Comment by rexrainbow** [comment]
@dranitski 

Thanks for this sample code, bug fixed. You can see the correct result in that sample code now.

**Comment by rexrainbow** [comment]
Issue solved.
