### ISSUE TITLE
fix example

### ISSUE THREAD

**Issue by mishelen** [rexrainbow/phaser3-rex-notes#6]
Hello, good work!

you have some mistake in https://rexrainbow.github.io/phaser3-rex-notes/docs/site/arcade/index.html#add-a-game-object-to-physics-world: 
```js
scene.physics.existing(gameObject, isStatic);
```  
it have to be 
```js
scene.physics.add.existing(gameObject, isStatic);
```

**Comment by rexrainbow** [comment]
Thank you, this error has been fix now.
Sorry for missing this issue.
