### ISSUE TITLE
Visual artifacts when using nine-patch

### ISSUE THREAD

**Issue by dranitski** [rexrainbow/phaser3-rex-notes#60]
**UPD: created interactive version for that issue https://codepen.io/dranitski/pen/dyyLNNM**

Hi! To reproduce the issue you can include this code:

<details>

```javascript
import NinePatchPlugin from '../../plugins/ninepatch-plugin.js'

class Demo extends Phaser.Scene {
    constructor() {
        super({
            key: 'examples'
        })
    }

    preload() {
        this.load.image('bg3', 'assets/images/actionbox.png'); // 372 x 561
    }

    create() {

        this.add.rexNinePatch({
            x: 200, y: 430,
            width: 372*2, height: 561/2,
            key: 'bg3',
            columns: [100, undefined, 100],
            rows: [100, undefined, 100],
            stretchMode: 0
        }).setScale(0.5)

        this.add.rexNinePatch({
            x: 200, y: 200,
            width: 372*2, height: 561,
            key: 'bg3',
            columns: [100, undefined, 100],
            rows: [100, undefined, 100],
            stretchMode: 0
        }).setScale(0.5)

        this.add.rexNinePatch({
            x: 500, y: 200,
            width: 372/2, height: 561,
            key: 'bg3',
            columns: [100, undefined, 100],
            rows: [100, undefined, 100],
            stretchMode: 0
        }).setScale(0.5)
    }

    update() {
    }
}

var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scale: {
        mode: Phaser.Scale.FIT,
        autoCenter: Phaser.Scale.CENTER_BOTH,
    },
    scene: Demo,
    plugins: {
        global: [{
            key: 'rexNinePatch',
            plugin: NinePatchPlugin,
            start: true
        }]
    }
};

var game = new Phaser.Game(config);
```

</details>

into `examples/ninepatch/test.js` for example, then download this asset 
![actionbox](https://user-images.githubusercontent.com/27373393/69415618-001c6280-0d26-11ea-9d4f-9b4ebe3e36bd.png) and save as `assets/images/actionbox.png`, then run `main=./examples/ninepatch/test.js webpack` from root of project

**here is the problem:** 
![image](https://user-images.githubusercontent.com/27373393/69415724-335ef180-0d26-11ea-8fd1-07fd63c8dca3.png)
the middle part of image is being scaled and have strange visual artifacts even when I expect rexNinePatch instance to not scale the middle part at all. What I want to do here is just to use my UI element image and scale in not distorting corners.
More - stretchMode seems not affecting the result at all.

I am using Google Chrome Version 78.0.3904.87 (Official Build) (64-bit)
Phaser 3.20.1
latest rexplugins (just pulled, commit _a398246_)

thank you for your time

**Comment by rexrainbow** [comment]
Bug fixed in issue #61 . Thanks for reporting this issue.

**Comment by dranitski** [comment]
Thanks! The previous example seems working correctly now, but I have another one that is blowing my head

https://codepen.io/dranitski/pen/xxxeLMp

What I try to do is to have an element that can be resized to any w,h and still look fine because of corners not being scaled. Nothing extraordinary, I guess that kind of plugins are made to solve such tasks. I really don't understand what starts to happen with my sprite in this codepen.

will be glad if you can help finding out what is wrong

**Comment by rexrainbow** [comment]
#### Columns and rows properties
Nine-patch first cut source texture into grids, via *columns* and *rows* properties, they ought to be precise values based on source texture. 
Therefore, assign column width/row height via `w * 0.1`, `h * 0.3` is not a good idea. You won't get correct stretched result if columns and rows properties are not correct.

#### Minimum size
Nine patch is composed of fixed size and stretchable size parts. 
- Stretchable width/height could be 0
- Fixed width/height as its origin size (in current design)

Therefore nine patch will have a minimum size via fixed size parts.
In latest test code, minimum size is 74x74  (74 = 37+37). Once the given size is smaller than this minimum size (74x74), the render result might be weird.
Would you expect that resize fixed size parts if the size of nine patch game object is smaller than minimum size?

**Comment by rexrainbow** [comment]
I have updated a new version of nine-patch. 
In this latest nine-patch plugin, fixed parts will be scale-down when size of nine-patch is small than minimum size.

**Comment by dranitski** [comment]
> I have updated a new version of nine-patch.
> In this latest nine-patch plugin, fixed parts will be scale-down when size of nine-patch is small than minimum size.

Thanks, that was really what I needed. That fix is really handy. And thanks for your explanations!

**Comment by dranitski** [comment]
@rexrainbow sorry, there are still issues with scaling when ninepatch size is less then '_minimum size_'

Please take a look https://codepen.io/dranitski/pen/yLLrWdv

One ninepatch have **200** width and looks fine, but when I change width to **199** in have scaling issues.

**Comment by dranitski** [comment]
updated the pen https://codepen.io/dranitski/pen/yLLrWdv

it seem like there are still some issues even when ninepatch element size is bigger then '_minimum size_'

**Comment by rexrainbow** [comment]
Oops, you are right, I did not count parameters correctly. Now it is fixed, please download latest version of nine-patch plugin.

For test2 (https://i.ibb.co/ZXpx4wp/header-test.png), I need do more testing.

**Comment by rexrainbow** [comment]
Finally I know why the test2 looks weird.
The width of source image is `100`, and it cuts to 3 parts: `50`, `undefined`, `50`. The `undefined` part will be resolved to `0`, means no stretchable part image.
I add a warn message for this kind of invalid texture size, now console will dump
```
Size of Grid(0,1) = 50x0, which is invalid
Size of Grid(1,1) = 344x0, which is invalid
Size of Grid(2,1) = 50x0, which is invalid
```
and nine-patch will draw nothing for this kind of grid.

**Comment by dranitski** [comment]
I got it - when my image is 100 and config is [50,0,50] then nine patch can render nothing if it’s size is > 100 because it can not stretch the corners (50) and at the same time have nothing to stretch between them (0). So one must not set corners size (w, h or both) equal to source texture size to avoid that kind of issues. There should always be some space to stretch if needed.

Thanks for your time! I will test new version in my project tomorrow and close the issue If everything will work fine. Your 9-slice plugin in now first and best solution to nine patch images in phaser 3. 👍

**Comment by rexrainbow** [comment]
Thanks for your testing & reporting, too.

**Comment by dranitski** [comment]
thanks, works ok for now
