### ISSUE TITLE
nine-patch plugin seem to copy instead of stretching

### ISSUE THREAD

**Issue by dranitski** [rexrainbow/phaser3-rex-notes#61]
https://codepen.io/dranitski/pen/wvvZgaq here I created an example

I want your test texture middle part (the triangle) to be **stretched** according to [docs](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ninepatch/):
```
columns : Configuration of columns.
A number array, like [20, 20, 20], or [20, undefined, 20] : Width of each column. undefined value will be replaced by remainder value from texture width.
Width of odd columns (column 0, column 2, ...) will be origin width.
Width of even columns (column 1, column 3, ...) will be **stretched**.
```

But whatever **stretchMode** settings I pass it seems only to copy the middle part instead of stretching it.

Will be glad for any advice!

**Comment by rexrainbow** [comment]
Bug fixed, please download latest nine-patch plugin. Also thanks for reporting this issue.
