### ISSUE TITLE
rexUI: text-edit position after canvas resize #63

### ISSUE THREAD

**Issue by dranitski** [rexrainbow/phaser3-rex-notes#63]
![image](https://user-images.githubusercontent.com/27373393/69483066-000a8880-0e34-11ea-8b5c-a469ce9be93d.png)

pen: https://codepen.io/dranitski/pen/JjjVgjK

when I resize my game canvas that way my input element not updates its position. Seems like it renders on place it should before the scaling. 
I guess that happens because I update canvas style manually via
```javascript
    game.canvas.style.width = 800 + 'px';
    game.canvas.style.height = 600 + 'px';
```
Can I update input element somehow to respect new canvas size? Thanks in advance

**Comment by rexrainbow** [comment]
Here is the code to get input element (dom)
```javascript
var editor = scene.rexUI.edit(userNameField.getElement('text'), config);
var dom = editor.inputText.node;
```

- `editor.inputText` is a DOM game object of p3
- `editor.inputText.node` is a DOM

**Comment by dranitski** [comment]
Thanks, manipulating input DOM (updating its x,y) helped. I will use that as temporary solution until this Phaser3 scale manager bug will not be fixed https://github.com/photonstorm/phaser/issues/4862

after the fix I will be able to user FIT scale mode and stop changing canvas style manually.
