### ISSUE TITLE
Input box

### ISSUE THREAD

**Issue by Aashik30** [rexrainbow/phaser3-rex-notes#64]
I need to create the input box  only 'number'  type  in phaser3,
Could you please rply immediately?

**Comment by rexrainbow** [comment]
[Here](https://codepen.io/rexrainbow/pen/mddNbPj) is a test code of number-input.
set parameter `type` to `'number'`, in line 23.

**Comment by Aashik30** [comment]
ya its working, but i not need this type of dropdown inputbox,
I need without Dropdown inputbox  in 'number' type

**Comment by rexrainbow** [comment]
[Here](https://stackoverflow.com/questions/3790935/can-i-hide-the-html5-number-input-s-spin-box) is a CSS solution to disable input’s spin box.

To insert this css string, you might add an `id` property into config ([test](https://codepen.io/rexrainbow/pen/mddNbPj), line 23), then insert css in normal way (line 40~47). Note that this css style only work on chrome.

**Comment by Aashik30** [comment]
Sry i not need in html and css,
i need in phaser3.

**Comment by rexrainbow** [comment]
Input box is a dom. Therefore you can control it by html/css.

**Comment by Aashik30** [comment]
I cannot understand your conversation,
could you please tell me it is possible in phaser3?

**Comment by rexrainbow** [comment]
[Input text game object](https://codepen.io/rexrainbow/pen/mddNbPj), or this [text-editor](https://codepen.io/rexrainbow/pen/GaxqLZ) are based on [phaser3's built-in DOM game object](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/domelement/) ([official example](https://labs.phaser.io/view.html?src=src\game%20objects\dom%20element\input%20test.js)), which create an [input tag](https://www.w3schools.com/tags/tag_input.asp) to allow user type characters from keyboard.

**Comment by Aashik30** [comment]
Thanks,now its working, but the 'e' button also  in  that number type text game object,
how can i block that keyword?

**Comment by rexrainbow** [comment]
[Test code](https://codepen.io/rexrainbow/pen/mddNbPj), line 34-38. ([Reference](https://stackoverflow.com/questions/39291997/how-to-block-e-in-input-type-number))

**Comment by Aashik30** [comment]
thanks,its working fine,
How can i resize the width and height for PC resolution,

**Comment by Aashik30** [comment]
How can i set the PC screen resolution scale in scene?

**Comment by rexrainbow** [comment]
Please post this question on [phaser's forum](https://phaser.discourse.group/)

**Comment by Aashik30** [comment]
I taken the build in android,i type in the inputbox the page is minimize,
i share the image of the problem in the below,please tell any method to resolve that.
![Screenshot_2020-01-29-11-23-23-852_com house poker](https://user-images.githubusercontent.com/51227986/73331786-f9ace880-428a-11ea-8b3e-5eeed918c631.jpg)
![Screenshot_2020-01-29-11-23-28-904_com house poker](https://user-images.githubusercontent.com/51227986/73331787-fa457f00-428a-11ea-86d5-08450f2d28df.jpg)

**Comment by rexrainbow** [comment]
No idea, actually.
[Here](https://codepen.io/rexrainbow/full/ZEYQdem) is a demo using input text, at the bottom-center of window. window wont be minimized. since the js code (plugin) is the same, the issue might come from html/css.
