### ISSUE TITLE
Property 'rexRoundRectangle' does not exist on type 'GameObjectFactory'

### ISSUE THREAD

**Issue by inceabdullah** [rexrainbow/phaser3-rex-notes#66]
i use phaser template for typescript [Phaser3-Typescript-Template](https://github.com/inceabdullah/Phaser3-Typescript-Template). Your extention was my first extention. But i got error like `Property 'rexRoundRectangle' does not exist on type 'GameObjectFactory'` How to solve this problem.

`"phaser": "^3.21.0",`

i just wanted to create a rounded rectangle which i could load a physics body. it is not been with `this.add.graphics` from `Phaser.Scene` but your extention

i could create rectangle but i already get error

**Comment by rexrainbow** [comment]
Sorry I don't support typescript yet in my plugins.

**Comment by khasanovbi** [comment]
Hi, I want to support typescript for this library, if you have some time you can help me to cover types https://github.com/khasanovbi/phaser3-rex-plugins-types
