### ISSUE TITLE
UI plugin: dislpay element name with .drawBounds 

### ISSUE THREAD

**Issue by iKest** [rexrainbow/phaser3-rex-notes#67]
good day!
Is it possible to display the element name when calling drawBounds?
For example:
```
someElement.drawBounds(graphics, color, {
drawName: true, // default false
align, // align text element in bounds like anchor (or can it always display in the center of the element)
config //standart json text object config
});
```
thx!

**Comment by iKest** [comment]
or just better add a text object after the color, like: 
`someRexUIElement.drawBounds(graphics, color, text, align);`

**Comment by rexrainbow** [comment]
It is a nice feature suggestion.
`drawBounds` method will draw bounds of all children, on a graphics game object, displaying name of all children needs creating text game object of each child, therefore I will add anther class and method to manipulate these text game object, and graphics game object.

**Comment by rexrainbow** [comment]
Now `sizer.drawBounds(graphics, { name: true })` can display child name by text game object. More detail configuration:

```javascript
sizer.drawBounds(graphics, {
    color: 0xff0000,
    name: {
        createTextCallback: function(scene) {
            return scene.add.text(0, 0, '', { color: '#ff0' });
        },
        align: 'right-bottom'
    }
});
```

[Reference](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-basesizer/#draw-bounds)
