### ISSUE TITLE
Fix NPM 

### ISSUE THREAD

**Issue by Proder** [rexrainbow/phaser3-rex-notes#68]
Hi. 
I decided to use Your module in my project, but it is not installed via npm. (or I do not understand something)
Please correct this or explain what I am wrong about.

1) npm i phaser3-rex-plugins
2) import UIPlugin from 'phaser3-rex-plugins';
Res: Module not found: Error: Can't resolve 'phaser3-rex-plugins'

P.s. Thank you for your work.

**Comment by rexrainbow** [comment]
Try this one:
```javascript
import UIPlugin from 'phaser3-rex-plugins/templates/ui/ui-plugin.js';
```

**Comment by rexrainbow** [comment]
[Installing instruction](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-overview/#install-from-npm-package) added. Thanks for this suggestion.

**Comment by Proder** [comment]
It works. Thank you very much.
