### ISSUE TITLE
Typo in path of Gashapon.js file

### ISSUE THREAD

**Issue by bradtaniguchi** [rexrainbow/phaser3-rex-notes#7]
In the imports of the Gashapon file, there is a typo in the import path.
`import IsEmpty from 'rexPlugins/utils/Object/IsEmpty.js';` 
should be:
`import IsEmpty from 'rexPlugins/utils/object/IsEmpty.js'` 

Otherwise you get an error similar to "Module not found Error: can't resolve..." where it specifies the above "Object" path in the Gashapon file.

**Comment by rexrainbow** [comment]
Fixed.
