### ISSUE TITLE
Phaser3 Checkbox 

### ISSUE THREAD

**Issue by Aashik30** [rexrainbow/phaser3-rex-notes#72]
How to create a checkbox in phaser3?
Please Help me and Share the code link.

**Comment by rexrainbow** [comment]
I don't have checkbox yet, add it to TODO list.

**Comment by Aashik30** [comment]
Do you have any other chances?

**Comment by rexrainbow** [comment]
Sorry I don't have any other solution yet.

**Comment by rexrainbow** [comment]
[Here](https://codepen.io/rexrainbow/pen/PowMEjX) is an example of checkboxes using rexUI/buttons.
