### ISSUE TITLE
Is there any support for AMD loading, i.e RequireJs?

### ISSUE THREAD

**Issue by awweather** [rexrainbow/phaser3-rex-notes#73]
I can go through and convert all files to use Require, but that would take a while.  Is there any other work around?

**Comment by iKest** [comment]
All plugins can be loaded as resources using the default loader.

**Comment by awweather** [comment]
Hi, do you mean using this in the preLoad step?
scene.load.scenePlugin('rexuiplugin', 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/dist/rexuiplugin.min.js', 'rexUI', 'rexUI');

I have not had any luck getting that to register the plugin in the scene.

**Comment by iKest** [comment]
Yes, I load this plugin within the boot scene along with other assets. this also saves the size of the bundle by about 350kb and the time it takes to initialize the application.

The plugin, after initialization, has a link to the global scope: window .RexPlugins and is automatically registered in all scenes. **but you should add anather scenes only after loading the plugin by scene.scene.add, and not in the game config.**

**Comment by rexrainbow** [comment]
@awweather [Here](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-overview/#install-from-minify-file) is an installing instructions of my rexUI plugin, with minify js code.
