### ISSUE TITLE
phaser3 build issue

### ISSUE THREAD

**Issue by Aashik30** [rexrainbow/phaser3-rex-notes#75]
I have on issue in phaser3 build
This is the command "npm run build"
After build I run the file in browser, its shows the below error:
**

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///Applications/XAMPP/htdocs/Phaser3/Sample/build/Bg.png. (Reason: CORS request not http)

**
How to solve this issue?

**Comment by rexrainbow** [comment]
Please post phaser3 issue on [official phaser3 forums](https://phaser.discourse.group/).
