### ISSUE TITLE
ShakePosition plugin

### ISSUE THREAD

**Issue by jcyuan** [rexrainbow/phaser3-rex-notes#76]
is it possible to support multiple gameobjects shaking at the same time using `ShakePosition` plugin?
or just shake a `sizer`? not sure if it can shake a sizer container.
great plugin lib! thanks so much for your work!

**Comment by rexrainbow** [comment]
[Here](https://codepen.io/rexrainbow/pen/WNvGNBW) is a demo of using rexShakePosition with multiple circle shape game objects. rexShakePosition can be used on any kind of game object (included sizer game object) which has x, y properties.

**Comment by jcyuan** [comment]
@rexrainbow yes! I just had tested that directly shake a `sizer` object to achieve the group shaking effect, and everything work just fine, thanks again~ will close this.
