### ISSUE TITLE
[how to] about usage of the parameter `proportion`

### ISSUE THREAD

**Issue by jcyuan** [rexrainbow/phaser3-rex-notes#78]
Hi, sir, sorry there is a problem that make me a bit confused:

`sizer.add(child, proportion, align, paddingConfig, expand, childKey);`

    proportion :
        0, or 'min' : Place next game object closely. Default value.
        > 0 : Stretch game object via proportion value.
        null : Don't arrange this child.

`> 0 : Stretch game object via proportion value.`. I have tested this parameter and it seems this value can't affect anything? what does 'stretch' mean? to scale a gameObject or the padding edge?
so far in our project only used 0 / null but still wanna know what is this, thank.

**Comment by rexrainbow** [comment]
Proportion can be used to control the width/height of spaceing.

[Here](https://codepen.io/rexrainbow/pen/GRJNKPo) is a demo. The sizer has 3 children game objects
- Left zone game object, set `proportion` to 1,
- Text game object, set `proportion` to 0,
- Right zone game object, set `proportion` to 3

After size.layout():
- Left zone game object has small width, which equal to (sizer.width - text.displayWidth)***(1/(1+3))**
- Right zone game object has large width, (sizer.width - text.displayWidth)***(3/(1+3))**

**Comment by jcyuan** [comment]
AH I got it! it's a bit similar with the bootstrap's grid system: col-md-1, col-md-3, but more powerful because there can be some objects which have dynamic width in it!!

**Comment by jcyuan** [comment]
I'll keep this open so that peoples can understand too.

**Comment by rexrainbow** [comment]
I add that demo into [document](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/ui-sizer/#live-demos).
