### ISSUE TITLE
How to Draw GameObject (image) in Grid Cell?

### ISSUE THREAD

**Issue by flamendless** [rexrainbow/phaser3-rex-notes#79]
Hi, thank you for this awesome rexui plugin!

Im wondering how to draw a gameobject (sprite which is also interactive with `setInteractive()`) using the provided example live demo [here](https://codepen.io/rexrainbow/pen/XyJbWX) instead of the colored circle?

Thanks!

**Comment by rexrainbow** [comment]
Replace 
- line 94 `icon: scene.rexUI.add.roundRectangle(0, 0, 20, 20, 10, 0x0)`, to `icon: scene.add.image(0,0,key,frame)`, and 
- line 111 `cellContainer.getElement('icon').setFillStyle(item.color);` to `cellContainer.getElement('icon').setTexture(key, frame)`

**Comment by flamendless** [comment]
Thank you!
