### ISSUE TITLE
Virtual joystick demo with sprites

### ISSUE THREAD

**Issue by Brandoning** [rexrainbow/phaser3-rex-notes#8]
Please can you provide a demo with sprites (images) rather than game generated graphic objects...

It works fine using the demo, but when I use sprites I have issues clicking on and using the control. 

It seems to only trigger if clicked in the top left, and then dragged around. Clicking in top right or bottom half of virtual joystick control does not work.

```
x: this.cameras.cameras[0].worldView.width - (this.vjRadius * 2),
y: this.cameras.cameras[0].worldView.height - (this.vjRadius * 2),
radius: this.vjRadius,
fixed: true,
base: this.add.sprite(0, 0, 'joystick-bottom'),
thumb: this.add.sprite(0, 0, 'joystick-top'),
enable: true
```

**Comment by Brandoning** [comment]
(Radius is set to half of the width of the base image, base image 190px radius is 95)

**Comment by rexrainbow** [comment]
Thank you for finding this bug: the position of hit area in base game object is not correct when base game object is not Graphics.

Please download the latest version of [virtual joystick plugin](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/plugins/dist/rexvirtualjoystickplugin.min.js).
