### ISSUE TITLE
For UI Elements no color gradient support

### ISSUE THREAD

**Issue by lortschi** [rexrainbow/phaser3-rex-notes#81]
There is currently no built in method to create color gradient to button or label elements. Without this the buttons looks really poor colored.

**Comment by iKest** [comment]
ui elements are logic, not graphics, so these are the problems of the artist, not the developer. For example, I overlay several backround layers on an element. it looks quite good

**Comment by lortschi** [comment]
@iKest sorry I don't agree. So long the background is for a lable over the property scene.rexUI.add.label.background is to be defined is for me graphics. Ok please provide an example code how you do it with several backgounds to achive a gradient colorization. Thank you

**Comment by rexrainbow** [comment]
rexUI objects only *set position and size of children game objects*. Color gradient background is not belong rexUI.
Graphics game object does not support gradient. My [Canvas game object](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/canvas/) can fill color gradient, or using built-in [canvas texture](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/canvas-texture/).

**Comment by rexrainbow** [comment]
I add [Canvas](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/canvas/https://rexrainbow.github.io/phaser3-rex-notes/docs/site/canvas/) game object into rexUI, please download latest rexUI. 
[Here](https://codepen.io/rexrainbow/pen/vYOWjBr) is a demo of filling linear gradient on a Canvas background (line 40-57)

**Comment by lortschi** [comment]
@rexrainbow awesome, that's great, thanks a lot!!

**Comment by lortschi** [comment]
Sorry for commenting again, just a last thing, cause I needed it self. How I recognized the ui background canvas is not supporting roundRectangle. Here is a sample code I used to extend the canvas. Maybe you could give it to your source code:
`ctx.constructor.prototype.fillRoundedRect = function (xx,yy, ww,hh, rad, fill, stroke) {
            if (typeof(rad) == "undefined") rad = 5;
            this.beginPath();
            this.moveTo(xx+rad, yy);
            this.arcTo(xx+ww, yy,    xx+ww, yy+hh, rad);
            this.arcTo(xx+ww, yy+hh, xx,    yy+hh, rad);
            this.arcTo(xx,    yy+hh, xx,    yy,    rad);
            this.arcTo(xx,    yy,    xx+ww, yy,    rad);
            if (stroke) this.stroke();
            if (fill || typeof(fill)=="undefined") this.fill();
        };

To call: ctx.fillRoundedRect(0, 0, width, height, <angle number>);`
