### ISSUE TITLE
Add support for lists in BBCodeText

### ISSUE THREAD

**Issue by smshuja** [rexrainbow/phaser3-rex-notes#82]
There is nothing like your plugins in phaser ecosystem. So a big thank you.

One of the requests I have been getting from my project manager is to format the text better, so I began using BBCode, the available functionality is really good.  Adding support for lists would greatly enhance the utility of this plugin. 

Have you considered adding this?

### Example
```
[ol]
  [li]Item one[/li]
  [li]Item two[/li]
[/ol]

[ul]
  [li]Item one[/li]
  [li]Item two[/li]
[/ul]
```

**Comment by rexrainbow** [comment]
This request is too complex. Sorry I won't implement it.

**Comment by rexrainbow** [comment]
BBcode text game object can [insert image](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/bbcodetext/#image) in text canvas, you might try to mix item content string and bullet image.

**Comment by smshuja** [comment]
I can use text bullets, but it wraps to the next line, so kind of problematic. I think a combination of image bullet and a blank spacer image should work, even though its kind of ugly.

**Comment by rexrainbow** [comment]
Agree, formatting content and objects is another big issue.
