### ISSUE TITLE
Textarea internal fonts become thicker after entering text multiple times

### ISSUE THREAD

**Issue by akeboshi1** [rexrainbow/phaser3-rex-notes#84]
Textarea internal fonts become thicker after entering text multiple times，
for(let i =0;i<10;i++){
      textArea.appendText(val);
}
display fonts become thicker
How do I resolve this?

**Comment by akeboshi1** [comment]
I debugged and found that there is no problem using canvasText before it is displayed, but as long as it is displayed on the scene, multiple appendTexts will make the original display font on the textarea thicker, and it will become thicker without inputting it once.

**Comment by rexrainbow** [comment]
Could you provide a test code (runable in codepen is better) for this issue? I still can get your point.

**Comment by akeboshi1** [comment]
> Could you provide a test code (runable in codepen is better) for this issue? I still can get your point.

I was in the discussion group and received your reply. Try to find the problem of displaying textarea text in phaser.container, thank you
