### ISSUE TITLE
WEBGL_RENDERER is not defined error

### ISSUE THREAD

**Issue by 888dev** [rexrainbow/phaser3-rex-notes#87]
Hello,
I’m using yarn to install Phaser and Rex plugins.
```
"phaser": "^3.18.1",
"phaser3-rex-plugins": "^1.1.8",
```
I was trying to import UIPlugin into my scene
but I'm getting an error 
`**ReferenceError: WEBGL_RENDERER is not defined [Learn More] [index.js] [...]**`
Here an example of my code
```
import UIPlugin from 'phaser3-rex-plugins/templates/ui/ui-plugin.js';
const config = {
  type: Phaser.AUTO,
  scale: {
    mode: Phaser.Scale.FIT,
    width: 523,
    height: 830,
    parent: 'game'
  },
  physics: {
    default: 'arcade',
    arcade: {
      // debug: true
    }
  },
  audio: {
    context: audioContext
  },
  scene: [PreloadingScene, WelcomeScene, GameScene, EnterTicketScene, AwaitingScene],
  transparent: true,
  title: 'Game',
  plugins: {
    scene: [
      {
        key: 'rexUI',
        plugin: RexUIPlugin,
        mapping: 'rexUI'
      }
    ]
  }
};

window.game = new Phaser.Game(config);
```

I would really appreciate your help, Am I missing something?

**Comment by rexrainbow** [comment]
If you are using webpack, try to add [these code](https://github.com/rexrainbow/phaser3-rex-notes/blob/master/webpack.config.js#L53-L57) in to webpack.config.js file.
```javascript
...
    plugins: [
        new webpack.DefinePlugin({
            __DEV__: JSON.stringify(JSON.parse(process.env.BUILD_DEV || 'true')),
            WEBGL_RENDERER: true,
            CANVAS_RENDERER: true
        }),
    ]
...
```

**Comment by 888dev** [comment]
@rexrainbow I was using create-react-app, and webpack is managed by react in my case, do you know any other way to do so?

**Comment by kevo1ution** [comment]
@888dev It seems like you have to run `npm run eject` if you did create-react-app. This allows you to access the webpack.config.js file in `config/webpack.config.js`.

**Comment by 888dev** [comment]
@kevo1ution yeah I know about this option, I just don't really wanna do this as it will require to manage all webpack by myself. 
I'll try to find another way to do that.

**Comment by kevo1ution** [comment]
@888dev You could also use something like this https://github.com/timarney/react-app-rewired. But I'm not sure if they allow you to insert exactly the ```plugins: [new webpack.DefinePlugin({...})]``` into the right place. It seems that you would have to override the entire react function that returns the webpack config object. Let me know your thoughts because I have a similar problem.

**Comment by rexrainbow** [comment]
I remove these variables in my plugins, webgl and canvas renders are all included, thus user dose not need to add them into webpack config  anymore.
