### ISSUE TITLE
rexUI - Menu error when clicking outside the menu

### ISSUE THREAD

**Issue by peelingSun** [rexrainbow/phaser3-rex-notes#88]
Hi,

Not sure if I'm doing something wrong or if it's a potential issue but in the codepen and my project both I have the issue where clicking outside of the already open menu will give me this error: 
To reproduce it, I opened the menu's children options and tried to click out of the menu.

![image](https://user-images.githubusercontent.com/45033804/78159075-0fb46200-7410-11ea-9b70-380552c4737e.png)

**Comment by rexrainbow** [comment]
Sorry I can't reproduce this issue, could you list more detail step-by-step instructions?

**Comment by rexrainbow** [comment]
This bug might be fixed, please get latest version of rexUI.

**Comment by peelingSun** [comment]
Thanks for the input. I tried it again and it seems to have been fixed. Thanks and amazing plugins
