### ISSUE TITLE
Get error when start a scene using plugin rexUI

### ISSUE THREAD

**Issue by raphlee** [rexrainbow/phaser3-rex-notes#9]
## Version
* Phaser Version: 3.14 and 3.15.1
* Operating system: Windows 10
* Browser: Google Chrome | 70.0.3538.102 (Official Build) (64-bit) (cohort: Stable)

## Description
My game have plugin rexUI from [rexUI](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/index.html) to create a simple scroll view (use GridTable) in a scene called Menu. Everything works fine, until I click an item view, this call a callback to start a scene (called Game). In console, it showed error and the game got frozen.
Actually, the game got frozen in version 3.14. When I update to version (just downloaded in webs) 3.15.1, it no longer frozen, the Game scene is loaded but the error still thrown.

## Code
Import plugin in scene (Menu)

`preload() {
        this.load.scenePlugin({
            key: 'rexuiplugin',
            url: 'assets/libs/rexuiplugin.min.js',
            sceneKey: 'rexUI'
        });
    }`

Event:

`// event
        table.on('cell.click', function (cellContainer, cellIndex) {
                console.log('Game scene with index ' + cellIndex);
                this.scene.start('Game');
            }, this);`

Here is screen shot:
![error](https://user-images.githubusercontent.com/16055569/49235428-ab088200-f42c-11e8-8a72-623f74687e64.PNG)

---
It's linked to issue I post in [Phaser Issue](https://github.com/photonstorm/phaser/issues/4204)

**Comment by rexrainbow** [comment]
Thank you for this reporting, it is a bug in my plugin, which I turn off scene event when that scene has been destroyed.
This bug hass been fixed, please get the lastest version of my ui plugins.

**Comment by raphlee** [comment]
thx @rexrainbow . I will check it out.

**Comment by raphlee** [comment]
Hey, I've get the lastest version, but event 'cell.click' is not working anymore, I checked event 'over', it' fine. You can see the example [here](https://codepen.io/rexrainbow/full/BGKvXK/).
