### ISSUE TITLE
Importing plugin causes Phaser.Renderer is undefined

### ISSUE THREAD

**Issue by johnunderwood** [rexrainbow/phaser3-rex-notes#90]
I wanted to add a scrollable panel to a new game I was developing, and I've spent the morning figuring out gulp, so it can properly bundle my js and fix the paths that wouldn't resolve correctly in this plugin. I get to the end of all that to find that including the plugin files causes an error in the console "Phaser.Renderer is undefined". I went ahead and removed a ton of code to make sure I wasn't doing something wrong, and I still can get that error to appear/disappear by uncommenting/commenting the import line. I tried 
import UIPlugin from 'phaser3-rex-plugins/templates/ui/ui-plugin.js'; 
and 
import { ScrollablePanel } from 'phaser3-rex-plugins/templates/ui/ui-components.js';
both of which error with "Phaser.Renderer is undefined"
I also tried
this.load.scenePlugin('rexuiplugin', 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/dist/rexuiplugin.min.js', 'rexUI', 'rexUI');
in the preload function, and it both errors with "Invalid Scene Plugin: rexUI" as a warning, and then errors with the same "Phaser.Renderer is undefined"

Here's my game.js, first two lines are commented, but if I run this through gulp with either of these uncommented(and the load.scenePlugin line commented), same errors I said above:

// import { ScrollablePanel } from 'phaser3-rex-plugins/templates/ui/ui-components.js';
// import UIPlugin from 'phaser3-rex-plugins/templates/ui/ui-plugin.js';

var Menu = new Phaser.Class({

    Extends: Phaser.Scene,

    initialize:

    function Menu ()
    {
        Phaser.Scene.call(this, { key: 'menu' } );
    },

    preload: function()
    {
      this.load.scenePlugin('rexuiplugin', 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/dist/rexuiplugin.min.js', 'rexUI', 'rexUI');
    },

    create: function ()
    {
        const loadDeckButton = this.add.text( 0, 0, 'Load Decks', { font: '30px Arial', fill: '#FFFFFF', align: 'left' } );
        Phaser.Display.Align.In.Center( loadDeckButton, this.add.zone( screen.width * .5, screen.height * .3 ) );
    },

});

var config = {
    type: Phaser.AUTO,
    scale: {
      mode: Phaser.Scale.FIT,
      parent: 'game',
      autoCenter: Phaser.Scale.CENTER_BOTH,
      width: "100%",
      height: "100%",
    },
    backgroundColor: '#000000',
    scene: [ Menu ]
};

var game = new Phaser.Game(config);

and my index file is

<!DOCTYPE html>
<html>
<head>
	<title>Card Game</title>
	<script src="https://cdn.jsdelivr.net/npm/phaser@3.22.0/dist/phaser-arcade-physics.min.js"></script>
	<script src="/src/js/game.js" type="module"></script>
	<style>
		html, body {
			border: 0;
			margin: 0;
			padding: 0;
		}
	</style>
</head>
<body>
	<div id="game"></div>
</body>
</html>

I would love to know if there's a simple reason why Phaser.Renderer is undefined? Or is this something more serious? Did I forget to include something in my setup? Any help is appreciated, thank you!

**Comment by rexrainbow** [comment]
Try this phaser cdn **https://cdn.jsdelivr.net/npm/phaser@3.22.0/dist/phaser.min.js**, I have no idea why *phaser-arcade-physics.min.js* dose not work.

**Comment by johnunderwood** [comment]
> Try this phaser cdn **https://cdn.jsdelivr.net/npm/phaser@3.22.0/dist/phaser.min.js**, I have no idea why _phaser-arcade-physics.min.js_ dose not work.

I tried this, and it now is upset WebGL is undefined. Please let me know if you have any ideas. Thanks for the quick response!

Uncaught TypeError: Cannot read property 'WebGL' of undefined
    at eval (FillPathWebGL.js:7)
    at Object../node_modules/phaser3-rex-plugins/plugins/gameobjects/shape/utils/FillPathWebGL.js (bundle.js:1066)
    at __webpack_require__ (bundle.js:20)
    at eval (WebGLRenderer.js:7)
    at Object../node_modules/phaser3-rex-plugins/plugins/gameobjects/shape/roundrectangle/render/WebGLRenderer.js (bundle.js:1043)
    at __webpack_require__ (bundle.js:20)
    at eval (Render.js:2)
    at Module../node_modules/phaser3-rex-plugins/plugins/gameobjects/shape/roundrectangle/render/Render.js (bundle.js:1032)
    at __webpack_require__ (bundle.js:20)
    at eval (RoundRectangle.js:7)
(anonymous) @ FillPathWebGL.js:7
./node_modules/phaser3-rex-plugins/plugins/gameobjects/shape/utils/FillPathWebGL.js @ bundle.js:1066
__webpack_require__ @ bundle.js:20
(anonymous) @ WebGLRenderer.js:7
./node_modules/phaser3-rex-plugins/plugins/gameobjects/shape/roundrectangle/render/WebGLRenderer.js @ bundle.js:1043
__webpack_require__ @ bundle.js:20
(anonymous) @ Render.js:2
./node_modules/phaser3-rex-plugins/plugins/gameobjects/shape/roundrectangle/render/Render.js @ bundle.js:1032
__webpack_require__ @ bundle.js:20
(anonymous) @ RoundRectangle.js:7
./node_modules/phaser3-rex-plugins/plugins/gameobjects/shape/roundrectangle/RoundRectangle.js @ bundle.js:997
__webpack_require__ @ bundle.js:20
(anonymous) @ RoundRectangle.js:2
./node_modules/phaser3-rex-plugins/templates/ui/roundrectangle/RoundRectangle.js @ bundle.js:4071
__webpack_require__ @ bundle.js:20
(anonymous) @ Factory.js:2
./node_modules/phaser3-rex-plugins/templates/ui/roundrectangle/Factory.js @ bundle.js:4059
__webpack_require__ @ bundle.js:20
(anonymous) @ ui-plugin.js:3
./node_modules/phaser3-rex-plugins/templates/ui/ui-plugin.js @ bundle.js:4959
__webpack_require__ @ bundle.js:20
(anonymous) @ game.js:2
./src/js/game.js @ bundle.js:5199
__webpack_require__ @ bundle.js:20
(anonymous) @ bundle.js:84
(anonymous) @ bundle.js:87

**Comment by rexrainbow** [comment]
[Here](https://codepen.io/rexrainbow/pen/YMyBom) is a test case, dose this test case work fine in your browser?

**Comment by johnunderwood** [comment]
That works fine.

**Comment by rexrainbow** [comment]
That case use `https://cdn.jsdelivr.net/npm/phaser@3.22.0/dist/phaser.min.js` as phaser engine file, and install rexUI via 
```javascript
        this.load.scenePlugin({
            key: 'rexuiplugin',
            url: 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/dist/rexuiplugin.min.js',
            sceneKey: 'rexUI'
        }); 
```
(line 13)
And, without using any packing tool chain (ex. webpack)

**Comment by johnunderwood** [comment]
> That case use `https://cdn.jsdelivr.net/npm/phaser@3.22.0/dist/phaser.min.js` as phaser engine file, and install rexUI via
> 
> ```js
>         this.load.scenePlugin({
>             key: 'rexuiplugin',
>             url: 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/dist/rexuiplugin.min.js',
>             sceneKey: 'rexUI'
>         }); 
> ```
> 
> (line 13)
> without using any packing tool chain (ex. webpack)

This seems to have worked for me, and I'm currently trying to implement it. Thanks!
