### ISSUE TITLE
"Phaser.Renderer is undefined" error when loading rexbbcodetextplugin.min.js

### ISSUE THREAD

**Issue by fmatulic** [rexrainbow/phaser3-rex-notes#92]
When preloading the BBCode text plugin using
`this.load.plugin('rexbbcodetextplugin', 'https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/dist/rexbbcodetextplugin.min.js', true);`
there's a `TypeError: Phaser.Renderer is undefined`.

To confirm that it wasn't anything to do with my code environment, I copy-pasted the example from here [https://codepen.io/rexrainbow/pen/OZbOyg]() and I get the same error.

Using the latest version of Phaser (3.23.0) on Mac OS and testing on Firefox.

**Comment by rexrainbow** [comment]
I upgrade phaser.min.js file to [3.23.0](https://cdn.jsdelivr.net/npm/phaser@3.23.0/dist/phaser.min.js) in that [demo](https://codepen.io/rexrainbow/pen/OZbOyg). It works fine. Test in window10, firefox.

[*Phaser.Renderer is undefined* issue](https://github.com/rexrainbow/phaser3-rex-notes/issues/90) is reported before.

**Comment by fmatulic** [comment]
Ok so it seems there was a similar [issue for another plugin](https://github.com/rexrainbow/phaser3-rex-notes/issues/90) and I tried your suggested URL to load the phaser script https://cdn.jsdelivr.net/npm/phaser@3.23.0/dist/phaser.min.js (I was using `phaser-arcade-physics.min.js`) and that worked. Thanks.

**Comment by rexrainbow** [comment]
Phaser has [Render](https://github.com/photonstorm/phaser/blob/master/src/phaser.js#L39) module, but  [phaser-arcade-physics](https://github.com/photonstorm/phaser/blob/master/src/phaser-arcade-physics.js) dose not have, from the source code of phaser3 engine.
