### ISSUE TITLE
Youtube player removed/not working?

### ISSUE THREAD

**Issue by futuremarc** [rexrainbow/phaser3-rex-notes#94]
Hi rex 👋🏻! Big fan, very grateful I found your work! I can't seem to get the youtube class working, and it looks like you're removing it from the next release unless I'm miss understanding something?

https://github.com/rexrainbow/phaser3-rex-notes/commit/5e0b4dd0a578c50f75ce428795023d39d641628b

Can I get some insight?

My code is just following the example so I think it should be working.

**Comment by rexrainbow** [comment]
You can get youtube player plugin back from [here](https://raw.githubusercontent.com/rexrainbow/phaser3-rex-notes/master/dist/rexyoutubeplayerplugin.min.js) ([document](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/youtubeplayer/))

I try to reduce the size of rexUI plugins, and I thought youtube player might be rarely used, so I removed it from rexUI plugins.
