### ISSUE TITLE
trying to follow the textbox sample code and roundedRectangle results in this error

### ISSUE THREAD

**Issue by Tercra** [rexrainbow/phaser3-rex-notes#95]
![image](https://user-images.githubusercontent.com/61608467/80695442-ee44a580-8aa3-11ea-9f52-92e84e601d9e.png)

**Comment by rexrainbow** [comment]
[Demo](https://codepen.io/rexrainbow/pen/MzGoJv) works fine. Could you post a simplest test code for your case?

**Comment by Tercra** [comment]
since i imported it as a class, I wrote it like this:

this.add.existing(new RoundRectangle(x,y,width, height, radius, color);

was basically doing as instructed so I'm not sure what was wrong, but this was the problem line in question.

**Comment by rexrainbow** [comment]
[Here](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/shape-roundrectangle/#import-class) is the instruction of using RoundRectangle class, import from 'plugins/roundrectangle.js', not 'dist/rexroundrectangleplugin.min.js'

'rexroundrectangleplugin.js' is the phaser3 plugin to install factory of RoundRectangle game object ( `scene.add.rexRoundRectangle(...)`)

**Comment by rexrainbow** [comment]
```javascript
this.add.existing(new RoundRectangle(this, x,y,width, height, radius, color);
```
The first parameter is `scene` object.

**Comment by Tercra** [comment]
i'm doing it inside a  class extending scene, so "this" should be correct

**Comment by rexrainbow** [comment]
Could you provide a simplest runnable test code for this issue?

**Comment by Tercra** [comment]
......
I got it to work somehow after fidgeting it for a while, after basically making my own version for my project.
Weird how life works.
Sorry for the trouble.
