### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by L3gomancer** [rexrainbow/phaser3-rex-notes#96]
Typo in snippets in step 3 "offset in pxiels"
https://github.com/rexrainbow/phaser3-rex-notes/blob/ae86d504b0206315ce7fdeabcae1da5b8b1a3025/docs/docs/tilemap.md#add-tile-map-object

**Comment by rexrainbow** [comment]
I will export document few days later, thanks for this type reporting.

**Comment by rexrainbow** [comment]
Document updated.
