### ISSUE TITLE
Url tag for bbcode plugin

### ISSUE THREAD

**Issue by DrSchizo** [rexrainbow/phaser3-rex-notes#99]
Hi,

The bbcode plugin is great. Thank you for sharing it, as well as all the other Rex plugin.

Are you planning to add the [url] tag for creating link?
It is possible to emulate it with the [area] tag, but it is a bit complicated to do for such a common tag. Such a tag can be really useful in the credit scene, for instance to link to Phaser page.

Have a nice day and thank you again!

**Comment by rexrainbow** [comment]
Open new tab when clicking hit-area is very easy to implement, [here](https://codepen.io/rexrainbow/pen/voXPRM) is a live demo.

1. In area tag, use a pre-defined key `url:xxx`, for url key
    ```javascript
    var IsURLKey = function (key) { return (key.substring(0, 4) === 'url:'); }
    ```
2. Once click url area, get url string from remainder string, 
    ```javascript
    var GetURL = function(key) { return key.substring(4, key.length); }
    ```
3. Use it to open new tab
    ```javascript
    window.open(GetURL(key), '_blank');
    ```

**Comment by DrSchizo** [comment]
Thanks a lot, that is what I thought so.

I want my phaser game to be compatible with Sandbox Adventure Engine, that I made. This framework allows game creators to write down text [using standard bbcode](url=http://sandbox-adventure.com/faq/how-to-write-dialogue-and-narration.html). I guess I can write a function that translate all [url=$1]$2[/url] tags to [area=url:$1]$2[/area].

**Comment by rexrainbow** [comment]
The 'goto url' action has many possible options:
- 'goto url' action might insert in pointer-down, or pointer-up event, or have more conditions.
- URL key might be the address of url, or a key mapping to address of url.
- 'goto url' action might open a window in a new tab, or just open url in current window.

Thus I would like to use `area` to implement `go to url` feature.
